// packages/hashtree-web/src/components/FollowsTreesView.svelte
<script lang="ts">
  /**
   * FollowsTreesView - shows trees from followed users
   */
  import { nostrStore } from '../nostr';
  import { createFollowsStore } from '../stores/follows';

  let pubkey = $derived($nostrStore.pubkey);
  let followsStore = $derived(pubkey ? createFollowsStore(pubkey) : null);
  let follows = $derived(followsStore ? $followsStore : null);
  let followCount = $derived(follows?.follows?.length ?? 0);
</script>

<div class="flex-1 flex flex-col min-h-0">
  <div class="h-10 shrink-0 px-4 border-b border-surface-3 flex items-center bg-surface-1">
    <span class="text-sm font-medium text-text-1">Following</span>
  </div>
  <div class="flex-1 overflow-auto p-4 text-muted text-sm">
    {#if followCount === 0}
      Not following anyone
    {:else}
      No trees from followed users
    {/if}
  </div>
</div>

// packages/hashtree-web/src/components/FollowsTreesView.tsx
/**
 * FollowsTreesView - shows trees from followed users on the home page
 */
import { useFollowsTrees } from '../hooks/useFollowsTrees';
import { useDelayedLoading } from '../hooks/useDelayedLoading';
import { TreeRow } from './TreeRow';

export function FollowsTreesView() {
  const { trees, loading, followsCount } = useFollowsTrees();
  const showLoading = useDelayedLoading(loading);

  if (loading && !showLoading) {
    return null;
  }

  if (showLoading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-text-3 p-8">
        <span className="i-lucide-loader-2 animate-spin text-2xl mb-3" />
        <span className="text-sm">Loading follows...</span>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col min-h-0">
      <div className="px-4 py-3 border-b border-surface-3">
        <span className="text-sm font-medium text-text-2">Follows</span>
      </div>
      {trees.length === 0 ? (
        <div className="p-3 text-text-3 text-sm">
          {followsCount === 0
            ? 'No follows yet'
            : `No trees from ${followsCount} follow${followsCount === 1 ? '' : 's'}`}
        </div>
      ) : (
        <div className="flex-1 overflow-auto">
        {trees.map((tree) => (
          <TreeRow
            key={`${tree.pubkey}-${tree.name}`}
            to={`/${tree.npub}/${encodeURIComponent(tree.name)}`}
            pubkey={tree.pubkey}
            npub={tree.npub}
            icon="folder"
            label={tree.name}
            showAuthorName
            timestamp={tree.created_at * 1000}
          />
        ))}
        </div>
      )}
    </div>
  );
}
