// examples/explorer/src/components/RecentsView.tsx
/**
 * RecentsView - shows recently visited locations on the home page
 */
import { Link } from 'react-router-dom';
import { useRecents, clearRecents } from '../hooks';

export function RecentsView() {
  const recents = useRecents();

  if (recents.length === 0) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-text-3 p-8">
        <span className="i-lucide-clock text-4xl mb-3" />
        <span className="text-sm">No recent activity</span>
        <span className="text-xs mt-1">Visit a folder to see it here</span>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col min-h-0">
      <div className="px-4 py-3 border-b border-surface-3 flex items-center justify-between">
        <span className="text-sm font-medium text-text-2">Recent</span>
        <button
          onClick={() => clearRecents()}
          className="btn-ghost text-xs px-2 py-1"
        >
          Clear
        </button>
      </div>
      <div className="flex-1 overflow-auto">
        {recents.map((item, i) => (
          <Link
            key={`${item.path}-${i}`}
            to={item.path}
            className="p-3 border-b border-surface-2 flex items-center gap-3 no-underline text-text-1 hover:bg-surface-1"
          >
            <span className={`shrink-0 ${getIcon(item.type)}`} />
            <div className="flex-1 min-w-0">
              <div className="truncate">{item.label}</div>
              {item.treeName && (
                <div className="text-xs text-text-3 truncate">
                  {item.treeName}
                </div>
              )}
            </div>
            <span className="text-xs text-text-3 shrink-0">
              {formatTimeAgo(item.timestamp)}
            </span>
          </Link>
        ))}
      </div>
    </div>
  );
}

function getIcon(type: string): string {
  switch (type) {
    case 'tree':
      return 'i-lucide-folder text-warning';
    case 'file':
      return 'i-lucide-file text-text-2';
    case 'hash':
      return 'i-lucide-link text-accent';
    default:
      return 'i-lucide-folder text-warning';
  }
}

function formatTimeAgo(timestamp: number): string {
  const seconds = Math.floor((Date.now() - timestamp) / 1000);

  if (seconds < 60) return 'now';
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h`;
  if (seconds < 604800) return `${Math.floor(seconds / 86400)}d`;
  return `${Math.floor(seconds / 604800)}w`;
}

// packages/hashtree-web/src/components/RecentsView.svelte
<script lang="ts">
  /**
   * RecentsView - shows recently accessed files and trees
   */
  import { recentsStore, type RecentItem } from '../stores/recents';
  import { navigate } from '../utils/navigate';

  let recents = $derived($recentsStore);

  function getIcon(type: RecentItem['type']): { icon: string; color: string } {
    switch (type) {
      case 'tree': return { icon: 'i-lucide-folder', color: 'text-warning' };
      case 'dir': return { icon: 'i-lucide-folder', color: 'text-warning' };
      case 'file': return { icon: 'i-lucide-file', color: 'text-text-2' };
      case 'hash': return { icon: 'i-lucide-link', color: 'text-accent' };
      default: return { icon: 'i-lucide-file', color: 'text-text-2' };
    }
  }

  function formatTime(timestamp: number): string {
    const now = Date.now();
    const diff = now - timestamp;
    const minutes = Math.floor(diff / 60000);
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(diff / 86400000);

    if (minutes < 1) return 'Just now';
    if (minutes < 60) return `${minutes}m ago`;
    if (hours < 24) return `${hours}h ago`;
    if (days < 7) return `${days}d ago`;
    return new Date(timestamp).toLocaleDateString();
  }

  function handleClick(item: RecentItem) {
    navigate(item.path);
  }
</script>

<div class="flex-1 flex flex-col min-h-0">
  <div class="h-10 shrink-0 px-4 border-b border-surface-3 flex items-center bg-surface-1">
    <span class="text-sm font-medium text-text-1">Recent</span>
    {#if recents.length > 0}
      <span class="ml-2 text-xs text-text-3">{recents.length}</span>
    {/if}
  </div>
  <div class="flex-1 overflow-auto">
    {#if recents.length === 0}
      <div class="p-4 text-muted text-sm">
        No recent items
      </div>
    {:else}
      <div class="divide-y divide-surface-2">
        {#each recents as item (item.path)}
          {@const iconInfo = getIcon(item.type)}
          <button
            class="w-full px-4 py-2 flex items-center gap-3 hover:bg-surface-1 transition-colors text-left"
            onclick={() => handleClick(item)}
          >
            <span class="{iconInfo.icon} {iconInfo.color} shrink-0"></span>
            <div class="flex-1 min-w-0">
              <div class="text-sm text-text-1 truncate">{item.label}</div>
              {#if item.treeName}
                <div class="text-xs text-text-3 truncate">{item.treeName}</div>
              {/if}
            </div>
            <span class="text-xs text-text-3 shrink-0">{formatTime(item.timestamp)}</span>
          </button>
        {/each}
      </div>
    {/if}
  </div>
</div>
