// packages/iris-files/src/components/RecentsView.svelte
<script lang="ts">
  /**
   * RecentsView - shows recently accessed files and trees
   */
  import { nip19 } from 'nostr-tools';
  import { recentsStore, clearRecents, type RecentItem } from '../stores/recents';
  import { TreeRow } from './ui';

  let recents = $derived($recentsStore);

  function npubToPubkey(npub: string): string | null {
    try {
      const decoded = nip19.decode(npub);
      if (decoded.type === 'npub') {
        return decoded.data as string;
      }
    } catch {}
    return null;
  }

  function formatTime(timestamp: number): string {
    const now = Date.now();
    const diff = now - timestamp;
    const minutes = Math.floor(diff / 60000);
    const hours = Math.floor(diff / 3600000);
    const days = Math.floor(diff / 86400000);

    if (minutes < 1) return 'Just now';
    if (minutes < 60) return `${minutes}m ago`;
    if (hours < 24) return `${hours}h ago`;
    if (days < 7) return `${days}d ago`;
    return new Date(timestamp).toLocaleDateString();
  }

  function isFolder(item: RecentItem): boolean {
    return item.type === 'tree' || item.type === 'dir' || item.type === 'hash';
  }

  function buildHref(item: RecentItem): string {
    // Encode treeName in path: /npub/treeName -> /npub/encodedTreeName
    const encodedPath = item.treeName
      ? `/${item.npub}/${encodeURIComponent(item.treeName)}`
      : item.path;
    const base = `#${encodedPath}`;
    return item.linkKey ? `${base}?k=${item.linkKey}` : base;
  }
</script>

<div class="flex-1 flex flex-col min-h-0">
  <div class="h-10 shrink-0 px-4 border-b border-surface-3 flex items-center">
    <span class="text-sm font-medium text-text-1">Recent</span>
    {#if recents.length > 0}
      <span class="ml-2 text-xs text-text-3">{recents.length}</span>
      <button
        class="ml-auto btn-ghost text-xs px-2 py-1"
        onclick={() => clearRecents()}
        title="Clear recents"
      >
        Clear
      </button>
    {/if}
  </div>
  <div class="flex-1 overflow-auto">
    {#if recents.length === 0}
      <div class="p-4 text-muted text-sm">
        No recent items
      </div>
    {:else}
      <div>
        {#each recents as item (item.path)}
          <TreeRow
            href={buildHref(item)}
            name={item.label}
            isFolder={isFolder(item)}
            ownerPubkey={item.npub ? npubToPubkey(item.npub) : null}
            showHashIcon={item.type === 'hash'}
            hasKey={item.hasKey}
            visibility={item.visibility}
            time={formatTime(item.timestamp)}
            class={item.type === 'hash' ? 'font-mono' : ''}
          />
        {/each}
      </div>
    {/if}
  </div>
</div>

// packages/hashtree-web/src/components/RecentsView.tsx
/**
 * RecentsView - shows recently visited locations on the home page
 */
import { useRecents, clearRecents } from '../hooks';
import { npubToPubkey } from '../nostr';
import { TreeRow } from './TreeRow';

export function RecentsView() {
  const recents = useRecents();

  if (recents.length === 0) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center text-text-3 p-8">
        <span className="i-lucide-clock text-4xl mb-3" />
        <span className="text-sm">No recent activity</span>
        <span className="text-xs mt-1">Visit a folder to see it here</span>
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col min-h-0">
      <div className="px-4 py-3 border-b border-surface-3 flex items-center justify-between">
        <span className="text-sm font-medium text-text-2">Recent</span>
        <button
          onClick={() => clearRecents()}
          className="btn-ghost text-xs px-2 py-1"
        >
          Clear
        </button>
      </div>
      <div className="flex-1 overflow-auto">
        {recents.map((item, i) => (
          <TreeRow
            key={`${item.path}-${i}`}
            to={item.path}
            pubkey={item.npub ? npubToPubkey(item.npub) || undefined : undefined}
            npub={item.npub}
            icon={getIcon(item.type)}
            label={item.label}
            subtitle={item.treeName}
            timestamp={item.timestamp}
          />
        ))}
      </div>
    </div>
  );
}

function getIcon(type: string): 'folder' | 'file' | 'hash' {
  switch (type) {
    case 'tree':
    case 'dir':
    case 'hash':
      return 'folder';
    case 'file':
      return 'file';
    default:
      return 'folder';
  }
}
