// packages/iris-files/src/components/ui/TreeRow.svelte
<script lang="ts">
  /**
   * TreeRow - reusable row component for displaying trees/folders
   * Used in FileBrowser, RecentsView, FollowsTreesView
   */
  import type { TreeVisibility } from 'hashtree';
  import { Avatar } from '../User';
  import VisibilityIcon from '../VisibilityIcon.svelte';
  import { getFileIcon } from '../../utils/fileIcon';

  interface Props {
    /** URL to navigate to (optional - if not provided, renders as div) */
    href?: string | null;
    /** Display name */
    name: string;
    /** Whether this is a folder (true) or file (false) */
    isFolder?: boolean;
    /** Visibility level */
    visibility?: TreeVisibility | null;
    /** Where to show visibility icon: 'left' (after avatar), 'right' (after name) */
    visibilityPosition?: 'left' | 'right';
    /** Owner's pubkey (shows avatar) */
    ownerPubkey?: string | null;
    /** Show hash icon instead of avatar (for permalinks) */
    showHashIcon?: boolean;
    /** Whether item has encryption key */
    hasKey?: boolean;
    /** File size (for files) */
    size?: string | null;
    /** Time string to display */
    time?: string | null;
    /** Whether this row is selected/active */
    selected?: boolean;
    /** Whether this row is focused (keyboard nav) */
    focused?: boolean;
    /** Whether this row was recently changed */
    recentlyChanged?: boolean;
    /** Additional classes */
    class?: string;
  }

  let {
    href = null,
    name,
    isFolder = true,
    visibility = null,
    visibilityPosition = 'left',
    ownerPubkey = null,
    showHashIcon = false,
    hasKey = false,
    size = null,
    time = null,
    selected = false,
    focused = false,
    recentlyChanged = false,
    class: className = '',
  }: Props = $props();

  let icon = $derived(isFolder ? 'i-lucide-folder' : getFileIcon(name));
  let iconColor = $derived(isFolder ? 'text-warning' : 'text-text-2');

  let baseClass = $derived(
    `flex items-center gap-2 text-text-1
    ${selected ? 'bg-surface-2' : href ? 'hover:bg-surface-2/50' : ''}
    ${focused ? 'ring-2 ring-inset ring-accent' : ''}
    ${recentlyChanged && !selected ? 'animate-pulse-live' : ''}
    ${className}`
  );

  let rowClass = $derived(
    href
      ? `w-full p-3 border-b border-surface-2 no-underline ${baseClass}`
      : `min-w-0 ${baseClass}`
  );
</script>

{#snippet content()}
  {#if ownerPubkey}
    <Avatar pubkey={ownerPubkey} size={20} class="shrink-0" />
  {:else if showHashIcon}
    <span class="i-lucide-hash text-accent shrink-0"></span>
  {/if}

  <!-- Visibility on left (after avatar, before folder icon) -->
  {#if visibilityPosition === 'left'}
    {#if visibility}
      <VisibilityIcon {visibility} class="text-text-3 shrink-0" />
    {:else if showHashIcon}
      {#if hasKey}
        <span class="relative inline-block shrink-0 text-text-3" title="Encrypted">
          <span class="i-lucide-link"></span>
          <span class="i-lucide-lock absolute -bottom-0.5 -right-1.5 text-[0.6em]"></span>
        </span>
      {:else}
        <span class="i-lucide-globe text-text-3 shrink-0" title="Public"></span>
      {/if}
    {/if}
  {/if}

  <span class="{icon} {iconColor} shrink-0"></span>
  <span class="text-sm text-text-1 truncate flex-1 min-w-0">{name}</span>

  <!-- Visibility on right (after name) -->
  {#if visibilityPosition === 'right'}
    {#if visibility}
      <VisibilityIcon {visibility} class="text-text-2 shrink-0" />
    {:else if showHashIcon}
      {#if hasKey}
        <span class="relative inline-block shrink-0 text-text-2" title="Encrypted">
          <span class="i-lucide-link"></span>
          <span class="i-lucide-lock absolute -bottom-0.5 -right-1.5 text-[0.6em]"></span>
        </span>
      {:else}
        <span class="i-lucide-globe text-text-2 shrink-0" title="Public"></span>
      {/if}
    {/if}
  {/if}

  {#if size}
    <span class="text-xs text-text-3 shrink-0">{size}</span>
  {/if}

  {#if time}
    <span class="text-xs text-text-3 shrink-0">{time}</span>
  {/if}
{/snippet}

{#if href}
  <a {href} class={rowClass}>
    {@render content()}
  </a>
{:else}
  <div class={rowClass}>
    {@render content()}
  </div>
{/if}

// packages/hashtree-web/src/components/TreeRow.tsx
/**
 * TreeRow - shared row component for tree/file listings
 */
import { Link } from 'react-router-dom';
import type { TreeVisibility } from 'hashtree';
import { navigate } from '../utils/navigate';
import { Avatar, Name } from './user';
import { VisibilityIcon } from './VisibilityIcon';

export interface TreeRowProps {
  to: string;
  pubkey?: string;
  npub?: string;
  icon: 'folder' | 'file' | 'hash';
  label: string;
  subtitle?: string;
  showAuthorName?: boolean;
  timestamp: number;
  /** @deprecated Use visibility instead */
  encrypted?: boolean;
  visibility?: TreeVisibility;
}

export function TreeRow({
  to,
  pubkey,
  npub,
  icon,
  label,
  subtitle,
  showAuthorName,
  timestamp,
  encrypted,
  visibility,
}: TreeRowProps) {
  const typeIconClass = icon === 'folder'
    ? 'i-lucide-folder text-warning'
    : icon === 'file'
      ? 'i-lucide-file text-text-2'
      : 'i-lucide-folder text-warning'; // hash items show folder icon

  return (
    <Link
      to={to}
      className="p-3 border-b border-surface-2 flex items-center gap-3 no-underline text-text-1 hover:bg-surface-1"
    >
      {pubkey && npub ? (
        <button
          onClick={(e) => { e.preventDefault(); e.stopPropagation(); navigate(`/${npub}`); }}
          className="shrink-0 bg-transparent border-none p-0 cursor-pointer hover:opacity-80"
        >
          <Avatar pubkey={pubkey} size={24} />
        </button>
      ) : (
        <span className="shrink-0 w-6 h-6 flex items-center justify-center">
          <span className="i-lucide-hash text-accent" />
        </span>
      )}
      <span className={`shrink-0 ${typeIconClass}`} />
      <div className="flex-1 min-w-0">
        <div className="truncate">{label}</div>
        {(subtitle || showAuthorName) && (
          <div className="text-xs text-text-3 truncate">
            {showAuthorName && pubkey ? <Name pubkey={pubkey} /> : subtitle}
          </div>
        )}
      </div>
      {visibility !== undefined ? (
        <VisibilityIcon visibility={visibility} className="text-text-3" />
      ) : encrypted !== undefined && (
        <span
          className={`shrink-0 ${encrypted ? 'i-lucide-lock' : 'i-lucide-globe'} text-text-3`}
          title={encrypted ? 'Encrypted' : 'Public'}
        />
      )}
      <span className="text-xs text-text-3 shrink-0">
        {formatTimeAgo(timestamp)}
      </span>
    </Link>
  );
}

function formatTimeAgo(timestamp: number): string {
  const seconds = Math.floor((Date.now() - timestamp) / 1000);

  if (seconds < 60) return 'now';
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h`;
  if (seconds < 604800) return `${Math.floor(seconds / 86400)}d`;
  return `${Math.floor(seconds / 604800)}w`;
}
