// packages/hashtree-web/src/components/User/Name.svelte
<script lang="ts">
  import { createProfileStore, getProfileName } from '../../hooks/useProfile';
  import { animalName } from '../../utils/animalName';

  interface Props {
    pubkey: string;
    class?: string;
  }

  let { pubkey, class: className = '' }: Props = $props();

  let profileStore = $derived(createProfileStore(pubkey));
  let profile = $derived($profileStore);
  let profileName = $derived(getProfileName(profile, pubkey));
  let animal = $derived(animalName(pubkey));
</script>

{#if profileName}
  <span class="truncate {className}">{profileName}</span>
{:else}
  <!-- Animal name fallback (styled differently) -->
  <span class="truncate italic opacity-70 {className}">
    {animal}
  </span>
{/if}

// examples/explorer/src/components/user/Name.tsx
import { useProfile, getProfileName } from '../../hooks/useProfile';
import { animalName } from '../../utils/animalName';

interface Props {
  pubkey: string;
  class?: string;
  className?: string;
}

/**
 * Display name with profile fetch and animal name fallback
 */
export function Name({ pubkey, class: classProp, className }: Props) {
  const cssClass = classProp || className;
  const profile = useProfile(pubkey);
  const profileName = getProfileName(profile, pubkey);

  if (profileName) {
    return <span className={`truncate ${cssClass || ''}`}>{profileName}</span>;
  }

  // Animal name fallback (styled differently)
  const animal = animalName(pubkey);
  return (
    <span className={`truncate italic opacity-70 ${cssClass || ''}`}>
      {animal}
    </span>
  );
}
