// packages/iris-files/src/components/Viewer/DirectoryActions.svelte
<script lang="ts">
  /**
   * DirectoryActions - empty state with upload zone and README display
   * Port of React DirectoryActions component
   */
  import { getTree, decodeAsText } from '../../store';
  import { nostrStore } from '../../nostr';
  import { routeStore, currentDirCidStore, treeRootStore, createTreesStore, directoryEntriesStore, createGitInfoStore } from '../../stores';
  import FolderActions from '../FolderActions.svelte';
  import GitRepoView from '../Git/GitRepoView.svelte';
  import ReadmePanel from './ReadmePanel.svelte';
  import ViewerHeader from './ViewerHeader.svelte';
  import { uploadFiles } from '../../stores/upload';
  import { LinkType, type TreeEntry as HashTreeEntry } from 'hashtree';

  let route = $derived($routeStore);
  let rootCid = $derived($treeRootStore);
  let rootHash = $derived(rootCid?.hash ?? null);
  let currentDirCid = $derived($currentDirCidStore);
  let currentPath = $derived(route.path);
  let dirEntries = $derived($directoryEntriesStore);
  let entries = $derived(dirEntries.entries);

  let viewedNpub = $derived(route.npub);
  let currentTreeName = $derived(route.treeName);
  let userNpub = $derived($nostrStore.npub);
  let isLoggedIn = $derived($nostrStore.isLoggedIn);

  // Get current tree for visibility info
  let targetNpub = $derived(viewedNpub || userNpub);
  let treesStore = $derived(createTreesStore(targetNpub));
  let trees = $state<Array<{ name: string; visibility?: string }>>([]);

  $effect(() => {
    const store = treesStore;
    const unsub = store.subscribe(value => {
      trees = value;
    });
    return unsub;
  });

  let currentTree = $derived(currentTreeName ? trees.find(t => t.name === currentTreeName) : null);

  let canEdit = $derived(!viewedNpub || viewedNpub === userNpub || !isLoggedIn);

  // Quick check if this looks like a git repo (has .git directory)
  // This allows us to show tabs immediately without waiting for async git info
  let hasGitDir = $derived(entries.some((e: HashTreeEntry) => e.name === '.git' && e.type === LinkType.Dir));

  // Check if we're inside a git repo subdirectory (gitRoot propagated via URL)
  let gitRootFromUrl = $derived(route.gitRoot);
  let isInGitRepo = $derived(hasGitDir || gitRootFromUrl !== null);

  // Resolve git root CID when we're in a subdirectory
  // If at git root (hasGitDir), use currentDirCid
  // If in subdirectory (gitRootFromUrl), resolve the path to get git root CID
  let gitRootCid = $state<typeof currentDirCid>(null);

  $effect(() => {
    if (hasGitDir) {
      // We're at the git root - use current directory CID
      gitRootCid = currentDirCid;
    } else if (gitRootFromUrl !== null && rootCid) {
      // We're in a subdirectory - resolve gitRoot path to get CID
      const tree = getTree();
      const pathParts = gitRootFromUrl === '' ? [] : gitRootFromUrl.split('/');

      let cancelled = false;
      (async () => {
        try {
          if (pathParts.length === 0) {
            // Git root is at tree root
            if (!cancelled) gitRootCid = rootCid;
          } else {
            // Resolve path to get git root CID
            const result = await tree.resolvePath(rootCid, pathParts.join('/'));
            if (!cancelled && result) {
              gitRootCid = result.cid;
            }
          }
        } catch {
          // Failed to resolve - fall back to null
          if (!cancelled) gitRootCid = null;
        }
      })();
      return () => { cancelled = true; };
    } else {
      gitRootCid = null;
    }
  });

  // Full git info (branches, etc) - loaded async using git root CID
  let gitInfoStore = $derived(createGitInfoStore(gitRootCid));
  let gitInfo = $state<{ isRepo: boolean; currentBranch: string | null; branches: string[]; loading: boolean }>({
    isRepo: false,
    currentBranch: null,
    branches: [],
    loading: true,
  });

  $effect(() => {
    const store = gitInfoStore;
    const unsub = store.subscribe(value => {
      gitInfo = value;
    });
    return unsub;
  });
  // Show actions if we have a tree OR we're in a tree context (empty tree that hasn't been created yet)
  let hasTreeContext = $derived(rootHash !== null || (route.treeName !== null && canEdit));

  let readmeContent = $state<string | null>(null);
  let isDraggingOver = $state(false);
  let fileInputRef: HTMLInputElement | undefined = $state();

  // Find and load README.md
  $effect(() => {
    readmeContent = null;
    const readmeEntry = entries.find(
      (e: HashTreeEntry) => e.name.toLowerCase() === 'readme.md' && e.type !== LinkType.Dir
    );
    if (!readmeEntry) return;

    let cancelled = false;
    getTree().readFile(readmeEntry.cid).then(data => {
      if (!cancelled && data) {
        const text = decodeAsText(data);
        if (text) readmeContent = text;
      }
    });
    return () => { cancelled = true; };
  });

  function openFilePicker() {
    fileInputRef?.click();
  }

  async function handleFileInputChange(e: Event) {
    const input = e.target as HTMLInputElement;
    const files = input.files;
    if (files && files.length > 0) {
      await uploadFiles(files);
    }
    // Reset input so same file can be selected again
    input.value = '';
  }

  // Handle external file drop
  async function handleFileDrop(e: DragEvent) {
    e.preventDefault();
    isDraggingOver = false;
    if (!canEdit) return;

    const files = e.dataTransfer?.files;
    if (files && files.length > 0) {
      await uploadFiles(files);
    }
  }

  function handleFileDragOver(e: DragEvent) {
    if (!canEdit) return;
    if (e.dataTransfer?.types.includes('Files')) {
      e.preventDefault();
      e.dataTransfer.dropEffect = 'copy';
      isDraggingOver = true;
    }
  }

  function handleFileDragLeave(e: DragEvent) {
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    if (
      e.clientX < rect.left ||
      e.clientX > rect.right ||
      e.clientY < rect.top ||
      e.clientY > rect.bottom
    ) {
      isDraggingOver = false;
    }
  }

  // Check if should hide actions (locked unlisted/private)
  let hideActions = $derived(
    rootCid?.hash && !rootCid?.key && currentTree &&
    (currentTree.visibility === 'unlisted' || currentTree.visibility === 'private')
  );

  // Build back URL (parent directory or tree list)
  let backUrl = $derived.by(() => {
    const parts: string[] = [];
    if (route.npub && route.treeName) {
      // In a tree - go to parent dir or tree list
      if (currentPath.length > 0) {
        // In a subdirectory - go to parent
        parts.push(route.npub, route.treeName, ...currentPath.slice(0, -1));
      } else {
        // At tree root - go to tree list
        parts.push(route.npub);
      }
    }
    const linkKeySuffix = route.linkKey ? `?k=${route.linkKey}` : '';
    return '#/' + parts.map(encodeURIComponent).join('/') + linkKeySuffix;
  });

  // Get current directory name
  let currentDirName = $derived.by(() => {
    if (currentPath.length > 0) {
      return currentPath[currentPath.length - 1];
    }
    return currentTreeName || '';
  });
</script>

<!-- If this is a git repo or inside one (via gitRoot URL param), show GitHub-style directory listing -->
{#if isInGitRepo && currentDirCid}
  <div class="flex flex-col h-full">
    <!-- Header with back button, avatar, visibility, folder name -->
    <ViewerHeader
      {backUrl}
      npub={viewedNpub}
      isPermalink={route.isPermalink}
      {rootCid}
      visibility={currentTree?.visibility}
      icon="i-lucide-folder-open text-warning"
      name={currentDirName}
    />
    <div class="flex-1 overflow-auto">
      <GitRepoView
        dirCid={currentDirCid}
        {gitRootCid}
        {entries}
        {canEdit}
        currentBranch={gitInfo.currentBranch}
        branches={gitInfo.branches}
      />
    </div>
  </div>
{:else}
  <div
    class="flex flex-col h-full"
    ondragover={handleFileDragOver}
    ondragleave={handleFileDragLeave}
    ondrop={handleFileDrop}
  >
    <!-- Header with back button, avatar, visibility, folder name -->
    <ViewerHeader
      {backUrl}
      npub={viewedNpub}
      isPermalink={route.isPermalink}
      {rootCid}
      visibility={currentTree?.visibility}
      icon="i-lucide-folder-open text-warning"
      name={currentDirName}
    />
    <!-- Action buttons - hide when viewing locked unlisted/private directory -->
    {#if hasTreeContext && !hideActions}
      <div class="p-3 shrink-0">
        <FolderActions dirCid={currentDirCid} {canEdit} />
      </div>
    {/if}

  <!-- Upload drop zone -->
  {#if hasTreeContext && canEdit && !readmeContent}
    <div
      class="flex-1 mx-3 mb-3 flex items-center justify-center cursor-pointer transition-colors border border-surface-3 rounded-lg {isDraggingOver ? 'bg-surface-1/50' : 'hover:bg-surface-1/50'}"
      onclick={openFilePicker}
      role="button"
      tabindex="0"
      onkeydown={(e) => { if (e.key === 'Enter' || e.key === ' ') openFilePicker(); }}
    >
      <div class="flex flex-col items-center text-text-3">
        <span class="i-lucide-plus text-4xl mb-2"></span>
        <span class="text-sm">Drop or click to add</span>
      </div>
      <input
        bind:this={fileInputRef}
        type="file"
        multiple
        class="hidden"
        onchange={handleFileInputChange}
      />
    </div>
  {/if}

  <!-- README.md content -->
  {#if readmeContent}
    <div class="flex-1 overflow-auto px-3 pb-3">
      <ReadmePanel content={readmeContent} {entries} {canEdit} />
    </div>
  {/if}
  </div>
{/if}

// packages/hashtree-web/src/components/viewer/DirectoryActions.tsx
/**
 * DirectoryActions - empty state with upload zone and README display
 * Also handles special directory types like .yjs documents and git repos
 */
import { useState, useEffect, useRef } from 'react';
import { getTree, decodeAsText } from '../../store';
import { ReadmePanel } from './ReadmePanel';
import { useNostrStore } from '../../nostr';
import { useRoute, useCurrentDirCid, useDirectoryEntries, useTreeRoot, useTrees, useCurrentPath } from '../../hooks';
import { useGitInfo } from '../../hooks/useGit';
import { FolderActions } from '../FolderActions';
import { useUpload } from '../../hooks/useUpload';
import { YjsDocument } from '../YjsDocument';
import { GitRepoView } from './GitRepoView';

export function DirectoryActions() {
  const rootCid = useTreeRoot();
  const rootHash = rootCid?.hash ?? null;
  const currentDirCid = useCurrentDirCid();
  const { entries } = useDirectoryEntries(currentDirCid);
  const currentPath = useCurrentPath();
  const route = useRoute();
  const viewedNpub = route.npub;
  const currentTreeName = route.treeName;
  const userNpub = useNostrStore(s => s.npub);
  const isLoggedIn = useNostrStore(s => s.isLoggedIn);
  const { uploadFiles } = useUpload();

  // Get current tree for visibility info
  const targetNpub = viewedNpub || userNpub;
  const trees = useTrees(targetNpub);
  const currentTree = currentTreeName ? trees.find(t => t.name === currentTreeName) : null;

  const canEdit = !viewedNpub || viewedNpub === userNpub || !isLoggedIn;
  // Show actions if we have a tree OR we're in a tree context (empty tree that hasn't been created yet)
  const hasTreeContext = rootHash !== null || (route.treeName !== null && canEdit);
  const [readmeContent, setReadmeContent] = useState<string | null>(null);
  const [isDraggingOver, setIsDraggingOver] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Check if current directory contains a .yjs file (indicates Yjs document directory)
  const yjsConfigFile = entries.find(e => e.name === '.yjs' && !e.isTree);
  const isYjsDoc = !!yjsConfigFile;

  // Check if current directory is a git repo
  const gitInfo = useGitInfo(currentDirCid);

  const openFilePicker = () => {
    fileInputRef.current?.click();
  };

  const handleFileInputChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      await uploadFiles(files);
    }
    // Reset input so same file can be selected again
    e.target.value = '';
  };

  // Handle external file drop
  const handleFileDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    setIsDraggingOver(false);
    if (!canEdit) return;

    const files = e.dataTransfer?.files;
    if (files && files.length > 0) {
      await uploadFiles(files);
    }
  };

  const handleFileDragOver = (e: React.DragEvent) => {
    if (!canEdit) return;
    if (e.dataTransfer?.types.includes('Files')) {
      e.preventDefault();
      e.dataTransfer.dropEffect = 'copy';
      setIsDraggingOver(true);
    }
  };

  const handleFileDragLeave = (e: React.DragEvent) => {
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    if (
      e.clientX < rect.left ||
      e.clientX > rect.right ||
      e.clientY < rect.top ||
      e.clientY > rect.bottom
    ) {
      setIsDraggingOver(false);
    }
  };

  // Find and load README.md
  useEffect(() => {
    setReadmeContent(null);
    const readmeEntry = entries.find(
      e => e.name.toLowerCase() === 'readme.md' && !e.isTree
    );
    if (!readmeEntry) return;

    let cancelled = false;
    // readFile takes CID directly
    getTree().readFile(readmeEntry.cid).then(data => {
      if (!cancelled && data) {
        const text = decodeAsText(data);
        if (text) setReadmeContent(text);
      }
    });
    return () => { cancelled = true; };
  }, [entries]);

  // If this is a .yjs directory, render the YjsDocument viewer
  // Use a key based on document identity (npub + treeName + path) to force remount when navigating
  // between different documents.
  // Note: We don't require rootCid here - YjsDocument handles its own loading state.
  // This prevents the component from remounting when rootCid updates (which causes loading spinner).
  if (isYjsDoc && currentDirCid) {
    const docKey = `${viewedNpub || userNpub || 'local'}/${route.treeName || ''}/${currentPath.join('/')}`;
    return <YjsDocument key={docKey} dirCid={currentDirCid} entries={entries} />;
  }

  // If this is a git repo, show GitHub-style directory listing with README
  if (gitInfo.isRepo && currentDirCid) {
    return <GitRepoView dirCid={currentDirCid} entries={entries} canEdit={canEdit} />;
  }

  return (
    <div
      className="flex flex-col h-full"
      onDragOver={handleFileDragOver}
      onDragLeave={handleFileDragLeave}
      onDrop={handleFileDrop}
    >
      {/* Action buttons - hide when viewing locked unlisted/private directory */}
      {hasTreeContext && !(rootCid?.hash && !rootCid?.key && currentTree && (currentTree.visibility === 'unlisted' || currentTree.visibility === 'private')) && (
        <div className="p-3 shrink-0">
          <FolderActions dirCid={currentDirCid ?? undefined} canEdit={canEdit} />
        </div>
      )}

      {/* Upload drop zone */}
      {hasTreeContext && canEdit && !readmeContent && (
        <div
          className={`flex-1 mx-3 mb-3 flex items-center justify-center cursor-pointer transition-colors border border-surface-3 rounded-lg ${isDraggingOver ? 'bg-surface-1/50' : 'hover:bg-surface-1/50'}`}
          onClick={openFilePicker}
        >
          <div className="flex flex-col items-center text-text-3">
            <span className="i-lucide-plus text-4xl mb-2" />
            <span className="text-sm">Drop or click to add</span>
          </div>
          <input
            ref={fileInputRef}
            type="file"
            multiple
            className="hidden"
            onChange={handleFileInputChange}
          />
        </div>
      )}

      {/* README.md content */}
      {readmeContent && (
        <div className="flex-1 overflow-auto px-4 pb-4">
          <ReadmePanel content={readmeContent} entries={entries} canEdit={canEdit} />
        </div>
      )}
    </div>
  );
}
