// packages/hashtree-web/src/components/HtmlViewer.tsx
/**
 * HTML Viewer with directory context
 *
 * Renders HTML files in a sandboxed iframe with access to sibling files
 * from the same directory. Uses blob URLs and script injection to intercept
 * resource loading.
 */
import { useEffect, useState, useMemo } from 'react';
import type { CID } from 'hashtree';
import { getTree } from '../store';

interface HtmlViewerProps {
  /** The HTML content to render */
  html: string;
  /** CID of the parent directory */
  directoryCid: CID;
  /** Filename for the title */
  filename?: string;
}

interface DirectoryFile {
  name: string;
  data: Uint8Array;
  mimeType: string;
}

/**
 * Get MIME type from filename
 */
function getMimeType(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase() || '';
  const mimeTypes: Record<string, string> = {
    // Images
    'png': 'image/png',
    'jpg': 'image/jpeg',
    'jpeg': 'image/jpeg',
    'gif': 'image/gif',
    'webp': 'image/webp',
    'svg': 'image/svg+xml',
    'ico': 'image/x-icon',
    'bmp': 'image/bmp',
    // CSS/JS
    'css': 'text/css',
    'js': 'text/javascript',
    'mjs': 'text/javascript',
    // Fonts
    'woff': 'font/woff',
    'woff2': 'font/woff2',
    'ttf': 'font/ttf',
    'otf': 'font/otf',
    'eot': 'application/vnd.ms-fontobject',
    // Data
    'json': 'application/json',
    'xml': 'application/xml',
    'txt': 'text/plain',
    // HTML
    'html': 'text/html',
    'htm': 'text/html',
  };
  return mimeTypes[ext] || 'application/octet-stream';
}

/**
 * Recursively collect all files from a directory tree
 */
async function collectDirectoryFiles(
  dirCid: CID,
  basePath: string = ''
): Promise<DirectoryFile[]> {
  const tree = getTree();
  const entries = await tree.listDirectory(dirCid);
  const files: DirectoryFile[] = [];

  for (const entry of entries) {
    const fullPath = basePath ? `${basePath}/${entry.name}` : entry.name;

    if (entry.isTree) {
      // Recursively collect subdirectory
      const subFiles = await collectDirectoryFiles(entry.cid, fullPath);
      files.push(...subFiles);
    } else {
      const data = await tree.readFile(entry.cid);
      if (data) {
        files.push({
          name: fullPath,
          data,
          mimeType: getMimeType(entry.name),
        });
      }
    }
  }

  return files;
}


/**
 * Inline resources directly into HTML for security
 * This avoids needing allow-same-origin in the sandbox
 */
function inlineResources(html: string, files: DirectoryFile[]): string {
  // Create a map of filename -> file data
  const fileMap = new Map<string, DirectoryFile>();
  for (const file of files) {
    fileMap.set(file.name.toLowerCase(), file);
  }

  let result = html;

  // Inline <script src="..."> as <script>content</script>
  result = result.replace(
    /<script([^>]*)\ssrc\s*=\s*["']([^"']+)["']([^>]*)><\/script>/gi,
    (match, before, src, after) => {
      const cleanSrc = src.replace(/^\.?\//, '').toLowerCase();
      const file = fileMap.get(cleanSrc);
      if (file && (file.mimeType === 'text/javascript' || file.mimeType === 'application/javascript')) {
        const content = new TextDecoder().decode(file.data);
        return `<script${before}${after}>${content}</script>`;
      }
      return match;
    }
  );

  // Inline <link rel="stylesheet" href="..."> as <style>content</style>
  result = result.replace(
    /<link([^>]*)rel\s*=\s*["']stylesheet["']([^>]*)href\s*=\s*["']([^"']+)["']([^>]*)>/gi,
    (match, before1, before2, href, after) => {
      const cleanHref = href.replace(/^\.?\//, '').toLowerCase();
      const file = fileMap.get(cleanHref);
      if (file && file.mimeType === 'text/css') {
        const content = new TextDecoder().decode(file.data);
        return `<style>${content}</style>`;
      }
      return match;
    }
  );

  // Also handle href before rel
  result = result.replace(
    /<link([^>]*)href\s*=\s*["']([^"']+)["']([^>]*)rel\s*=\s*["']stylesheet["']([^>]*)>/gi,
    (match, before1, href, before2, after) => {
      const cleanHref = href.replace(/^\.?\//, '').toLowerCase();
      const file = fileMap.get(cleanHref);
      if (file && file.mimeType === 'text/css') {
        const content = new TextDecoder().decode(file.data);
        return `<style>${content}</style>`;
      }
      return match;
    }
  );

  // Convert images to data URLs
  result = result.replace(
    /(<img[^>]*\s)src\s*=\s*["']([^"']+)["']/gi,
    (match, prefix, src) => {
      if (src.startsWith('http://') || src.startsWith('https://') ||
          src.startsWith('data:') || src.startsWith('blob:')) {
        return match;
      }
      const cleanSrc = src.replace(/^\.?\//, '').toLowerCase();
      const file = fileMap.get(cleanSrc);
      if (file && file.mimeType.startsWith('image/')) {
        const base64 = btoa(String.fromCharCode(...file.data));
        return `${prefix}src="data:${file.mimeType};base64,${base64}"`;
      }
      return match;
    }
  );

  // Convert url() in CSS to data URLs
  result = result.replace(
    /url\(\s*["']?([^"')]+)["']?\s*\)/gi,
    (match, url) => {
      if (url.startsWith('http://') || url.startsWith('https://') ||
          url.startsWith('data:') || url.startsWith('blob:')) {
        return match;
      }
      const cleanUrl = url.replace(/^\.?\//, '').toLowerCase();
      const file = fileMap.get(cleanUrl);
      if (file && (file.mimeType.startsWith('image/') || file.mimeType.startsWith('font/'))) {
        const base64 = btoa(String.fromCharCode(...file.data));
        return `url("data:${file.mimeType};base64,${base64}")`;
      }
      return match;
    }
  );

  return result;
}

export function HtmlViewer({ html, directoryCid, filename }: HtmlViewerProps) {
  const [files, setFiles] = useState<DirectoryFile[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Load directory files
  useEffect(() => {
    let cancelled = false;

    async function loadFiles() {
      try {
        setLoading(true);
        const dirFiles = await collectDirectoryFiles(directoryCid);
        if (!cancelled) {
          setFiles(dirFiles);
          setLoading(false);
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load directory');
          setLoading(false);
        }
      }
    }

    loadFiles();
    return () => { cancelled = true; };
  }, [directoryCid]);

  // Create modified HTML with inlined resources (only when files are loaded)
  const modifiedHtml = useMemo(() => {
    if (loading) {
      return '';
    }

    // Inline all resources directly into HTML for security
    // This allows us to use sandbox="allow-scripts" without allow-same-origin
    return files.length > 0
      ? inlineResources(html, files)
      : html;
  }, [html, files, loading]);

  if (error) {
    return (
      <div className="p-4 text-error">
        Error loading directory: {error}
      </div>
    );
  }

  // Show loading state while collecting directory files
  if (loading) {
    return (
      <div className="w-full h-full flex items-center justify-center text-muted">
        Loading resources...
      </div>
    );
  }

  return (
    <iframe
      srcDoc={modifiedHtml}
      className="block w-full h-full border-none bg-surface-0"
      title={filename}
      sandbox="allow-scripts"
    />
  );
}

/**
 * Check if HTML viewer with directory context should be used
 * (when the file is HTML and we have a directory context)
 */
export function shouldUseHtmlViewer(filename: string | undefined): boolean {
  if (!filename) return false;
  const lower = filename.toLowerCase();
  return lower.endsWith('.html') || lower.endsWith('.htm');
}

// packages/hashtree-web/src/components/Viewer/HtmlViewer.svelte
<script lang="ts">
  /**
   * HtmlViewer - renders HTML content in a sandboxed iframe
   * Resources are resolved relative to the current directory
   */
  import { routeStore, currentDirCidStore, directoryEntriesStore } from '../../hooks';
  import { getTree } from '../../store';
  import type { TreeEntry } from 'hashtree';

  interface Props {
    content: string;
    fileName: string;
  }

  let { content, fileName }: Props = $props();

  let route = $derived($routeStore);
  let currentDirCid = $derived($currentDirCidStore);
  let dirEntries = $derived($directoryEntriesStore);
  let entries = $derived(dirEntries.entries);

  // Build a map of files in current directory for resource lookup
  let fileMap = $derived.by(() => {
    const map = new Map<string, TreeEntry>();
    for (const entry of entries) {
      map.set(entry.name, entry);
    }
    return map;
  });

  // Recursively resolve path segments to get an entry
  async function resolveRelativePath(pathParts: string[], currentEntries: TreeEntry[]): Promise<TreeEntry | null> {
    if (pathParts.length === 0) return null;

    const [first, ...rest] = pathParts;

    // Handle ".." by going up (not supported in sandboxed view)
    if (first === '..') return null;

    // Find entry with this name
    const entry = currentEntries.find(e => e.name === first);
    if (!entry) return null;

    // If this is the last segment, return it
    if (rest.length === 0) return entry;

    // If it's a directory, recurse into it
    if (entry.isTree && entry.cid) {
      const tree = getTree();
      const subEntries = await tree.listDirectory(entry.cid);
      if (subEntries) {
        return resolveRelativePath(rest, subEntries);
      }
    }

    return null;
  }

  // Transform HTML content to use blob URLs for resources
  let transformedHtml = $state<string>('');
  let iframeSrc = $state<string>('');

  $effect(() => {
    let cancelled = false;

    async function transformContent() {
      const html = content;
      const currentEntries = entries;
      const tree = getTree();

      // Find all resource references (src, href attributes)
      const resourcePatterns = [
        /src="([^"]+)"/gi,
        /href="([^"]+\.(?:css|js|ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))"/gi,
      ];

      // Collect all URLs to replace
      const replacements = new Map<string, string>();

      for (const pattern of resourcePatterns) {
        let match;
        const regex = new RegExp(pattern.source, pattern.flags);
        while ((match = regex.exec(html)) !== null) {
          const url = match[1];

          // Skip external URLs and data URLs
          if (url.startsWith('http://') || url.startsWith('https://') ||
              url.startsWith('data:') || url.startsWith('//') ||
              url.startsWith('#')) {
            continue;
          }

          if (!replacements.has(url)) {
            // Parse the relative path
            const pathParts = url.split('/').filter(p => p && p !== '.');

            // Resolve to an entry
            const entry = await resolveRelativePath(pathParts, currentEntries);

            if (entry && entry.cid && !entry.isTree) {
              // Read the file content
              const data = await tree.readFile(entry.cid);
              if (data && !cancelled) {
                // Create blob URL
                const mimeType = getMimeType(entry.name);
                const blob = new Blob([data], { type: mimeType });
                const blobUrl = URL.createObjectURL(blob);
                replacements.set(url, blobUrl);
              }
            }
          }
        }
      }

      if (cancelled) return;

      // Replace all URLs in HTML
      let result = html;
      for (const [originalUrl, blobUrl] of replacements) {
        // Escape special regex characters in URL
        const escaped = originalUrl.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        result = result.replace(new RegExp(`(src|href)="${escaped}"`, 'gi'), `$1="${blobUrl}"`);
      }

      transformedHtml = result;

      // Create blob for the entire HTML
      const htmlBlob = new Blob([result], { type: 'text/html' });
      const newSrc = URL.createObjectURL(htmlBlob);

      // Clean up old blob URL
      if (iframeSrc) {
        URL.revokeObjectURL(iframeSrc);
      }

      iframeSrc = newSrc;
    }

    transformContent();

    return () => {
      cancelled = true;
      if (iframeSrc) {
        URL.revokeObjectURL(iframeSrc);
      }
    };
  });

  function getMimeType(filename: string): string {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    const mimeTypes: Record<string, string> = {
      'css': 'text/css',
      'js': 'text/javascript',
      'json': 'application/json',
      'html': 'text/html',
      'htm': 'text/html',
      'png': 'image/png',
      'jpg': 'image/jpeg',
      'jpeg': 'image/jpeg',
      'gif': 'image/gif',
      'svg': 'image/svg+xml',
      'ico': 'image/x-icon',
      'woff': 'font/woff',
      'woff2': 'font/woff2',
      'ttf': 'font/ttf',
      'eot': 'application/vnd.ms-fontobject',
      'mp3': 'audio/mpeg',
      'mp4': 'video/mp4',
      'webm': 'video/webm',
    };
    return mimeTypes[ext] || 'application/octet-stream';
  }
</script>

<div class="flex-1 flex flex-col min-h-0">
  {#if iframeSrc}
    <iframe
      src={iframeSrc}
      class="flex-1 w-full border-0 bg-white"
      sandbox="allow-scripts"
      title={fileName}
    ></iframe>
  {:else}
    <div class="flex-1 flex items-center justify-center text-muted">
      Loading...
    </div>
  {/if}
</div>
