// packages/hashtree-web/src/components/viewer/Viewer.tsx
/**
 * Viewer - main file viewer component
 */
import { useMemo, useState, useEffect, useRef, useCallback } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { toHex, nhashEncode } from 'hashtree';
import type { CID } from 'hashtree';
import { Avatar } from '../user';
import { npubToPubkey } from '../../nostr';
import { LiveVideo, LiveVideoFromHash } from '../LiveVideo';
import { DosBoxViewer, isDosExecutable } from '../DosBox';
import { HtmlViewer } from '../HtmlViewer';
import { decodeAsText, getTree } from '../../store';
import { saveFile, deleteEntry } from '../../actions';
import { openRenameModal, openShareModal, openUnsavedChangesModal } from '../../hooks/useModals';
import { useNostrStore } from '../../nostr';
import { useSettingsStore } from '../../stores/settings';
import { useRoute, useCurrentDirCid, useDirectoryEntries, useTreeRoot, useTrees, usePathType } from '../../hooks';
import { VisibilityIcon, LinkLockIcon } from '../VisibilityIcon';
import { getResolverKey } from '../../refResolver';
import { useRecentlyChanged } from '../../hooks/useRecentlyChanged';
import { useDelayedLoading } from '../../hooks/useDelayedLoading';
import { ContentView } from './ContentView';
import { DirectoryActions } from './DirectoryActions';
import { getMimeType, getFileIcon, isLikelyTextFile, useDebounce } from './utils';
import { NavButton } from '../NavButton';

/** Save button with stable width */
function SaveButton({ saved, onClick }: { saved: boolean; onClick: () => void }) {
  return (
    <button onClick={onClick} className="btn-success relative">
      <span className="invisible flex items-center gap-1">
        <span className="i-lucide-check" />
        Saved
      </span>
      <span className="absolute inset-0 flex items-center justify-center gap-1">
        {saved ? <><span className="i-lucide-check" />Saved</> : 'Save'}
      </span>
    </button>
  );
}

export function Viewer() {
  const navigate = useNavigate();
  const location = useLocation();
  const rootCid = useTreeRoot();
  const currentDirCid = useCurrentDirCid();
  const { entries } = useDirectoryEntries(currentDirCid);

  const route = useRoute();
  const viewedNpub = route.npub;
  const currentTreeName = route.treeName;
  const userNpub = useNostrStore(s => s.npub);
  const isLoggedIn = useNostrStore(s => s.isLoggedIn);

  // Get current tree for visibility info
  const targetNpub = viewedNpub || userNpub;
  const trees = useTrees(targetNpub);
  const currentTree = currentTreeName ? trees.find(t => t.name === currentTreeName) : null;

  // Get filename from URL path - uses hashtree to determine if last segment is file or directory
  const { dirPath, fileName: urlFileName } = usePathType();
  const currentPath = dirPath;

  // Find entry in current entries list (for metadata like hash)
  const entryFromStore = useMemo(() => {
    if (!urlFileName) return null;
    return entries.find(e => e.name === urlFileName && !e.isTree) || null;
  }, [urlFileName, entries]);

  // Get files only (no directories) for prev/next navigation
  const filesOnly = useMemo(() => entries.filter(e => !e.isTree), [entries]);
  const currentFileIndex = useMemo(() => {
    if (!urlFileName) return -1;
    return filesOnly.findIndex(e => e.name === urlFileName);
  }, [filesOnly, urlFileName]);
  // Wrap around at start/end
  const prevFile = filesOnly.length > 1 && currentFileIndex >= 0
    ? filesOnly[(currentFileIndex - 1 + filesOnly.length) % filesOnly.length]
    : null;
  const nextFile = filesOnly.length > 1 && currentFileIndex >= 0
    ? filesOnly[(currentFileIndex + 1) % filesOnly.length]
    : null;

  // Navigate to a file in the same directory
  const navigateToFile = useCallback((fileName: string) => {
    const parts: string[] = [];
    if (viewedNpub && currentTreeName) {
      parts.push(viewedNpub, currentTreeName, ...currentPath, fileName);
    }
    navigate('/' + parts.map(encodeURIComponent).join('/') + location.search);
  }, [viewedNpub, currentTreeName, currentPath, navigate, location.search]);

  // File state - content loaded from cid
  const [content, setContent] = useState<Uint8Array | null>(null);
  const [loading, setLoading] = useState(false);
  const [loadProgress, setLoadProgress] = useState(0); // 0-100
  const showLoading = useDelayedLoading(loading);
  const [, setFileCid] = useState<CID | null>(null);
  const [resolvedEntry, setResolvedEntry] = useState<{ name: string; cid: CID; size?: number } | null>(null);

  // Use store entry if available, otherwise use resolved entry
  const entry = entryFromStore || resolvedEntry;

  // Resolve file cid from path when store entry is not available
  useEffect(() => {
    if (entryFromStore) {
      setResolvedEntry(null);
      return;
    }

    // For permalinks without path, check if rootCid itself is a file
    if (route.isPermalink && !urlFileName && rootCid?.hash) {
      let cancelled = false;
      const tree = getTree();
      tree.isDirectory(rootCid).then(isDir => {
        if (!cancelled && !isDir) {
          // The rootCid is the file itself
          setResolvedEntry({ name: 'file', cid: rootCid });
        }
      });
      return () => { cancelled = true; };
    }

    if (!urlFileName || !rootCid) {
      setResolvedEntry(null);
      return;
    }

    let cancelled = false;
    const tree = getTree();

    // For permalinks with path, check if rootCid itself is a file (not a directory)
    // In that case, the path is just the filename for display purposes
    if (route.isPermalink && rootCid?.hash) {
      tree.isDirectory(rootCid).then(isDir => {
        if (!cancelled && !isDir) {
          // The rootCid is the file itself, use urlFileName for display
          setResolvedEntry({ name: urlFileName, cid: rootCid });
        } else if (!cancelled && isDir) {
          // It's a directory, resolve the path within it
          const fullPath = [...currentPath, urlFileName].join('/');
          tree.resolvePath(rootCid, fullPath).then(async result => {
            if (!cancelled && result?.cid?.hash) {
              const isFileDir = await tree.isDirectory(result.cid);
              if (!cancelled && !isFileDir) {
                setResolvedEntry({ name: urlFileName, cid: result.cid });
              }
            }
          });
        }
      });
    } else if (!route.isPermalink) {
      // Non-permalink: resolve path normally
      const fullPath = [...currentPath, urlFileName].join('/');
      tree.resolvePath(rootCid, fullPath).then(async result => {
        if (!cancelled && result?.cid?.hash) {
          const isDir = await tree.isDirectory(result.cid);
          if (!cancelled && !isDir) {
            setResolvedEntry({ name: urlFileName, cid: result.cid });
          }
        }
      });
    }

    return () => { cancelled = true; };
  }, [entryFromStore, urlFileName, rootCid?.hash ? toHex(rootCid.hash) : null, currentPath.join('/'), route.isPermalink]);

  // Parse query params from location.search (works with hash routing)
  const searchParams = useMemo(() => new URLSearchParams(location.search), [location.search]);

  // Edit mode is driven by URL query param
  const isEditing = searchParams.get('edit') === '1';
  const isFullscreen = searchParams.get('fullscreen') === '1';
  const [editContent, setEditContent] = useState('');
  const [savedContent, setSavedContent] = useState(''); // Content as of last save (for detecting unsaved changes)
  const autoSave = useSettingsStore((s) => s.editor.autoSave);
  const setAutoSave = useSettingsStore((s) => s.setEditorSettings);
  const [saved, setSaved] = useState(false);

  // Helper to update URL query params
  const setUrlParam = useCallback((param: string, value: boolean) => {
    const hash = window.location.hash.split('?')[0];
    const params = new URLSearchParams(window.location.hash.split('?')[1] || '');
    if (value) {
      params.set(param, '1');
    } else {
      params.delete(param);
    }
    const queryString = params.toString();
    window.location.hash = queryString ? `${hash}?${queryString}` : hash;
  }, []);

  const setIsEditing = useCallback((editing: boolean) => setUrlParam('edit', editing), [setUrlParam]);
  const setIsFullscreen = useCallback((fullscreen: boolean) => setUrlParam('fullscreen', fullscreen), [setUrlParam]);

  const mimeType = urlFileName ? getMimeType(urlFileName) : null;
  const isVideo = mimeType?.startsWith('video/');
  const isImage = mimeType?.startsWith('image/');
  const isHtml = mimeType === 'text/html';
  const isDosExe = urlFileName ? isDosExecutable(urlFileName) : false;
  const canEdit = !viewedNpub || viewedNpub === userNpub || !isLoggedIn;

  // Debug: log DOS exe detection
  if (isDosExe) {
    console.log('[Viewer] DOS exe detected:', urlFileName, { isDosExe, entry: !!entry, currentDirCid: !!currentDirCid });
  }

  // Check if currently viewed file was recently changed
  const recentlyChangedFiles = useRecentlyChanged();
  const isRecentlyChanged = urlFileName && !isEditing && recentlyChangedFiles.has(urlFileName);

  // Stable key for video - only changes when file path changes, not on hash updates
  const videoKeyRef = useRef<string | null>(null);
  const currentFilePath = urlFileName ? `${currentPath.join('/')}/${urlFileName}` : null;
  if (currentFilePath !== videoKeyRef.current) {
    videoKeyRef.current = currentFilePath;
  }

  // Load file content when entry is found (skip for video - it streams)
  useEffect(() => {
    // Reset edit content when file changes
    setEditContent('');

    // Clear content immediately when selection changes
    setContent(null);
    setFileCid(null);
    setLoading(false);
    setLoadProgress(0);

    if (!entry || isVideo || isDosExe) {
      return;
    }

    let cancelled = false;
    setLoading(true);
    setFileCid(entry.cid);

    // Use streaming to track progress
    const totalSize = entry.size || 0;
    const chunks: Uint8Array[] = [];
    let bytesLoaded = 0;

    (async () => {
      try {
        for await (const chunk of getTree().readFileStream(entry.cid)) {
          if (cancelled) return;
          chunks.push(chunk);
          bytesLoaded += chunk.length;
          if (totalSize > 0) {
            setLoadProgress(Math.min(100, Math.round((bytesLoaded / totalSize) * 100)));
          }
        }
        if (!cancelled) {
          // Combine chunks
          const totalLength = chunks.reduce((sum, c) => sum + c.length, 0);
          const result = new Uint8Array(totalLength);
          let offset = 0;
          for (const chunk of chunks) {
            result.set(chunk, offset);
            offset += chunk.length;
          }
          setContent(result);
          setLoading(false);
        }
      } catch {
        if (!cancelled) {
          setLoading(false);
        }
      }
    })();

    return () => { cancelled = true; };
  }, [entry?.cid?.hash ? toHex(entry.cid.hash) : null, isVideo]);

  // Initialize editContent when entering edit mode
  useEffect(() => {
    if (isEditing && content) {
      const text = decodeAsText(content);
      if (text !== null) {
        setEditContent(text);
        setSavedContent(text); // Track original content for unsaved changes detection
      }
    }
  }, [isEditing, content]);

  // Silent save for autosave - doesn't update content state to avoid re-render
  const silentSave = useCallback(async () => {
    if (isEditing && entry?.name) {
      await saveFile(entry.name, editContent);
    }
  }, [entry?.name, isEditing, editContent]);

  // Debounced autosave (1 second after typing stops)
  const debouncedSave = useDebounce(silentSave, 1000);

  const isText = content ? decodeAsText(content) !== null : false;

  const handleEdit = () => {
    if (!content) return;
    if (decodeAsText(content) !== null) {
      setIsEditing(true);
    }
  };

  const handleDownload = async () => {
    if (!entry) return;

    let data = content;
    // For video files, content isn't preloaded - fetch it now
    if (!data && isVideo) {
      data = await getTree().readFile(entry.cid);
    }
    if (!data) return;

    const blob = new Blob([new Uint8Array(data)], { type: mimeType || 'application/octet-stream' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = entry.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSave = async () => {
    const newData = await saveFile(entry?.name, editContent);
    if (newData) {
      setContent(newData);
      setSavedContent(editContent); // Update saved content tracker
      setSaved(true);
      setTimeout(() => setSaved(false), 2000);
    }
  };

  // Check if there are unsaved changes
  const hasUnsavedChanges = isEditing && editContent !== savedContent;

  // Handle closing the editor - checks for unsaved changes
  const handleCloseEditor = useCallback(async () => {
    if (hasUnsavedChanges) {
      // If autosave is enabled, just save and close immediately
      if (autoSave) {
        await handleSave();
        setIsEditing(false);
      } else {
        // Show modal to ask user what to do
        openUnsavedChangesModal({
          fileName: entry?.name,
          onSave: async () => {
            await handleSave();
            setIsEditing(false);
          },
          onDiscard: () => {
            setIsEditing(false);
          },
        });
      }
    } else {
      setIsEditing(false);
    }
  }, [hasUnsavedChanges, autoSave, entry?.name, setIsEditing]);

  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setEditContent(e.target.value);
    if (autoSave) {
      debouncedSave();
    }
  };

  const handleShare = useCallback(() => {
    // Strip ?edit=1 or &edit=1 from hash when sharing
    let url = window.location.href;
    url = url.replace(/[?&]edit=1/, '');
    openShareModal(url);
  }, []);

  // Keyboard navigation (when not editing)
  useEffect(() => {
    if (!entry && !urlFileName) return; // Only when viewing a file
    if (isEditing) return; // Don't navigate when editing

    const handleKeyDown = (e: KeyboardEvent) => {
      // Don't interfere with browser shortcuts (Cmd/Ctrl + arrows for back/forward)
      if (e.metaKey || e.ctrlKey) return;

      const key = e.key.toLowerCase();

      // Escape or h: back to directory
      if (key === 'escape' || key === 'h') {
        e.preventDefault();
        (document.activeElement as HTMLElement)?.blur();
        const parts: string[] = [];
        if (viewedNpub && currentTreeName) {
          parts.push(viewedNpub, currentTreeName, ...currentPath);
        }
        navigate('/' + parts.map(encodeURIComponent).join('/') + location.search);
        return;
      }

      // j/k/ArrowLeft/ArrowRight: prev/next file
      if ((key === 'j' || key === 'arrowright') && nextFile) {
        e.preventDefault();
        navigateToFile(nextFile.name);
        return;
      }
      if ((key === 'k' || key === 'arrowleft') && prevFile) {
        e.preventDefault();
        navigateToFile(prevFile.name);
        return;
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [entry, urlFileName, isEditing, viewedNpub, currentTreeName, currentPath, navigate, location.search, prevFile, nextFile, navigateToFile]);

  // Escape key handler for edit mode
  useEffect(() => {
    if (!isEditing) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        (document.activeElement as HTMLElement)?.blur();
        handleCloseEditor();
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [isEditing, handleCloseEditor]);

  return (
    <div className="flex-1 flex flex-col min-h-0 bg-surface-0">
      {/* Header - only show when file selected and not fullscreen */}
      {(entry || urlFileName) && !isFullscreen && (
        <div className="shrink-0 px-3 py-2 border-b border-surface-3 flex flex-wrap items-center gap-2 bg-surface-1">
          <span className="font-medium flex items-center gap-2 shrink-0">
            {(entry || urlFileName) && (
              <NavButton
                onClick={() => {
                  // Navigate to directory (remove file from URL), preserve query params like ?k=
                  const parts: string[] = [];
                  if (viewedNpub && currentTreeName) {
                    parts.push(viewedNpub, currentTreeName, ...currentPath);
                  }
                  navigate('/' + parts.map(encodeURIComponent).join('/') + location.search);
                }}
                className="lg:hidden"
              />
            )}
          {/* Show avatar (for npub routes) or hash icon (for nhash routes) */}
          {viewedNpub ? (
            <Link to={`/${viewedNpub}/profile`} className="shrink-0">
              <Avatar pubkey={npubToPubkey(viewedNpub) || viewedNpub} size={20} />
            </Link>
          ) : route.isPermalink && (
            rootCid?.key ? (
              <LinkLockIcon className="text-text-2" title="Encrypted permalink" />
            ) : (
              <span className="i-lucide-globe text-text-2 shrink-0" title="Public permalink" />
            )
          )}
          {/* Visibility icon */}
          {currentTree && (
            <VisibilityIcon visibility={currentTree.visibility} className="text-text-2" />
          )}
          {/* File type icon */}
          <span className={`${getFileIcon(entry?.name || urlFileName || '')} text-text-2 shrink-0`} />
          {entry?.name || urlFileName || ''}
          {isRecentlyChanged && (
            <span className="ml-2 px-1.5 py-0.5 text-xs font-bold bg-red-600 text-white rounded animate-pulse">
              LIVE
            </span>
          )}
        </span>

        {entry && !isEditing && (
          <div className="flex flex-wrap items-center gap-2 ml-auto">
            <button
              onClick={handleDownload}
              className="btn-ghost"
              title="Download file"
              disabled={loading && !isVideo}
            >
              Download
            </button>
            {/* Permalink to this specific file's hash (includes key if encrypted) */}
            {entry.cid?.hash && (
              <Link
                to={`/${nhashEncode({ hash: toHex(entry.cid.hash), decryptKey: entry.cid.key ? toHex(entry.cid.key) : undefined })}/${encodeURIComponent(entry.name)}`}
                className="btn-ghost no-underline"
                title={toHex(entry.cid.hash)}
              >
                Permalink
              </Link>
            )}
            <button
              onClick={() => setIsFullscreen(true)}
              className="btn-ghost"
              title="Fullscreen"
            >
              <span className="i-lucide-maximize text-base" />
            </button>
            <button
              onClick={handleShare}
              className="btn-ghost"
              title="Share"
            >
              <span className="i-lucide-share text-base" />
            </button>
            {canEdit && (
              <>
                <button onClick={() => openRenameModal(entry?.name)} className="btn-ghost">Rename</button>
                {isLikelyTextFile(entry.name) && (
                  <button
                    onClick={handleEdit}
                    className="btn-ghost"
                    disabled={loading || !content || !isText}
                  >
                    Edit
                  </button>
                )}
                <button
                  onClick={() => {
                    if (confirm(`Delete ${entry.name}?`)) {
                      deleteEntry(entry.name);
                      // Navigate back to directory, preserve query params like ?k=
                      const parts: string[] = [];
                      if (viewedNpub && currentTreeName) {
                        parts.push(viewedNpub, currentTreeName, ...currentPath);
                      }
                      navigate('/' + parts.map(encodeURIComponent).join('/') + location.search);
                    }
                  }}
                  className="btn-ghost text-danger"
                >
                  Delete
                </button>
              </>
            )}
            {/* Prev/Next file navigation - mobile only, wraps around */}
            {filesOnly.length > 1 && prevFile && nextFile && (
              <>
                <button
                  onClick={() => navigateToFile(prevFile.name)}
                  className="btn-ghost lg:hidden"
                  title={`Previous: ${prevFile.name}`}
                >
                  <span className="i-lucide-chevron-left text-base" />
                </button>
                <button
                  onClick={() => navigateToFile(nextFile.name)}
                  className="btn-ghost lg:hidden"
                  title={`Next: ${nextFile.name}`}
                >
                  <span className="i-lucide-chevron-right text-base" />
                </button>
              </>
            )}
          </div>
        )}

        {isEditing && (
          <div className="flex flex-wrap items-center gap-2 ml-auto">
            <label className="flex items-center gap-1 text-xs text-text-2 cursor-pointer">
              <input
                type="checkbox"
                checked={autoSave}
                onChange={(e) => { setAutoSave({ autoSave: e.target.checked }); }}
                className="cursor-pointer"
              />
              Autosave
            </label>
            <SaveButton saved={saved} onClick={handleSave} />
            <button onClick={handleCloseEditor} className="btn-ghost">
              Done
            </button>
            <button onClick={handleShare} className="btn-ghost" title="Share">
              <span className="i-lucide-share text-base" />
            </button>
          </div>
        )}
        </div>
      )}

      {/* Content */}
      <div className={`flex-1 ${isEditing ? 'overflow-hidden p-4' : `overflow-auto ${isVideo || isImage || isHtml || isDosExe ? '' : 'p-4'}`}`}>
        {/* Show textarea immediately if in edit mode with a filename (even before entry loads) */}
        {isEditing && urlFileName ? (
          <textarea
            value={editContent}
            onChange={handleInput}
            autoFocus={editContent === ''}
            className="w-full h-full input font-mono text-sm resize-none"
          />
        ) : isVideo && mimeType && urlFileName ? (
          // Video: render immediately based on filename, don't wait for entry to load
          // This prevents remounting when merkle root changes during livestream
          viewedNpub && currentTreeName ? (
            // Use resolver subscription for live updates
            <LiveVideo
              key={videoKeyRef.current}
              resolverKey={getResolverKey(viewedNpub, currentTreeName)}
              filePath={[...currentPath, urlFileName]}
              mimeType={mimeType}
              initialCid={rootCid}
            />
          ) : entry ? (
            // Direct hash access (no resolver) - need entry for CID
            <LiveVideoFromHash cid={entry.cid} mimeType={mimeType} />
          ) : null
        ) : !entry ? (
          <DirectoryActions />
        ) : loading ? (
          showLoading ? (
            <div className="w-full h-full flex flex-col items-center justify-center text-muted gap-2">
              <div className="w-48 h-2 bg-surface-2 rounded-full overflow-hidden">
                <div
                  className="h-full bg-accent transition-all duration-150"
                  style={{ width: `${loadProgress}%` }}
                />
              </div>
              <span className="text-sm">{loadProgress}%</span>
            </div>
          ) : null
        ) : isDosExe && currentDirCid && entry?.cid?.hash ? (
          // DOS executable - show DOSBox viewer
          // Key on CID hash to prevent remounting when layout changes (fullscreen toggle)
          <DosBoxViewer
            key={toHex(entry.cid.hash)}
            exeCid={entry.cid}
            directoryCid={currentDirCid}
            exeName={entry.name}
          />
        ) : isHtml && content && currentDirCid && entry?.cid?.hash ? (
          // HTML file with directory context - can load sibling resources
          <HtmlViewer
            key={toHex(entry.cid.hash)}
            html={decodeAsText(content) || ''}
            directoryCid={currentDirCid}
            filename={entry.name}
          />
        ) : content ? (
          <ContentView data={content} filename={entry.name} onDownload={handleDownload} />
        ) : null}
      </div>
    </div>
  );
}

// packages/hashtree-web/src/components/Viewer/Viewer.svelte
<script lang="ts">
  /**
   * Viewer - main file viewer component
   * Port of React Viewer component
   */
  import { toHex, nhashEncode } from 'hashtree';
  import { routeStore, treeRootStore, currentDirCidStore, directoryEntriesStore, currentHash, createTreesStore, addRecent, recentlyChangedFiles } from '../../stores';
  import { looksLikeFile } from '../../utils/route';
  import { getTree, decodeAsText, formatBytes } from '../../store';
  import { nostrStore, npubToPubkey } from '../../nostr';
  import { deleteEntry } from '../../actions';
  import { openRenameModal, openShareModal } from '../../stores/modals';
  import DirectoryActions from './DirectoryActions.svelte';
  import FileEditor from './FileEditor.svelte';
  import HtmlViewer from './HtmlViewer.svelte';
  import VideoViewer from './VideoViewer.svelte';
  import YjsDocumentEditor from './YjsDocumentEditor.svelte';
  import ZipPreview from './ZipPreview.svelte';
  import DosBox from './DosBox.svelte';
  import { Avatar } from '../User';
  import VisibilityIcon from '../VisibilityIcon.svelte';

  let route = $derived($routeStore);
  let rootCid = $derived($treeRootStore);
  let currentDirCid = $derived($currentDirCidStore);
  let dirEntries = $derived($directoryEntriesStore);
  let entries = $derived(dirEntries.entries);
  let hash = $derived($currentHash);

  // Check if user can edit (owns the tree or is not viewing another user's tree)
  let userNpub = $derived($nostrStore.npub);
  let isLoggedIn = $derived($nostrStore.isLoggedIn);
  let viewedNpub = $derived(route.npub);
  let canEdit = $derived(!viewedNpub || viewedNpub === userNpub || !isLoggedIn);

  // Get current tree for visibility info
  let targetNpub = $derived(viewedNpub || userNpub);
  let treesStore = $derived(createTreesStore(targetNpub));
  let trees = $derived($treesStore);
  let currentTreeName = $derived(route.treeName);
  let currentTree = $derived(currentTreeName ? trees.find(t => t.name === currentTreeName) : null);

  // Get filename from URL path - uses path type heuristic
  let urlPath = $derived(route.path);
  let lastSegment = $derived(urlPath.length > 0 ? urlPath[urlPath.length - 1] : null);
  // Don't treat .yjs files as viewable files - they are internal to Yjs documents
  let hasFile = $derived(lastSegment && looksLikeFile(lastSegment) && !lastSegment.endsWith('.yjs'));
  let urlFileName = $derived(hasFile ? lastSegment : null);

  // Parse query params from URL hash - use currentHash store for reactivity
  let searchParams = $derived.by(() => {
    const qIdx = hash.indexOf('?');
    if (qIdx === -1) return new URLSearchParams();
    return new URLSearchParams(hash.slice(qIdx + 1));
  });

  let isEditing = $derived(searchParams.get('edit') === '1');

  // Find entry in current entries list, or create synthetic entry for file permalinks
  let entryFromStore = $derived.by(() => {
    if (!urlFileName) return null;

    // First try to find the file in entries (works for files within directories)
    const fromEntries = entries.find(e => e.name === urlFileName && !e.isTree);
    if (fromEntries) return fromEntries;

    // For direct file permalinks (no directory listing), the rootCid IS the file's CID
    // Create a synthetic entry since there's no directory listing
    if (route.isPermalink && rootCid && entries.length === 0) {
      return {
        name: urlFileName,
        cid: rootCid,
        size: 0,
        isTree: false,
      };
    }

    return null;
  });

  // Get files only (no directories) for prev/next navigation
  let filesOnly = $derived(entries.filter(e => !e.isTree));
  let currentFileIndex = $derived(urlFileName ? filesOnly.findIndex(e => e.name === urlFileName) : -1);
  // Wrap around at start/end
  let prevFile = $derived(
    filesOnly.length > 1 && currentFileIndex >= 0
      ? filesOnly[(currentFileIndex - 1 + filesOnly.length) % filesOnly.length]
      : null
  );
  let nextFile = $derived(
    filesOnly.length > 1 && currentFileIndex >= 0
      ? filesOnly[(currentFileIndex + 1) % filesOnly.length]
      : null
  );

  // Navigate to a file in the same directory
  function navigateToFile(fileName: string) {
    const dirPath = route.path.slice(0, -1); // Remove current filename
    const parts: string[] = [];
    if (route.npub && route.treeName) {
      parts.push(route.npub, route.treeName, ...dirPath, fileName);
    }
    const linkKeySuffix = route.linkKey ? `?k=${route.linkKey}` : '';
    window.location.hash = '/' + parts.map(encodeURIComponent).join('/') + linkKeySuffix;
  }

  // Check if we have a tree context (for showing actions)
  let hasTreeContext = $derived(!!rootCid || !!route.treeName);

  // Check if current directory is a Yjs document (contains .yjs file)
  let isYjsDocument = $derived(entries.some(e => e.name === '.yjs' && !e.isTree));

  // Get current directory name from path
  let currentDirName = $derived.by(() => {
    const pathSegments = route.path;
    return pathSegments.length > 0 ? pathSegments[pathSegments.length - 1] : route.treeName || 'Document';
  });

  // File content state - raw binary data
  let fileData = $state<Uint8Array | null>(null);
  // Decoded text content (null if binary)
  let fileContent = $state<string | null>(null);
  let loading = $state(false);
  // Only show loading indicator after 2 seconds (avoid flash for fast loads)
  let showLoading = $state(false);
  let loadingTimer: ReturnType<typeof setTimeout> | null = null;
  // Blob URL for binary content (images, etc)
  let blobUrl = $state<string | null>(null);
  // Track current blob URL outside of reactive system for cleanup
  let currentBlobUrl: string | null = null;
  // Fullscreen mode
  let isFullscreen = $state(false);

  // MIME type detection
  function getMimeType(filename?: string): string | null {
    if (!filename) return null;
    const ext = filename.split('.').pop()?.toLowerCase();
    const mimeTypes: Record<string, string> = {
      // Images
      png: 'image/png',
      jpg: 'image/jpeg',
      jpeg: 'image/jpeg',
      gif: 'image/gif',
      webp: 'image/webp',
      avif: 'image/avif',
      svg: 'image/svg+xml',
      ico: 'image/x-icon',
      bmp: 'image/bmp',
      // PDF
      pdf: 'application/pdf',
      // Audio
      mp3: 'audio/mpeg',
      wav: 'audio/wav',
      flac: 'audio/flac',
      m4a: 'audio/mp4',
      ogg: 'audio/ogg',
    };
    return ext ? mimeTypes[ext] || null : null;
  }

  // Helper to clean up blob URL
  function cleanupBlobUrl() {
    if (currentBlobUrl) {
      URL.revokeObjectURL(currentBlobUrl);
      currentBlobUrl = null;
    }
  }

  // Load file content when entry changes
  $effect(() => {
    // Clean up previous blob URL (use non-reactive variable)
    cleanupBlobUrl();

    // Clear loading timer
    if (loadingTimer) {
      clearTimeout(loadingTimer);
      loadingTimer = null;
    }

    fileData = null;
    fileContent = null;
    blobUrl = null;
    loading = false;
    showLoading = false;

    const entry = entryFromStore;
    if (!entry) return;

    // Skip loading for video files - they stream separately
    // Skip loading for DOS executables - they use their own loader
    if (isVideo || isDos) return;

    loading = true;
    let cancelled = false;

    // Show loading indicator only after 2 seconds delay
    loadingTimer = setTimeout(() => {
      if (!cancelled && loading) {
        showLoading = true;
      }
    }, 2000);

    getTree().readFile(entry.cid).then(data => {
      if (!cancelled && data) {
        fileData = data;
        // Try to decode as text
        const text = decodeAsText(data);
        fileContent = text;

        // If not text, create blob URL for binary viewing
        if (text === null && urlFileName) {
          const mimeType = getMimeType(urlFileName);
          if (mimeType) {
            const blob = new Blob([data], { type: mimeType });
            const newUrl = URL.createObjectURL(blob);
            currentBlobUrl = newUrl;
            blobUrl = newUrl;
          }
        }
      }
      loading = false;
      showLoading = false;
      if (loadingTimer) {
        clearTimeout(loadingTimer);
        loadingTimer = null;
      }
    }).catch(() => {
      loading = false;
      showLoading = false;
      if (loadingTimer) {
        clearTimeout(loadingTimer);
        loadingTimer = null;
      }
    });

    return () => {
      cancelled = true;
      cleanupBlobUrl();
      if (loadingTimer) {
        clearTimeout(loadingTimer);
        loadingTimer = null;
      }
    };
  });

  // Track file visits in recents
  $effect(() => {
    if (!urlFileName || !route.npub || !route.treeName) return;

    // Build full path for the file
    const pathParts = route.path.join('/');
    const fullPath = `/${route.npub}/${route.treeName}${pathParts ? '/' + pathParts : ''}`;

    addRecent({
      type: 'file',
      label: urlFileName,
      path: fullPath,
      npub: route.npub,
      treeName: route.treeName,
    });
  });

  function exitEditMode() {
    // Remove ?edit=1 from URL
    const hashBase = window.location.hash.split('?')[0];
    const params = new URLSearchParams(window.location.hash.split('?')[1] || '');
    params.delete('edit');
    const queryString = params.toString();
    window.location.hash = queryString ? `${hashBase}?${queryString}` : hashBase;
  }

  function enterEditMode() {
    // Add ?edit=1 to URL
    const hashBase = window.location.hash.split('?')[0];
    const params = new URLSearchParams(window.location.hash.split('?')[1] || '');
    params.set('edit', '1');
    window.location.hash = `${hashBase}?${params.toString()}`;
  }

  function handleDelete() {
    if (!entryFromStore) return;
    if (confirm(`Delete ${entryFromStore.name}?`)) {
      deleteEntry(entryFromStore.name);
      // Navigate back to directory
      const dirPath = route.path.slice(0, -1);
      const parts: string[] = [];
      if (route.npub && route.treeName) {
        parts.push(route.npub, route.treeName, ...dirPath);
      }
      const linkKeySuffix = route.linkKey ? `?k=${route.linkKey}` : '';
      window.location.hash = '#/' + parts.map(encodeURIComponent).join('/') + linkKeySuffix;
    }
  }

  // Keyboard navigation for file viewing
  $effect(() => {
    if (!entryFromStore && !urlFileName) return; // Only when viewing a file
    if (isEditing) return; // Don't navigate when editing

    const handleKeyDown = (e: KeyboardEvent) => {
      // Don't interfere with browser shortcuts (Cmd/Ctrl + arrows)
      if (e.metaKey || e.ctrlKey) return;
      // Don't interfere when focus is in input/textarea
      const target = e.target as HTMLElement;
      if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.isContentEditable) return;

      const key = e.key.toLowerCase();

      // Escape: back to directory
      if (key === 'escape') {
        e.preventDefault();
        (document.activeElement as HTMLElement)?.blur();
        window.location.hash = backUrl.slice(1); // Remove leading #
        return;
      }

      // j/k/ArrowDown/ArrowUp: next/prev file (vertical navigation)
      // l/ArrowRight: next file (horizontal navigation)
      if ((key === 'j' || key === 'arrowdown' || key === 'l' || key === 'arrowright') && nextFile) {
        e.preventDefault();
        navigateToFile(nextFile.name);
        return;
      }

      // k/ArrowUp/h/ArrowLeft: prev file
      if ((key === 'k' || key === 'arrowup' || key === 'h' || key === 'arrowleft') && prevFile) {
        e.preventDefault();
        navigateToFile(prevFile.name);
        return;
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  });

  // Check if file looks like text based on extension
  function isLikelyTextFile(filename: string): boolean {
    const textExtensions = ['txt', 'md', 'json', 'js', 'ts', 'jsx', 'tsx', 'css', 'scss', 'html', 'xml', 'yaml', 'yml', 'toml', 'ini', 'cfg', 'conf', 'sh', 'bash', 'py', 'rb', 'go', 'rs', 'c', 'cpp', 'h', 'hpp', 'java', 'php', 'sql', 'svelte', 'vue'];
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return textExtensions.includes(ext);
  }

  let isTextFile = $derived(urlFileName ? isLikelyTextFile(urlFileName) : false);

  // Check if file is HTML (should be rendered in iframe)
  function isHtmlFile(filename: string): boolean {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return ext === 'html' || ext === 'htm';
  }

  let isHtml = $derived(urlFileName ? isHtmlFile(urlFileName) : false);

  // Check if file is a video
  function isVideoFile(filename: string): boolean {
    const videoExtensions = ['mp4', 'webm', 'ogg', 'ogv', 'mov', 'avi', 'mkv'];
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return videoExtensions.includes(ext);
  }

  let isVideo = $derived(urlFileName ? isVideoFile(urlFileName) : false);

  // Check if file is an image
  function isImageFile(filename: string): boolean {
    const imageExtensions = ['png', 'jpg', 'jpeg', 'gif', 'webp', 'avif', 'svg', 'ico', 'bmp'];
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return imageExtensions.includes(ext);
  }

  let isImage = $derived(urlFileName ? isImageFile(urlFileName) : false);

  // Check if file is audio
  function isAudioFile(filename: string): boolean {
    const audioExtensions = ['mp3', 'wav', 'flac', 'm4a', 'ogg', 'aac'];
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return audioExtensions.includes(ext);
  }

  let isAudio = $derived(urlFileName ? isAudioFile(urlFileName) : false);

  // Check if file is PDF
  function isPdfFile(filename: string): boolean {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return ext === 'pdf';
  }

  let isPdf = $derived(urlFileName ? isPdfFile(urlFileName) : false);

  // Check if file is ZIP archive
  function isZipFile(filename: string): boolean {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return ext === 'zip';
  }

  let isZip = $derived(urlFileName ? isZipFile(urlFileName) : false);

  // Check if file is DOS executable
  function isDosExecutable(filename: string): boolean {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return ext === 'exe' || ext === 'com' || ext === 'bat';
  }

  let isDos = $derived(urlFileName ? isDosExecutable(urlFileName) : false);

  // Check if file was recently changed (for LIVE indicator)
  let changedFiles = $derived($recentlyChangedFiles);
  let isRecentlyChanged = $derived(urlFileName ? changedFiles.has(urlFileName) : false);

  // Build permalink URL for the current file
  let permalinkUrl = $derived.by(() => {
    if (!entryFromStore?.cid?.hash) return null;
    const hashHex = toHex(entryFromStore.cid.hash);
    const keyHex = entryFromStore.cid.key ? toHex(entryFromStore.cid.key) : undefined;
    const nhash = nhashEncode({ hash: hashHex, decryptKey: keyHex });
    return `#/${nhash}/${encodeURIComponent(entryFromStore.name)}`;
  });

  // Build back URL (directory without file)
  let backUrl = $derived.by(() => {
    const dirPath = route.path.slice(0, -1);
    const parts: string[] = [];
    if (route.npub && route.treeName) {
      parts.push(route.npub, route.treeName, ...dirPath);
    }
    const linkKeySuffix = route.linkKey ? `?k=${route.linkKey}` : '';
    return '#/' + parts.map(encodeURIComponent).join('/') + linkKeySuffix;
  });

  // Get file icon based on extension
  function getFileIcon(filename: string): string {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    const iconMap: Record<string, string> = {
      // Images
      png: 'i-lucide-image',
      jpg: 'i-lucide-image',
      jpeg: 'i-lucide-image',
      gif: 'i-lucide-image',
      webp: 'i-lucide-image',
      svg: 'i-lucide-image',
      // Video
      mp4: 'i-lucide-video',
      webm: 'i-lucide-video',
      mov: 'i-lucide-video',
      // Audio
      mp3: 'i-lucide-music',
      wav: 'i-lucide-music',
      flac: 'i-lucide-music',
      // Code
      js: 'i-lucide-file-code',
      ts: 'i-lucide-file-code',
      jsx: 'i-lucide-file-code',
      tsx: 'i-lucide-file-code',
      py: 'i-lucide-file-code',
      rs: 'i-lucide-file-code',
      go: 'i-lucide-file-code',
      // Documents
      md: 'i-lucide-file-text',
      txt: 'i-lucide-file-text',
      pdf: 'i-lucide-file-text',
      // Archive
      zip: 'i-lucide-archive',
      tar: 'i-lucide-archive',
      gz: 'i-lucide-archive',
    };
    return iconMap[ext] || 'i-lucide-file';
  }

  let fileIcon = $derived(urlFileName ? getFileIcon(urlFileName) : 'i-lucide-file');

  // Download handler
  async function handleDownload() {
    if (!entryFromStore) return;

    let data = fileData;
    // For video files, content isn't preloaded - fetch it now
    if (!data && isVideo) {
      data = await getTree().readFile(entryFromStore.cid);
    }
    if (!data) return;

    const mimeType = getMimeType(urlFileName || '') || 'application/octet-stream';
    const blob = new Blob([data], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = entryFromStore.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // Share handler
  function handleShare() {
    // Strip ?edit=1 from URL when sharing
    let url = window.location.href;
    url = url.replace(/[?&]edit=1/, '');
    openShareModal(url);
  }
</script>

{#if urlFileName && isEditing}
  <!-- Edit mode - show even if entry not found yet (newly created file) -->
  <FileEditor
    fileName={urlFileName}
    initialContent={fileContent || ''}
    onDone={exitEditMode}
  />
{:else if urlFileName && entryFromStore}
  <!-- File view - show content -->
  <div class="flex-1 flex flex-col min-h-0 bg-surface-0">
    <!-- Header -->
    <div class="shrink-0 px-3 py-2 border-b border-surface-3 flex flex-wrap items-center justify-between gap-2 bg-surface-1" data-testid="viewer-header">
      <div class="flex items-center gap-2 min-w-0">
        <a href={backUrl} class="btn-ghost p-1 no-underline" title="Back to folder" data-testid="viewer-back">
          <span class="i-lucide-chevron-left text-lg"></span>
        </a>
        <!-- Avatar (for npub routes) or LinkLock/globe (for nhash routes) -->
        {#if viewedNpub}
          <a href="#/{viewedNpub}/profile" class="shrink-0">
            <Avatar pubkey={npubToPubkey(viewedNpub) || ''} size={20} />
          </a>
        {:else if route.isPermalink}
          {#if rootCid?.key}
            <!-- LinkLockIcon for encrypted permalink -->
            <span class="relative inline-block shrink-0 text-text-2" title="Encrypted permalink">
              <span class="i-lucide-link"></span>
              <span class="i-lucide-lock absolute -bottom-0.5 -right-1.5 text-[0.6em]"></span>
            </span>
          {:else}
            <span class="i-lucide-globe text-text-2 shrink-0" title="Public permalink"></span>
          {/if}
        {/if}
        <!-- Visibility icon (for trees) -->
        {#if currentTree}
          <VisibilityIcon visibility={currentTree.visibility} class="text-text-2" />
        {/if}
        <!-- File type icon -->
        <span class="{fileIcon} text-text-2 shrink-0"></span>
        <span class="font-medium text-text-1 truncate">{entryFromStore.name}</span>
        {#if isRecentlyChanged}
          <span class="ml-2 px-1.5 py-0.5 text-xs font-bold bg-red-600 text-white rounded animate-pulse">LIVE</span>
        {/if}
      </div>
      <div class="flex items-center gap-1 flex-wrap">
        <button onclick={handleDownload} class="btn-ghost" title="Download file" data-testid="viewer-download" disabled={loading && !isVideo}>
          Download
        </button>
        {#if permalinkUrl}
          <a href={permalinkUrl} class="btn-ghost no-underline" title={entryFromStore?.cid?.hash ? toHex(entryFromStore.cid.hash) : ''} data-testid="viewer-permalink">
            Permalink
          </a>
        {/if}
        <button onclick={() => isFullscreen = true} class="btn-ghost" title="Fullscreen" data-testid="viewer-fullscreen">
          <span class="i-lucide-maximize text-base"></span>
        </button>
        <button onclick={handleShare} class="btn-ghost" title="Share" data-testid="viewer-share">
          <span class="i-lucide-share text-base"></span>
        </button>
        {#if canEdit}
          <button onclick={() => openRenameModal(entryFromStore.name)} class="btn-ghost" data-testid="viewer-rename">Rename</button>
          {#if isTextFile && !isHtml}
            <button
              onclick={enterEditMode}
              class="btn-ghost"
              disabled={loading || fileContent === null}
              data-testid="viewer-edit"
            >
              Edit
            </button>
          {/if}
          <button onclick={handleDelete} class="btn-ghost text-danger" data-testid="viewer-delete">Delete</button>
        {/if}
        <!-- Prev/Next file navigation - mobile only -->
        {#if filesOnly.length > 1 && prevFile && nextFile}
          <button
            onclick={() => navigateToFile(prevFile.name)}
            class="btn-ghost lg:hidden"
            title={`Previous: ${prevFile.name}`}
          >
            <span class="i-lucide-chevron-left text-base"></span>
          </button>
          <button
            onclick={() => navigateToFile(nextFile.name)}
            class="btn-ghost lg:hidden"
            title={`Next: ${nextFile.name}`}
          >
            <span class="i-lucide-chevron-right text-base"></span>
          </button>
        {/if}
      </div>
    </div>

    <!-- Content -->
    {#if isVideo && entryFromStore?.cid}
      <VideoViewer cid={entryFromStore.cid} fileName={urlFileName} />
    {:else if isHtml && fileContent !== null}
      <HtmlViewer content={fileContent} fileName={urlFileName} />
    {:else if isImage && blobUrl}
      <!-- Image viewer -->
      <div class="flex-1 flex items-center justify-center overflow-auto bg-surface-0 p-4">
        <img
          src={blobUrl}
          alt={urlFileName}
          class="max-w-full max-h-full object-contain"
          data-testid="image-viewer"
        />
      </div>
    {:else if isAudio && blobUrl}
      <!-- Audio player -->
      <div class="flex-1 flex items-center justify-center p-4">
        <audio src={blobUrl} controls class="w-full max-w-md" />
      </div>
    {:else if isPdf && blobUrl}
      <!-- PDF viewer -->
      <iframe
        src={blobUrl}
        class="flex-1 w-full border-none"
        title={urlFileName}
      />
    {:else if isZip && fileData}
      <!-- ZIP preview -->
      <ZipPreview data={fileData} filename={urlFileName} onDownload={handleDownload} />
    {:else if isDos && currentDirCid}
      <!-- DOS executable - show DOSBox viewer -->
      <DosBox directoryCid={currentDirCid} exeName={urlFileName} />
    {:else}
      <div class="flex-1 overflow-auto p-4">
        {#if showLoading}
          <p class="text-muted animate-fade-in" data-testid="loading-indicator">Loading...</p>
        {:else if fileContent !== null}
          <pre class="text-sm text-text-1 font-mono whitespace-pre-wrap break-words">{fileContent}</pre>
        {:else if !loading && entryFromStore}
          <!-- Binary/unsupported format fallback - show download pane -->
          <!-- svelte-ignore a11y_click_events_have_key_events -->
          <!-- svelte-ignore a11y_no_static_element_interactions -->
          <div class="w-full h-full p-3">
            <div
              class="w-full h-full flex flex-col items-center justify-center text-accent cursor-pointer hover:bg-accent/10 transition-colors border border-accent/50 rounded-lg"
              onclick={handleDownload}
            >
              <span class="i-lucide-download text-4xl mb-2"></span>
              <span class="text-sm mb-1">{urlFileName}</span>
              {#if entryFromStore.size}
                <span class="text-xs text-text-2">{formatBytes(entryFromStore.size)}</span>
              {/if}
            </div>
          </div>
        {/if}
      </div>
    {/if}
  </div>
{:else if hasTreeContext && isYjsDocument && currentDirCid}
  <!-- Yjs Document view - show Tiptap editor -->
  <YjsDocumentEditor
    dirCid={currentDirCid}
    dirName={currentDirName}
    entries={entries}
  />
{:else if hasTreeContext}
  <!-- Directory view - show DirectoryActions -->
  <div class="flex-1 flex flex-col min-h-0 bg-surface-0">
    <DirectoryActions />
  </div>
{:else}
  <!-- No content view -->
  <div class="flex-1 flex items-center justify-center bg-surface-0 text-muted">
    <span>Select a file to view</span>
  </div>
{/if}

<!-- Fullscreen overlay -->
{#if isFullscreen && entryFromStore}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class="fixed inset-0 z-50 bg-black flex items-center justify-center"
    onclick={() => isFullscreen = false}
    onkeydown={(e) => { if (e.key === 'Escape') isFullscreen = false; }}
  >
    <button
      onclick={() => isFullscreen = false}
      class="absolute top-4 right-4 btn-ghost text-white z-10"
      title="Close fullscreen"
    >
      <span class="i-lucide-x text-2xl"></span>
    </button>
    {#if isImage && blobUrl}
      <img
        src={blobUrl}
        alt={urlFileName}
        class="max-w-full max-h-full object-contain"
        onclick={(e) => e.stopPropagation()}
      />
    {:else if isVideo && entryFromStore?.cid}
      <div class="w-full h-full" onclick={(e) => e.stopPropagation()}>
        <VideoViewer cid={entryFromStore.cid} fileName={urlFileName || ''} />
      </div>
    {:else if fileContent !== null}
      <pre
        class="max-w-full max-h-full overflow-auto p-8 text-white font-mono text-sm whitespace-pre-wrap"
        onclick={(e) => e.stopPropagation()}
      >{fileContent}</pre>
    {/if}
  </div>
{/if}
