// packages/hashtree-web/src/components/Viewer.tsx
import { useMemo, useState, useEffect, useRef, useCallback } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import Markdown from 'markdown-to-jsx';
import { toHex, fromHex, nhashEncode, cid } from 'hashtree';
import type { CID } from 'hashtree';
import { Avatar } from './user';
import { npubToPubkey } from '../nostr';
import { LiveVideo, LiveVideoFromHash } from './LiveVideo';
import { StreamView } from './stream';
import { FolderActions } from './FolderActions';
import { DosBoxViewer, isDosExecutable } from './DosBox';
import {
  formatBytes,
  decodeAsText,
  getTree,
} from '../store';
import { saveFile, deleteEntry, selectFile } from '../actions';
import { openRenameModal } from '../hooks/useModals';
import { useNostrStore } from '../nostr';
import { useSelectedFile, useRoute, useCurrentDirHash, useCurrentDirCid, useDirectoryEntries, useTreeRoot, useTrees } from '../hooks';
import { VisibilityIcon } from './VisibilityIcon';
import { useUpload } from '../hooks/useUpload';
import { getResolverKey } from '../refResolver';
import { useRecentlyChanged } from '../hooks/useRecentlyChanged';
import { useDelayedLoading } from '../hooks/useDelayedLoading';

// Debounce hook
function useDebounce<T extends (...args: unknown[]) => unknown>(fn: T, delay: number): T {
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  return useCallback((...args: Parameters<T>) => {
    if (timeoutRef.current) clearTimeout(timeoutRef.current);
    timeoutRef.current = setTimeout(() => fn(...args), delay);
  }, [fn, delay]) as T;
}

export function Viewer() {
  const navigate = useNavigate();
  const location = useLocation();
  const rootCid = useTreeRoot();
  const currentDirCid = useCurrentDirCid();
  const { entries } = useDirectoryEntries(currentDirCid);

  const route = useRoute();
  const viewedNpub = route.npub;
  const currentTreeName = route.treeName;
  const userNpub = useNostrStore(s => s.npub);
  const isLoggedIn = useNostrStore(s => s.isLoggedIn);

  // Get current tree for visibility info
  const targetNpub = viewedNpub || userNpub;
  const trees = useTrees(targetNpub);
  const currentTree = currentTreeName ? trees.find(t => t.name === currentTreeName) : null;

  // Get filename from URL path directly (last segment)
  const urlFileName = route.path.length > 0 ? route.path[route.path.length - 1] : null;
  const currentPath = route.path.slice(0, -1); // Directory path excludes filename

  // Find entry in current entries list (for metadata like hash)
  const entryFromStore = useMemo(() => {
    if (!urlFileName) return null;
    return entries.find(e => e.name === urlFileName && !e.isTree) || null;
  }, [urlFileName, entries]);

  // File state - content loaded from cid
  const [content, setContent] = useState<Uint8Array | null>(null);
  const [loading, setLoading] = useState(false);
  const showLoading = useDelayedLoading(loading);
  const [fileCid, setFileCid] = useState<CID | null>(null);
  const [resolvedEntry, setResolvedEntry] = useState<{ name: string; cid: CID; size?: number } | null>(null);

  // Use store entry if available, otherwise use resolved entry
  const entry = entryFromStore || resolvedEntry;

  // Resolve file cid from path when store entry is not available
  useEffect(() => {
    if (entryFromStore) {
      setResolvedEntry(null);
      return;
    }

    // For permalinks without path, check if rootCid itself is a file
    if (route.isPermalink && !urlFileName && rootCid) {
      let cancelled = false;
      const tree = getTree();
      tree.isDirectory(rootCid).then(isDir => {
        if (!cancelled && !isDir) {
          // The rootCid is the file itself
          setResolvedEntry({ name: 'file', cid: rootCid });
        }
      });
      return () => { cancelled = true; };
    }

    if (!urlFileName || !rootCid) {
      setResolvedEntry(null);
      return;
    }

    let cancelled = false;
    const tree = getTree();

    // For permalinks with path, check if rootCid itself is a file (not a directory)
    // In that case, the path is just the filename for display purposes
    if (route.isPermalink) {
      tree.isDirectory(rootCid).then(isDir => {
        if (!cancelled && !isDir) {
          // The rootCid is the file itself, use urlFileName for display
          setResolvedEntry({ name: urlFileName, cid: rootCid });
        } else if (!cancelled && isDir) {
          // It's a directory, resolve the path within it
          const fullPath = [...currentPath, urlFileName].join('/');
          tree.resolvePath(rootCid, fullPath).then(async result => {
            if (!cancelled && result) {
              const isFileDir = await tree.isDirectory(result.cid);
              if (!cancelled && !isFileDir) {
                setResolvedEntry({ name: urlFileName, cid: result.cid });
              }
            }
          });
        }
      });
    } else {
      // Non-permalink: resolve path normally
      const fullPath = [...currentPath, urlFileName].join('/');
      tree.resolvePath(rootCid, fullPath).then(async result => {
        if (!cancelled && result) {
          const isDir = await tree.isDirectory(result.cid);
          if (!cancelled && !isDir) {
            setResolvedEntry({ name: urlFileName, cid: result.cid });
          }
        }
      });
    }

    return () => { cancelled = true; };
  }, [entryFromStore, urlFileName, rootCid?.hash ? toHex(rootCid.hash) : null, currentPath.join('/'), route.isPermalink]);

  // Parse query params from location.search (works with hash routing)
  const searchParams = useMemo(() => new URLSearchParams(location.search), [location.search]);

  // Edit mode is driven by URL query param
  const isEditing = searchParams.get('edit') === '1';
  const isFullscreen = searchParams.get('fullscreen') === '1';
  const [editContent, setEditContent] = useState('');
  const [autoSave, setAutoSave] = useState(false);

  // Helper to update URL query params
  const setUrlParam = useCallback((param: string, value: boolean) => {
    const hash = window.location.hash.split('?')[0];
    const params = new URLSearchParams(window.location.hash.split('?')[1] || '');
    if (value) {
      params.set(param, '1');
    } else {
      params.delete(param);
    }
    const queryString = params.toString();
    window.location.hash = queryString ? `${hash}?${queryString}` : hash;
  }, []);

  const setIsEditing = useCallback((editing: boolean) => setUrlParam('edit', editing), [setUrlParam]);
  const setIsFullscreen = useCallback((fullscreen: boolean) => setUrlParam('fullscreen', fullscreen), [setUrlParam]);

  const mimeType = urlFileName ? getMimeType(urlFileName) : null;
  const isVideo = mimeType?.startsWith('video/');
  const isImage = mimeType?.startsWith('image/');
  const isHtml = mimeType === 'text/html';
  const isDosExe = urlFileName ? isDosExecutable(urlFileName) : false;
  const canEdit = !viewedNpub || viewedNpub === userNpub || !isLoggedIn;

  // Debug: log DOS exe detection
  if (isDosExe) {
    console.log('[Viewer] DOS exe detected:', urlFileName, { isDosExe, entry: !!entry, currentDirCid: !!currentDirCid });
  }

  // Check if currently viewed file was recently changed
  const recentlyChangedFiles = useRecentlyChanged();
  const isWebm = mimeType === 'video/webm';
  const isRecentlyChanged = urlFileName && !isEditing && recentlyChangedFiles.has(urlFileName);

  // Stable key for video - only changes when file path changes, not on hash updates
  const videoKeyRef = useRef<string | null>(null);
  const currentFilePath = urlFileName ? `${currentPath.join('/')}/${urlFileName}` : null;
  if (currentFilePath !== videoKeyRef.current) {
    videoKeyRef.current = currentFilePath;
  }

  // Load file content when entry is found (skip for video - it streams)
  useEffect(() => {
    // Reset edit content when file changes
    setEditContent('');

    // Clear content immediately when selection changes
    setContent(null);
    setFileCid(null);
    setLoading(false);

    if (!entry || isVideo || isDosExe) {
      return;
    }

    let cancelled = false;
    setLoading(true);
    setFileCid(entry.cid);

    // readFile takes CID directly
    getTree().readFile(entry.cid).then(data => {
      if (!cancelled) {
        setContent(data);
        setLoading(false);
      }
    }).catch(() => {
      if (!cancelled) {
        setLoading(false);
      }
    });

    return () => { cancelled = true; };
  }, [entry?.cid?.hash ? toHex(entry.cid.hash) : null, isVideo]);

  // Initialize editContent when entering edit mode
  useEffect(() => {
    if (isEditing && content) {
      const text = decodeAsText(content);
      if (text !== null) {
        setEditContent(text);
      }
    }
  }, [isEditing, content]);

  // Silent save for autosave - doesn't update content state to avoid re-render
  const silentSave = useCallback(async () => {
    if (isEditing && entry?.name) {
      await saveFile(entry.name, editContent);
    }
  }, [entry?.name, isEditing, editContent]);

  // Debounced autosave (1 second after typing stops)
  const debouncedSave = useDebounce(silentSave, 1000);

  const isText = content ? decodeAsText(content) !== null : false;

  const handleEdit = () => {
    if (!content) return;
    if (decodeAsText(content) !== null) {
      setIsEditing(true);
    }
  };

  const handleDownload = async () => {
    if (!entry) return;

    let data = content;
    // For video files, content isn't preloaded - fetch it now
    if (!data && isVideo) {
      data = await getTree().readFile(entry.cid);
    }
    if (!data) return;

    const blob = new Blob([new Uint8Array(data)], { type: mimeType || 'application/octet-stream' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = entry.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleSave = async () => {
    const newData = await saveFile(entry?.name, editContent);
    if (newData) setContent(newData);
  };

  const handleInput = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    setEditContent(e.target.value);
    if (autoSave) {
      debouncedSave();
    }
  };

  return (
    <div className="flex-1 flex flex-col min-h-0 bg-surface-0">
      {/* Header - only show when file selected and not fullscreen */}
      {(entry || urlFileName) && !isFullscreen && (
        <div className="h-10 shrink-0 px-3 border-b border-surface-3 flex items-center justify-between bg-surface-1">
          <span className="font-medium flex items-center gap-2">
            {(entry || urlFileName) && (
            <button
              onClick={() => {
                // Navigate to directory (remove file from URL)
                const parts: string[] = [];
                if (viewedNpub && currentTreeName) {
                  parts.push(viewedNpub, currentTreeName, ...currentPath);
                }
                navigate('/' + parts.map(encodeURIComponent).join('/'));
              }}
              className="bg-transparent border-none text-text-1 cursor-pointer p-1 lg:hidden"
            >
              <span className="i-lucide-chevron-left text-lg" />
            </button>
          )}
          {/* Show avatar (for npub routes) or hash icon (for nhash routes) */}
          {viewedNpub ? (
            <Link to={`/${viewedNpub}/profile`} className="shrink-0">
              <Avatar pubkey={npubToPubkey(viewedNpub) || viewedNpub} size={20} />
            </Link>
          ) : route.isPermalink && (
            <span className="i-lucide-hash text-accent shrink-0" />
          )}
          {/* Visibility icon */}
          {currentTree && (
            <VisibilityIcon visibility={currentTree.visibility} className="text-text-2" />
          )}
          {/* File type icon */}
          <span className={`${getFileIcon(entry?.name || urlFileName || '')} text-text-2 shrink-0`} />
          {entry?.name || urlFileName || ''}
          {isRecentlyChanged && (
            <span className="ml-2 px-1.5 py-0.5 text-xs font-bold bg-red-600 text-white rounded animate-pulse">
              LIVE
            </span>
          )}
        </span>

        {entry && !isEditing && (
          <div className="flex items-center gap-2">
            <button
              onClick={handleDownload}
              className="btn-ghost"
              title="Download file"
              disabled={loading && !isVideo}
            >
              Download
            </button>
            {/* Permalink to this specific file's hash */}
            <Link
              to={`/${nhashEncode(toHex(entry.cid.hash))}/${encodeURIComponent(entry.name)}`}
              className="btn-ghost no-underline"
              title={toHex(entry.cid.hash)}
            >
              Permalink
            </Link>
            <button
              onClick={() => setIsFullscreen(true)}
              className="btn-ghost"
              title="Fullscreen"
            >
              <span className="i-lucide-maximize text-base" />
            </button>
            {canEdit && (
              <>
                <button onClick={() => openRenameModal(entry?.name)} className="btn-ghost">Rename</button>
                {isLikelyTextFile(entry.name) && (
                  <button
                    onClick={handleEdit}
                    className="btn-ghost"
                    disabled={loading || !content || !isText}
                  >
                    Edit
                  </button>
                )}
                <button
                  onClick={() => {
                    if (confirm(`Delete ${entry.name}?`)) {
                      deleteEntry(entry.name);
                      // Navigate back to directory
                      const parts: string[] = [];
                      if (viewedNpub && currentTreeName) {
                        parts.push(viewedNpub, currentTreeName, ...currentPath);
                      }
                      navigate('/' + parts.map(encodeURIComponent).join('/'));
                    }
                  }}
                  className="btn-ghost text-danger"
                >
                  Delete
                </button>
              </>
            )}
          </div>
        )}

        {isEditing && (
          <div className="flex items-center gap-2">
            <label className="flex items-center gap-1 text-xs text-text-2 cursor-pointer">
              <input
                type="checkbox"
                checked={autoSave}
                onChange={(e) => { setAutoSave(e.target.checked); }}
                className="cursor-pointer"
              />
              Auto
            </label>
            <button onClick={handleSave} className="btn-success">
              Save
            </button>
            <button onClick={() => { setIsEditing(false); }} className="btn-ghost">
              Done
            </button>
          </div>
        )}
        </div>
      )}

      {/* Content */}
      <div className={`flex-1 overflow-auto ${isVideo || isImage || isHtml || isDosExe ? '' : 'p-4'}`}>
        {/* Show textarea immediately if in edit mode with a filename (even before entry loads) */}
        {isEditing && urlFileName ? (
          <textarea
            value={editContent}
            onChange={handleInput}
            autoFocus={editContent === ''}
            className="w-full h-full min-h-300px input font-mono text-sm resize-y"
          />
        ) : !entry ? (
          <DirectoryActions />
        ) : loading ? (
          showLoading ? <div className="w-full h-full flex items-center justify-center text-muted">Loading...</div> : null
        ) : isDosExe && currentDirCid ? (
          // DOS executable - show DOSBox viewer
          // Key on CID hash to prevent remounting when layout changes (fullscreen toggle)
          <DosBoxViewer
            key={toHex(entry.cid.hash)}
            exeCid={entry.cid}
            directoryCid={currentDirCid}
            exeName={entry.name}
          />
        ) : isVideo && mimeType ? (
          viewedNpub && currentTreeName ? (
            // Use resolver subscription for live updates
            <LiveVideo
              key={videoKeyRef.current}
              resolverKey={getResolverKey(viewedNpub, currentTreeName)}
              filePath={[...currentPath, entry.name]}
              mimeType={mimeType}
              initialCid={rootCid}
            />
          ) : (
            // Direct hash access (no resolver)
            <LiveVideoFromHash cid={entry.cid} mimeType={mimeType} />
          )
        ) : content ? (
          <ContentView data={content} filename={entry.name} onDownload={handleDownload} />
        ) : null}
      </div>
    </div>
  );
}

function ContentView({ data, filename, onDownload }: { data: Uint8Array; filename?: string; onDownload?: () => void }) {
  const text = decodeAsText(data);
  const mimeType = getMimeType(filename);
  const blobUrl = useMemo(() => {
    if (mimeType && isInlineViewable(mimeType)) {
      const blob = new Blob([new Uint8Array(data)], { type: mimeType });
      return URL.createObjectURL(blob);
    }
    return null;
  }, [data, mimeType]);

  // HTML files - render in sandboxed iframe
  const isHtml = filename?.toLowerCase().endsWith('.html') || filename?.toLowerCase().endsWith('.htm');
  const htmlBlobUrl = useMemo(() => {
    if (text !== null && isHtml) {
      const blob = new Blob([text], { type: 'text/html' });
      return URL.createObjectURL(blob);
    }
    return null;
  }, [text, isHtml]);

  if (htmlBlobUrl) {
    return (
      <iframe
        src={htmlBlobUrl}
        className="block w-full h-full border-none bg-surface-0"
        title={filename}
        sandbox="allow-scripts"
      />
    );
  }

  // Markdown files
  const isMarkdown = filename?.toLowerCase().endsWith('.md');
  if (text !== null && isMarkdown) {
    return (
      <div className="prose prose-sm max-w-none text-text-1">
        <Markdown>{text}</Markdown>
      </div>
    );
  }

  // Text content
  if (text !== null) {
    return (
      <pre className="m-0 whitespace-pre-wrap break-all text-sm font-mono">
        {text}
      </pre>
    );
  }

  // Inline viewable content
  if (blobUrl && mimeType) {
    if (mimeType.startsWith('image/')) {
      return (
        <div className="w-full h-full flex items-center justify-center">
          <img
            src={blobUrl}
            alt={filename}
            className="max-w-full max-h-full object-contain"
          />
        </div>
      );
    }

    if (mimeType === 'application/pdf') {
      return (
        <iframe
          src={blobUrl}
          className="w-full h-300px border-none"
          title={filename}
        />
      );
    }

    // Note: video is handled by LiveVideo in Preview component

    if (mimeType.startsWith('audio/')) {
      return (
        <audio src={blobUrl} controls className="w-full" />
      );
    }
  }

  // Binary/unsupported format fallback - show download pane (matches upload zone size)
  return (
    <div className="w-full h-full p-3">
      <div
        className="w-full h-full flex flex-col items-center justify-center text-accent cursor-pointer hover:bg-accent/10 transition-colors border border-accent/50 rounded-lg"
        onClick={onDownload}
      >
        <span className="i-lucide-download text-4xl mb-2" />
        <span className="text-sm mb-1">{filename || 'Download file'}</span>
        <span className="text-xs text-text-2">{formatBytes(data.length)}</span>
      </div>
    </div>
  );
}

function getMimeType(filename?: string): string | null {
  if (!filename) return null;

  const ext = filename.split('.').pop()?.toLowerCase();
  const mimeTypes: Record<string, string> = {
    // Images
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    gif: 'image/gif',
    webp: 'image/webp',
    avif: 'image/avif',
    heic: 'image/heic',
    heif: 'image/heif',
    svg: 'image/svg+xml',
    ico: 'image/x-icon',
    bmp: 'image/bmp',
    tiff: 'image/tiff',
    tif: 'image/tiff',

    // PDF
    pdf: 'application/pdf',

    // Video
    mp4: 'video/mp4',
    webm: 'video/webm',
    ogg: 'video/ogg',
    mov: 'video/quicktime',

    // Audio
    mp3: 'audio/mpeg',
    wav: 'audio/wav',
    flac: 'audio/flac',
    m4a: 'audio/mp4',

    // HTML
    html: 'text/html',
    htm: 'text/html',
  };

  return ext ? mimeTypes[ext] || null : null;
}

function isInlineViewable(mimeType: string): boolean {
  return (
    mimeType.startsWith('image/') ||
    mimeType.startsWith('video/') ||
    mimeType.startsWith('audio/') ||
    mimeType === 'application/pdf'
  );
}

// Get icon class based on file extension
function getFileIcon(filename: string): string {
  const ext = filename.split('.').pop()?.toLowerCase() || '';
  switch (ext) {
    case 'jpg': case 'jpeg': case 'png': case 'gif': case 'webp': case 'svg': case 'ico': case 'bmp':
      return 'i-lucide-image';
    case 'mp4': case 'webm': case 'mkv': case 'avi': case 'mov':
      return 'i-lucide-video';
    case 'mp3': case 'wav': case 'ogg': case 'flac': case 'm4a':
      return 'i-lucide-music';
    case 'exe': case 'com': case 'bat':
      return 'i-lucide-terminal';
    case 'js': case 'ts': case 'jsx': case 'tsx': case 'py': case 'rb': case 'go': case 'rs':
    case 'c': case 'cpp': case 'h': case 'java': case 'php': case 'sh': case 'bash':
      return 'i-lucide-file-code';
    case 'json': case 'yaml': case 'yml': case 'toml': case 'xml': case 'ini': case 'env':
      return 'i-lucide-file-json';
    case 'pdf': case 'doc': case 'docx': case 'txt': case 'md': case 'markdown': case 'rst':
      return 'i-lucide-file-text';
    case 'xls': case 'xlsx': case 'csv':
      return 'i-lucide-file-spreadsheet';
    case 'zip': case 'tar': case 'gz': case 'rar': case '7z':
      return 'i-lucide-file-archive';
    case 'html': case 'htm': case 'css': case 'scss': case 'sass': case 'less':
      return 'i-lucide-file-code';
    default:
      return 'i-lucide-file';
  }
}

function isLikelyTextFile(filename?: string): boolean {
  if (!filename) return false;
  const ext = filename.split('.').pop()?.toLowerCase();
  if (!ext) return true; // No extension - assume text
  const textExtensions = new Set([
    'txt', 'md', 'json', 'js', 'ts', 'tsx', 'jsx', 'css', 'scss', 'less',
    'html', 'htm', 'xml', 'svg', 'yaml', 'yml', 'toml', 'ini', 'cfg', 'conf',
    'sh', 'bash', 'zsh', 'fish', 'py', 'rb', 'rs', 'go', 'java', 'c', 'cpp',
    'h', 'hpp', 'cs', 'php', 'pl', 'lua', 'vim', 'sql', 'graphql', 'prisma',
    'env', 'gitignore', 'dockerignore', 'editorconfig', 'prettierrc', 'eslintrc',
    'log', 'csv', 'tsv', 'lock', 'map'
  ]);
  return textExtensions.has(ext);
}

function DirectoryActions() {
  const rootCid = useTreeRoot();
  const rootHash = rootCid?.hash ?? null;
  const currentDirCid = useCurrentDirCid();
  const currentDirHash = currentDirCid?.hash ?? null;
  const { entries } = useDirectoryEntries(currentDirCid);
  const route = useRoute();
  const viewedNpub = route.npub;
  const userNpub = useNostrStore(s => s.npub);
  const isLoggedIn = useNostrStore(s => s.isLoggedIn);
  const { uploadProgress, uploadFiles, cancelUpload } = useUpload();

  const canEdit = !viewedNpub || viewedNpub === userNpub || !isLoggedIn;
  // Show actions if we have a tree OR we're in a tree context (empty tree that hasn't been created yet)
  const hasTreeContext = rootHash !== null || (route.treeName !== null && canEdit);
  const [readmeContent, setReadmeContent] = useState<string | null>(null);
  const [isDraggingOver, setIsDraggingOver] = useState(false);
  const dirHash = currentDirHash ? toHex(currentDirHash) : null;
  const fileInputRef = useRef<HTMLInputElement>(null);

  const openFilePicker = () => {
    fileInputRef.current?.click();
  };

  const handleFileInputChange = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (files && files.length > 0) {
      await uploadFiles(files);
    }
    // Reset input so same file can be selected again
    e.target.value = '';
  };

  // Handle external file drop
  const handleFileDrop = async (e: React.DragEvent) => {
    e.preventDefault();
    setIsDraggingOver(false);
    if (!canEdit) return;

    const files = e.dataTransfer?.files;
    if (files && files.length > 0) {
      await uploadFiles(files);
    }
  };

  const handleFileDragOver = (e: React.DragEvent) => {
    if (!canEdit) return;
    if (e.dataTransfer?.types.includes('Files')) {
      e.preventDefault();
      e.dataTransfer.dropEffect = 'copy';
      setIsDraggingOver(true);
    }
  };

  const handleFileDragLeave = (e: React.DragEvent) => {
    const rect = (e.currentTarget as HTMLElement).getBoundingClientRect();
    if (
      e.clientX < rect.left ||
      e.clientX > rect.right ||
      e.clientY < rect.top ||
      e.clientY > rect.bottom
    ) {
      setIsDraggingOver(false);
    }
  };

  // Find and load README.md
  useEffect(() => {
    setReadmeContent(null);
    const readmeEntry = entries.find(
      e => e.name.toLowerCase() === 'readme.md' && !e.isTree
    );
    if (!readmeEntry) return;

    let cancelled = false;
    // readFile takes CID directly
    getTree().readFile(readmeEntry.cid).then(data => {
      if (!cancelled && data) {
        const text = decodeAsText(data);
        if (text) setReadmeContent(text);
      }
    });
    return () => { cancelled = true; };
  }, [entries]);

  return (
    <div
      className="flex flex-col h-full"
      onDragOver={handleFileDragOver}
      onDragLeave={handleFileDragLeave}
      onDrop={handleFileDrop}
    >
      {/* Action buttons */}
      {hasTreeContext && (
        <div className="p-3 shrink-0">
          <FolderActions dirCid={currentDirCid ?? undefined} canEdit={canEdit} />
        </div>
      )}

      {/* Upload drop zone */}
      {hasTreeContext && canEdit && !readmeContent && (
        <div
          className={`flex-1 mx-3 mb-3 flex items-center justify-center cursor-pointer transition-colors border border-surface-3 rounded-lg ${isDraggingOver ? 'bg-surface-1/50' : 'hover:bg-surface-1/50'}`}
          onClick={uploadProgress ? undefined : openFilePicker}
        >
          {uploadProgress ? (
            <div className="flex flex-col items-center text-text-2 w-64">
              <span className="i-lucide-loader-2 text-4xl mb-3 animate-spin text-accent" />
              <span className="text-sm mb-2 truncate max-w-full">{uploadProgress.fileName}</span>
              <div className="w-full h-2 bg-surface-2 rounded overflow-hidden">
                <div
                  className="h-full bg-accent transition-all"
                  style={{ width: `${(uploadProgress.current / uploadProgress.total) * 100}%` }}
                />
              </div>
              <span className="text-xs mt-1 text-text-3">
                {uploadProgress.current} / {uploadProgress.total}
              </span>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  cancelUpload();
                }}
                className="mt-3 btn-ghost text-xs px-3 py-1 text-danger hover:bg-danger/10"
              >
                Cancel
              </button>
            </div>
          ) : (
            <div className="flex flex-col items-center text-text-3">
              <span className="i-lucide-plus text-4xl mb-2" />
              <span className="text-sm">Drop or click to add</span>
            </div>
          )}
          <input
            ref={fileInputRef}
            type="file"
            multiple
            className="hidden"
            onChange={handleFileInputChange}
          />
        </div>
      )}

      {/* README.md content */}
      {readmeContent && (
        <div className="flex-1 overflow-auto px-4 pb-4 lg:px-8 lg:pb-8">
          <div className="flex items-center justify-between mb-3">
            <span className="text-text-2 text-sm font-medium">README.md</span>
            {canEdit && (
              <button
                onClick={() => {
                  const readmeEntry = entries.find(
                    e => e.name.toLowerCase() === 'readme.md' && !e.isTree
                  );
                  if (readmeEntry) {
                    selectFile(readmeEntry);
                  }
                }}
                className="btn-ghost text-xs px-2 py-1"
              >
                Edit
              </button>
            )}
          </div>
          <div className="prose prose-sm max-w-none text-text-1">
            <Markdown>{readmeContent}</Markdown>
          </div>
        </div>
      )}
    </div>
  );
}

// packages/hashtree-web/src/components/Viewer/Viewer.svelte
<script lang="ts">
  /**
   * Viewer - main file viewer component
   * Port of React Viewer component
   */
  import { toHex, nhashEncode } from 'hashtree';
  import { routeStore, treeRootStore, currentDirCidStore, directoryEntriesStore, currentHash, createTreesStore, addRecent, recentlyChangedFiles } from '../../stores';
  import { looksLikeFile } from '../../utils/route';
  import { getTree, decodeAsText, formatBytes } from '../../store';
  import { nostrStore, npubToPubkey } from '../../nostr';
  import { deleteEntry } from '../../actions';
  import { openRenameModal, openShareModal } from '../../stores/modals';
  import DirectoryActions from './DirectoryActions.svelte';
  import FileEditor from './FileEditor.svelte';
  import HtmlViewer from './HtmlViewer.svelte';
  import VideoViewer from './VideoViewer.svelte';
  import YjsDocumentEditor from './YjsDocumentEditor.svelte';
  import ZipPreview from './ZipPreview.svelte';
  import DosBox from './DosBox.svelte';
  import { Avatar } from '../User';
  import VisibilityIcon from '../VisibilityIcon.svelte';

  let route = $derived($routeStore);
  let rootCid = $derived($treeRootStore);
  let currentDirCid = $derived($currentDirCidStore);
  let dirEntries = $derived($directoryEntriesStore);
  let entries = $derived(dirEntries.entries);
  let hash = $derived($currentHash);

  // Check if user can edit (owns the tree or is not viewing another user's tree)
  let userNpub = $derived($nostrStore.npub);
  let isLoggedIn = $derived($nostrStore.isLoggedIn);
  let viewedNpub = $derived(route.npub);
  let canEdit = $derived(!viewedNpub || viewedNpub === userNpub || !isLoggedIn);

  // Get current tree for visibility info
  let targetNpub = $derived(viewedNpub || userNpub);
  let treesStore = $derived(createTreesStore(targetNpub));
  let trees = $derived($treesStore);
  let currentTreeName = $derived(route.treeName);
  let currentTree = $derived(currentTreeName ? trees.find(t => t.name === currentTreeName) : null);

  // Get filename from URL path - uses path type heuristic
  let urlPath = $derived(route.path);
  let lastSegment = $derived(urlPath.length > 0 ? urlPath[urlPath.length - 1] : null);
  // Don't treat .yjs files as viewable files - they are internal to Yjs documents
  let hasFile = $derived(lastSegment && looksLikeFile(lastSegment) && !lastSegment.endsWith('.yjs'));
  let urlFileName = $derived(hasFile ? lastSegment : null);

  // Parse query params from URL hash - use currentHash store for reactivity
  let searchParams = $derived.by(() => {
    const qIdx = hash.indexOf('?');
    if (qIdx === -1) return new URLSearchParams();
    return new URLSearchParams(hash.slice(qIdx + 1));
  });

  let isEditing = $derived(searchParams.get('edit') === '1');

  // Find entry in current entries list, or create synthetic entry for file permalinks
  let entryFromStore = $derived.by(() => {
    if (!urlFileName) return null;

    // First try to find the file in entries (works for files within directories)
    const fromEntries = entries.find(e => e.name === urlFileName && !e.isTree);
    if (fromEntries) return fromEntries;

    // For direct file permalinks (no directory listing), the rootCid IS the file's CID
    // Create a synthetic entry since there's no directory listing
    if (route.isPermalink && rootCid && entries.length === 0) {
      return {
        name: urlFileName,
        cid: rootCid,
        size: 0,
        isTree: false,
      };
    }

    return null;
  });

  // Get files only (no directories) for prev/next navigation
  let filesOnly = $derived(entries.filter(e => !e.isTree));
  let currentFileIndex = $derived(urlFileName ? filesOnly.findIndex(e => e.name === urlFileName) : -1);
  // Wrap around at start/end
  let prevFile = $derived(
    filesOnly.length > 1 && currentFileIndex >= 0
      ? filesOnly[(currentFileIndex - 1 + filesOnly.length) % filesOnly.length]
      : null
  );
  let nextFile = $derived(
    filesOnly.length > 1 && currentFileIndex >= 0
      ? filesOnly[(currentFileIndex + 1) % filesOnly.length]
      : null
  );

  // Navigate to a file in the same directory
  function navigateToFile(fileName: string) {
    const dirPath = route.path.slice(0, -1); // Remove current filename
    const parts: string[] = [];
    if (route.npub && route.treeName) {
      parts.push(route.npub, route.treeName, ...dirPath, fileName);
    }
    const linkKeySuffix = route.linkKey ? `?k=${route.linkKey}` : '';
    window.location.hash = '/' + parts.map(encodeURIComponent).join('/') + linkKeySuffix;
  }

  // Check if we have a tree context (for showing actions)
  let hasTreeContext = $derived(!!rootCid || !!route.treeName);

  // Check if current directory is a Yjs document (contains .yjs file)
  let isYjsDocument = $derived(entries.some(e => e.name === '.yjs' && !e.isTree));

  // Get current directory name from path
  let currentDirName = $derived.by(() => {
    const pathSegments = route.path;
    return pathSegments.length > 0 ? pathSegments[pathSegments.length - 1] : route.treeName || 'Document';
  });

  // File content state - raw binary data
  let fileData = $state<Uint8Array | null>(null);
  // Decoded text content (null if binary)
  let fileContent = $state<string | null>(null);
  let loading = $state(false);
  // Only show loading indicator after 2 seconds (avoid flash for fast loads)
  let showLoading = $state(false);
  let loadingTimer: ReturnType<typeof setTimeout> | null = null;
  // Blob URL for binary content (images, etc)
  let blobUrl = $state<string | null>(null);
  // Track current blob URL outside of reactive system for cleanup
  let currentBlobUrl: string | null = null;
  // Fullscreen mode
  let isFullscreen = $state(false);

  // MIME type detection
  function getMimeType(filename?: string): string | null {
    if (!filename) return null;
    const ext = filename.split('.').pop()?.toLowerCase();
    const mimeTypes: Record<string, string> = {
      // Images
      png: 'image/png',
      jpg: 'image/jpeg',
      jpeg: 'image/jpeg',
      gif: 'image/gif',
      webp: 'image/webp',
      avif: 'image/avif',
      svg: 'image/svg+xml',
      ico: 'image/x-icon',
      bmp: 'image/bmp',
      // PDF
      pdf: 'application/pdf',
      // Audio
      mp3: 'audio/mpeg',
      wav: 'audio/wav',
      flac: 'audio/flac',
      m4a: 'audio/mp4',
      ogg: 'audio/ogg',
    };
    return ext ? mimeTypes[ext] || null : null;
  }

  // Helper to clean up blob URL
  function cleanupBlobUrl() {
    if (currentBlobUrl) {
      URL.revokeObjectURL(currentBlobUrl);
      currentBlobUrl = null;
    }
  }

  // Load file content when entry changes
  $effect(() => {
    // Clean up previous blob URL (use non-reactive variable)
    cleanupBlobUrl();

    // Clear loading timer
    if (loadingTimer) {
      clearTimeout(loadingTimer);
      loadingTimer = null;
    }

    fileData = null;
    fileContent = null;
    blobUrl = null;
    loading = false;
    showLoading = false;

    const entry = entryFromStore;
    if (!entry) return;

    // Skip loading for video files - they stream separately
    // Skip loading for DOS executables - they use their own loader
    if (isVideo || isDos) return;

    loading = true;
    let cancelled = false;

    // Show loading indicator only after 2 seconds delay
    loadingTimer = setTimeout(() => {
      if (!cancelled && loading) {
        showLoading = true;
      }
    }, 2000);

    getTree().readFile(entry.cid).then(data => {
      if (!cancelled && data) {
        fileData = data;
        // Try to decode as text
        const text = decodeAsText(data);
        fileContent = text;

        // If not text, create blob URL for binary viewing
        if (text === null && urlFileName) {
          const mimeType = getMimeType(urlFileName);
          if (mimeType) {
            const blob = new Blob([data], { type: mimeType });
            const newUrl = URL.createObjectURL(blob);
            currentBlobUrl = newUrl;
            blobUrl = newUrl;
          }
        }
      }
      loading = false;
      showLoading = false;
      if (loadingTimer) {
        clearTimeout(loadingTimer);
        loadingTimer = null;
      }
    }).catch(() => {
      loading = false;
      showLoading = false;
      if (loadingTimer) {
        clearTimeout(loadingTimer);
        loadingTimer = null;
      }
    });

    return () => {
      cancelled = true;
      cleanupBlobUrl();
      if (loadingTimer) {
        clearTimeout(loadingTimer);
        loadingTimer = null;
      }
    };
  });

  // Track file visits in recents
  $effect(() => {
    if (!urlFileName || !route.npub || !route.treeName) return;

    // Build full path for the file
    const pathParts = route.path.join('/');
    const fullPath = `/${route.npub}/${route.treeName}${pathParts ? '/' + pathParts : ''}`;

    addRecent({
      type: 'file',
      label: urlFileName,
      path: fullPath,
      npub: route.npub,
      treeName: route.treeName,
    });
  });

  function exitEditMode() {
    // Remove ?edit=1 from URL
    const hashBase = window.location.hash.split('?')[0];
    const params = new URLSearchParams(window.location.hash.split('?')[1] || '');
    params.delete('edit');
    const queryString = params.toString();
    window.location.hash = queryString ? `${hashBase}?${queryString}` : hashBase;
  }

  function enterEditMode() {
    // Add ?edit=1 to URL
    const hashBase = window.location.hash.split('?')[0];
    const params = new URLSearchParams(window.location.hash.split('?')[1] || '');
    params.set('edit', '1');
    window.location.hash = `${hashBase}?${params.toString()}`;
  }

  function handleDelete() {
    if (!entryFromStore) return;
    if (confirm(`Delete ${entryFromStore.name}?`)) {
      deleteEntry(entryFromStore.name);
      // Navigate back to directory
      const dirPath = route.path.slice(0, -1);
      const parts: string[] = [];
      if (route.npub && route.treeName) {
        parts.push(route.npub, route.treeName, ...dirPath);
      }
      const linkKeySuffix = route.linkKey ? `?k=${route.linkKey}` : '';
      window.location.hash = '#/' + parts.map(encodeURIComponent).join('/') + linkKeySuffix;
    }
  }

  // Keyboard navigation for file viewing
  $effect(() => {
    if (!entryFromStore && !urlFileName) return; // Only when viewing a file
    if (isEditing) return; // Don't navigate when editing

    const handleKeyDown = (e: KeyboardEvent) => {
      // Don't interfere with browser shortcuts (Cmd/Ctrl + arrows)
      if (e.metaKey || e.ctrlKey) return;
      // Don't interfere when focus is in input/textarea
      const target = e.target as HTMLElement;
      if (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA' || target.isContentEditable) return;

      const key = e.key.toLowerCase();

      // Escape: back to directory
      if (key === 'escape') {
        e.preventDefault();
        (document.activeElement as HTMLElement)?.blur();
        window.location.hash = backUrl.slice(1); // Remove leading #
        return;
      }

      // j/k/ArrowDown/ArrowUp: next/prev file (vertical navigation)
      // l/ArrowRight: next file (horizontal navigation)
      if ((key === 'j' || key === 'arrowdown' || key === 'l' || key === 'arrowright') && nextFile) {
        e.preventDefault();
        navigateToFile(nextFile.name);
        return;
      }

      // k/ArrowUp/h/ArrowLeft: prev file
      if ((key === 'k' || key === 'arrowup' || key === 'h' || key === 'arrowleft') && prevFile) {
        e.preventDefault();
        navigateToFile(prevFile.name);
        return;
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  });

  // Check if file looks like text based on extension
  function isLikelyTextFile(filename: string): boolean {
    const textExtensions = ['txt', 'md', 'json', 'js', 'ts', 'jsx', 'tsx', 'css', 'scss', 'html', 'xml', 'yaml', 'yml', 'toml', 'ini', 'cfg', 'conf', 'sh', 'bash', 'py', 'rb', 'go', 'rs', 'c', 'cpp', 'h', 'hpp', 'java', 'php', 'sql', 'svelte', 'vue'];
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return textExtensions.includes(ext);
  }

  let isTextFile = $derived(urlFileName ? isLikelyTextFile(urlFileName) : false);

  // Check if file is HTML (should be rendered in iframe)
  function isHtmlFile(filename: string): boolean {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return ext === 'html' || ext === 'htm';
  }

  let isHtml = $derived(urlFileName ? isHtmlFile(urlFileName) : false);

  // Check if file is a video
  function isVideoFile(filename: string): boolean {
    const videoExtensions = ['mp4', 'webm', 'ogg', 'ogv', 'mov', 'avi', 'mkv'];
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return videoExtensions.includes(ext);
  }

  let isVideo = $derived(urlFileName ? isVideoFile(urlFileName) : false);

  // Check if file is an image
  function isImageFile(filename: string): boolean {
    const imageExtensions = ['png', 'jpg', 'jpeg', 'gif', 'webp', 'avif', 'svg', 'ico', 'bmp'];
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return imageExtensions.includes(ext);
  }

  let isImage = $derived(urlFileName ? isImageFile(urlFileName) : false);

  // Check if file is audio
  function isAudioFile(filename: string): boolean {
    const audioExtensions = ['mp3', 'wav', 'flac', 'm4a', 'ogg', 'aac'];
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return audioExtensions.includes(ext);
  }

  let isAudio = $derived(urlFileName ? isAudioFile(urlFileName) : false);

  // Check if file is PDF
  function isPdfFile(filename: string): boolean {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return ext === 'pdf';
  }

  let isPdf = $derived(urlFileName ? isPdfFile(urlFileName) : false);

  // Check if file is ZIP archive
  function isZipFile(filename: string): boolean {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return ext === 'zip';
  }

  let isZip = $derived(urlFileName ? isZipFile(urlFileName) : false);

  // Check if file is DOS executable
  function isDosExecutable(filename: string): boolean {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    return ext === 'exe' || ext === 'com' || ext === 'bat';
  }

  let isDos = $derived(urlFileName ? isDosExecutable(urlFileName) : false);

  // Check if file was recently changed (for LIVE indicator)
  let changedFiles = $derived($recentlyChangedFiles);
  let isRecentlyChanged = $derived(urlFileName ? changedFiles.has(urlFileName) : false);

  // Build permalink URL for the current file
  let permalinkUrl = $derived.by(() => {
    if (!entryFromStore?.cid?.hash) return null;
    const hashHex = toHex(entryFromStore.cid.hash);
    const keyHex = entryFromStore.cid.key ? toHex(entryFromStore.cid.key) : undefined;
    const nhash = nhashEncode({ hash: hashHex, decryptKey: keyHex });
    return `#/${nhash}/${encodeURIComponent(entryFromStore.name)}`;
  });

  // Build back URL (directory without file)
  let backUrl = $derived.by(() => {
    const dirPath = route.path.slice(0, -1);
    const parts: string[] = [];
    if (route.npub && route.treeName) {
      parts.push(route.npub, route.treeName, ...dirPath);
    }
    const linkKeySuffix = route.linkKey ? `?k=${route.linkKey}` : '';
    return '#/' + parts.map(encodeURIComponent).join('/') + linkKeySuffix;
  });

  // Get file icon based on extension
  function getFileIcon(filename: string): string {
    const ext = filename.split('.').pop()?.toLowerCase() || '';
    const iconMap: Record<string, string> = {
      // Images
      png: 'i-lucide-image',
      jpg: 'i-lucide-image',
      jpeg: 'i-lucide-image',
      gif: 'i-lucide-image',
      webp: 'i-lucide-image',
      svg: 'i-lucide-image',
      // Video
      mp4: 'i-lucide-video',
      webm: 'i-lucide-video',
      mov: 'i-lucide-video',
      // Audio
      mp3: 'i-lucide-music',
      wav: 'i-lucide-music',
      flac: 'i-lucide-music',
      // Code
      js: 'i-lucide-file-code',
      ts: 'i-lucide-file-code',
      jsx: 'i-lucide-file-code',
      tsx: 'i-lucide-file-code',
      py: 'i-lucide-file-code',
      rs: 'i-lucide-file-code',
      go: 'i-lucide-file-code',
      // Documents
      md: 'i-lucide-file-text',
      txt: 'i-lucide-file-text',
      pdf: 'i-lucide-file-text',
      // Archive
      zip: 'i-lucide-archive',
      tar: 'i-lucide-archive',
      gz: 'i-lucide-archive',
    };
    return iconMap[ext] || 'i-lucide-file';
  }

  let fileIcon = $derived(urlFileName ? getFileIcon(urlFileName) : 'i-lucide-file');

  // Download handler
  async function handleDownload() {
    if (!entryFromStore) return;

    let data = fileData;
    // For video files, content isn't preloaded - fetch it now
    if (!data && isVideo) {
      data = await getTree().readFile(entryFromStore.cid);
    }
    if (!data) return;

    const mimeType = getMimeType(urlFileName || '') || 'application/octet-stream';
    const blob = new Blob([data], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = entryFromStore.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  // Share handler
  function handleShare() {
    // Strip ?edit=1 from URL when sharing
    let url = window.location.href;
    url = url.replace(/[?&]edit=1/, '');
    openShareModal(url);
  }
</script>

{#if urlFileName && isEditing}
  <!-- Edit mode - show even if entry not found yet (newly created file) -->
  <FileEditor
    fileName={urlFileName}
    initialContent={fileContent || ''}
    onDone={exitEditMode}
  />
{:else if urlFileName && entryFromStore}
  <!-- File view - show content -->
  <div class="flex-1 flex flex-col min-h-0 bg-surface-0">
    <!-- Header -->
    <div class="shrink-0 px-3 py-2 border-b border-surface-3 flex flex-wrap items-center justify-between gap-2 bg-surface-1" data-testid="viewer-header">
      <div class="flex items-center gap-2 min-w-0">
        <a href={backUrl} class="btn-ghost p-1 no-underline" title="Back to folder" data-testid="viewer-back">
          <span class="i-lucide-chevron-left text-lg"></span>
        </a>
        <!-- Avatar (for npub routes) or LinkLock/globe (for nhash routes) -->
        {#if viewedNpub}
          <a href="#/{viewedNpub}/profile" class="shrink-0">
            <Avatar pubkey={npubToPubkey(viewedNpub) || ''} size={20} />
          </a>
        {:else if route.isPermalink}
          {#if rootCid?.key}
            <!-- LinkLockIcon for encrypted permalink -->
            <span class="relative inline-block shrink-0 text-text-2" title="Encrypted permalink">
              <span class="i-lucide-link"></span>
              <span class="i-lucide-lock absolute -bottom-0.5 -right-1.5 text-[0.6em]"></span>
            </span>
          {:else}
            <span class="i-lucide-globe text-text-2 shrink-0" title="Public permalink"></span>
          {/if}
        {/if}
        <!-- Visibility icon (for trees) -->
        {#if currentTree}
          <VisibilityIcon visibility={currentTree.visibility} class="text-text-2" />
        {/if}
        <!-- File type icon -->
        <span class="{fileIcon} text-text-2 shrink-0"></span>
        <span class="font-medium text-text-1 truncate">{entryFromStore.name}</span>
        {#if isRecentlyChanged}
          <span class="ml-2 px-1.5 py-0.5 text-xs font-bold bg-red-600 text-white rounded animate-pulse">LIVE</span>
        {/if}
      </div>
      <div class="flex items-center gap-1 flex-wrap">
        <button onclick={handleDownload} class="btn-ghost" title="Download file" data-testid="viewer-download" disabled={loading && !isVideo}>
          Download
        </button>
        {#if permalinkUrl}
          <a href={permalinkUrl} class="btn-ghost no-underline" title={entryFromStore?.cid?.hash ? toHex(entryFromStore.cid.hash) : ''} data-testid="viewer-permalink">
            Permalink
          </a>
        {/if}
        <button onclick={() => isFullscreen = true} class="btn-ghost" title="Fullscreen" data-testid="viewer-fullscreen">
          <span class="i-lucide-maximize text-base"></span>
        </button>
        <button onclick={handleShare} class="btn-ghost" title="Share" data-testid="viewer-share">
          <span class="i-lucide-share text-base"></span>
        </button>
        {#if canEdit}
          <button onclick={() => openRenameModal(entryFromStore.name)} class="btn-ghost" data-testid="viewer-rename">Rename</button>
          {#if isTextFile && !isHtml}
            <button
              onclick={enterEditMode}
              class="btn-ghost"
              disabled={loading || fileContent === null}
              data-testid="viewer-edit"
            >
              Edit
            </button>
          {/if}
          <button onclick={handleDelete} class="btn-ghost text-danger" data-testid="viewer-delete">Delete</button>
        {/if}
        <!-- Prev/Next file navigation - mobile only -->
        {#if filesOnly.length > 1 && prevFile && nextFile}
          <button
            onclick={() => navigateToFile(prevFile.name)}
            class="btn-ghost lg:hidden"
            title={`Previous: ${prevFile.name}`}
          >
            <span class="i-lucide-chevron-left text-base"></span>
          </button>
          <button
            onclick={() => navigateToFile(nextFile.name)}
            class="btn-ghost lg:hidden"
            title={`Next: ${nextFile.name}`}
          >
            <span class="i-lucide-chevron-right text-base"></span>
          </button>
        {/if}
      </div>
    </div>

    <!-- Content -->
    {#if isVideo && entryFromStore?.cid}
      <VideoViewer cid={entryFromStore.cid} fileName={urlFileName} />
    {:else if isHtml && fileContent !== null}
      <HtmlViewer content={fileContent} fileName={urlFileName} />
    {:else if isImage && blobUrl}
      <!-- Image viewer -->
      <div class="flex-1 flex items-center justify-center overflow-auto bg-surface-0 p-4">
        <img
          src={blobUrl}
          alt={urlFileName}
          class="max-w-full max-h-full object-contain"
          data-testid="image-viewer"
        />
      </div>
    {:else if isAudio && blobUrl}
      <!-- Audio player -->
      <div class="flex-1 flex items-center justify-center p-4">
        <audio src={blobUrl} controls class="w-full max-w-md" />
      </div>
    {:else if isPdf && blobUrl}
      <!-- PDF viewer -->
      <iframe
        src={blobUrl}
        class="flex-1 w-full border-none"
        title={urlFileName}
      />
    {:else if isZip && fileData}
      <!-- ZIP preview -->
      <ZipPreview data={fileData} filename={urlFileName} onDownload={handleDownload} />
    {:else if isDos && currentDirCid}
      <!-- DOS executable - show DOSBox viewer -->
      <DosBox directoryCid={currentDirCid} exeName={urlFileName} />
    {:else}
      <div class="flex-1 overflow-auto p-4">
        {#if showLoading}
          <p class="text-muted animate-fade-in" data-testid="loading-indicator">Loading...</p>
        {:else if fileContent !== null}
          <pre class="text-sm text-text-1 font-mono whitespace-pre-wrap break-words">{fileContent}</pre>
        {:else if !loading && entryFromStore}
          <!-- Binary/unsupported format fallback - show download pane -->
          <!-- svelte-ignore a11y_click_events_have_key_events -->
          <!-- svelte-ignore a11y_no_static_element_interactions -->
          <div class="w-full h-full p-3">
            <div
              class="w-full h-full flex flex-col items-center justify-center text-accent cursor-pointer hover:bg-accent/10 transition-colors border border-accent/50 rounded-lg"
              onclick={handleDownload}
            >
              <span class="i-lucide-download text-4xl mb-2"></span>
              <span class="text-sm mb-1">{urlFileName}</span>
              {#if entryFromStore.size}
                <span class="text-xs text-text-2">{formatBytes(entryFromStore.size)}</span>
              {/if}
            </div>
          </div>
        {/if}
      </div>
    {/if}
  </div>
{:else if hasTreeContext && isYjsDocument && currentDirCid}
  <!-- Yjs Document view - show Tiptap editor -->
  <YjsDocumentEditor
    dirCid={currentDirCid}
    dirName={currentDirName}
    entries={entries}
  />
{:else if hasTreeContext}
  <!-- Directory view - show DirectoryActions -->
  <div class="flex-1 flex flex-col min-h-0 bg-surface-0">
    <DirectoryActions />
  </div>
{:else}
  <!-- No content view -->
  <div class="flex-1 flex items-center justify-center bg-surface-0 text-muted">
    <span>Select a file to view</span>
  </div>
{/if}

<!-- Fullscreen overlay -->
{#if isFullscreen && entryFromStore}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div
    class="fixed inset-0 z-50 bg-black flex items-center justify-center"
    onclick={() => isFullscreen = false}
    onkeydown={(e) => { if (e.key === 'Escape') isFullscreen = false; }}
  >
    <button
      onclick={() => isFullscreen = false}
      class="absolute top-4 right-4 btn-ghost text-white z-10"
      title="Close fullscreen"
    >
      <span class="i-lucide-x text-2xl"></span>
    </button>
    {#if isImage && blobUrl}
      <img
        src={blobUrl}
        alt={urlFileName}
        class="max-w-full max-h-full object-contain"
        onclick={(e) => e.stopPropagation()}
      />
    {:else if isVideo && entryFromStore?.cid}
      <div class="w-full h-full" onclick={(e) => e.stopPropagation()}>
        <VideoViewer cid={entryFromStore.cid} fileName={urlFileName || ''} />
      </div>
    {:else if fileContent !== null}
      <pre
        class="max-w-full max-h-full overflow-auto p-8 text-white font-mono text-sm whitespace-pre-wrap"
        onclick={(e) => e.stopPropagation()}
      >{fileContent}</pre>
    {/if}
  </div>
{/if}
