// packages/hashtree-web/src/components/modals/CollaboratorsModal.tsx
/**
 * CollaboratorsModal - manage collaborator npubs for Yjs documents
 * Features:
 * - UserRow display for collaborators
 * - QR scanner for adding npubs
 * - Fuse.js search through followed users
 * - Read-only mode for viewers
 */
import { useState, useEffect, useMemo } from 'react';
import { nip19 } from 'nostr-tools';
import Fuse from 'fuse.js';
import { useModals, closeCollaboratorsModal } from '../../hooks/useModals';
import { useNostrStore } from '../../nostr';
import { useFollows, useSocialGraph } from '../../utils/socialGraph';
import { useProfile, getProfileName } from '../../hooks/useProfile';
import { UserRow } from '../user/UserRow';
import { QRScanner } from '../QRScanner';

interface SearchResult {
  pubkey: string;
  npub: string;
  name?: string;
  nip05?: string;
}

/** Extract npub from a scanned QR code text */
function extractNpubFromScan(text: string): string | null {
  // Trim and clean up text
  const cleaned = text.trim();

  // Direct npub match
  if (cleaned.startsWith('npub1') && cleaned.length === 63) {
    return cleaned;
  }

  // Try to find npub in the text (e.g., nostr:npub1...)
  const npubMatch = cleaned.match(/npub1[a-z0-9]{58}/i);
  if (npubMatch) {
    return npubMatch[0].toLowerCase();
  }

  // Try to decode hex pubkey
  if (/^[a-f0-9]{64}$/i.test(cleaned)) {
    try {
      return nip19.npubEncode(cleaned);
    } catch {
      return null;
    }
  }

  return null;
}

/** Convert npub to hex pubkey */
function npubToHex(npub: string): string | null {
  try {
    const decoded = nip19.decode(npub);
    if (decoded.type === 'npub') {
      return decoded.data as string;
    }
  } catch {
    // ignore
  }
  return null;
}

/** Preview component for a user about to be added */
function UserPreview({ npub, onConfirm, onCancel }: { npub: string; onConfirm: () => void; onCancel: () => void }) {
  const pubkey = npubToHex(npub);
  const profile = useProfile(pubkey || undefined);
  const name = getProfileName(profile, pubkey || undefined);

  return (
    <div className="bg-surface-2 rounded p-3 space-y-3">
      <div className="flex items-center gap-3">
        {pubkey ? (
          <UserRow pubkey={pubkey} avatarSize={40} />
        ) : (
          <span className="text-muted text-sm">Invalid npub</span>
        )}
      </div>
      <div className="flex gap-2">
        <button onClick={onCancel} className="btn-ghost flex-1 text-sm">
          Cancel
        </button>
        <button
          onClick={onConfirm}
          className="btn-success flex-1 text-sm"
          disabled={!pubkey}
        >
          Add {name ? name : 'User'}
        </button>
      </div>
    </div>
  );
}

export function CollaboratorsModal() {
  const { showCollaboratorsModal, collaboratorsTarget } = useModals();
  const [npubs, setNpubs] = useState<string[]>([]);
  const [newNpub, setNewNpub] = useState('');
  const [pendingNpub, setPendingNpub] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showQRScanner, setShowQRScanner] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [showSearchResults, setShowSearchResults] = useState(false);

  const userPubkey = useNostrStore(s => s.pubkey);
  const follows = useFollows(userPubkey);
  const socialGraph = useSocialGraph();

  // Read-only mode if no onSave callback
  const isReadOnly = !collaboratorsTarget?.onSave;

  // Build fuse.js search index from followed users
  const fuseIndex = useMemo(() => {
    if (!follows || follows.size === 0) return null;

    const searchItems: SearchResult[] = [];
    for (const pubkey of follows) {
      try {
        const npub = nip19.npubEncode(pubkey);
        // We'll search by pubkey and npub - names will be added as they load
        searchItems.push({
          pubkey,
          npub,
          name: undefined,
          nip05: undefined,
        });
      } catch {
        // Skip invalid pubkeys
      }
    }

    return new Fuse(searchItems, {
      keys: ['name', 'nip05', 'npub', 'pubkey'],
      includeScore: true,
      threshold: 0.4,
    });
  }, [follows]);

  // Search results
  const searchResults = useMemo(() => {
    if (!fuseIndex || !searchQuery.trim()) return [];

    const results = fuseIndex.search(searchQuery.trim(), { limit: 6 });
    // Filter out already added npubs
    return results
      .map(r => r.item)
      .filter(item => !npubs.includes(item.npub));
  }, [fuseIndex, searchQuery, npubs]);

  // Initialize state when modal opens
  useEffect(() => {
    if (showCollaboratorsModal && collaboratorsTarget) {
      setNpubs([...collaboratorsTarget.npubs]);
      setNewNpub('');
      setPendingNpub(null);
      setError(null);
      setSearchQuery('');
      setShowSearchResults(false);
    }
  }, [showCollaboratorsModal, collaboratorsTarget]);

  // Handle Escape key to close modal
  useEffect(() => {
    if (!showCollaboratorsModal) return;

    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        if (showQRScanner) {
          setShowQRScanner(false);
        } else if (pendingNpub) {
          setPendingNpub(null);
        } else {
          (document.activeElement as HTMLElement)?.blur();
          closeCollaboratorsModal();
        }
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [showCollaboratorsModal, showQRScanner, pendingNpub]);

  if (!showCollaboratorsModal || !collaboratorsTarget) return null;

  const validateNpub = (input: string): string | null => {
    const trimmed = input.trim();
    if (!trimmed) return null;

    // Validate npub format
    if (!trimmed.startsWith('npub1') || trimmed.length !== 63) {
      return null;
    }

    // Check for duplicates
    if (npubs.includes(trimmed)) {
      return null;
    }

    return trimmed;
  };

  const validateAndPrepareAdd = (input: string): string | null => {
    const trimmed = input.trim();
    if (!trimmed) return null;

    // Validate npub format
    if (!trimmed.startsWith('npub1') || trimmed.length !== 63) {
      setError('Invalid npub format. Must start with npub1 and be 63 characters.');
      return null;
    }

    // Check for duplicates
    if (npubs.includes(trimmed)) {
      setError('This npub is already in the list.');
      return null;
    }

    return trimmed;
  };

  // Auto-detect valid npub as user types
  const detectedNpub = useMemo(() => {
    if (pendingNpub) return null; // Don't detect if we already have a pending one
    return validateNpub(newNpub);
  }, [newNpub, npubs, pendingNpub]);

  const handlePrepareAdd = () => {
    const validated = validateAndPrepareAdd(newNpub);
    if (validated) {
      setPendingNpub(validated);
      setNewNpub('');
      setError(null);
      setShowSearchResults(false);
    }
  };

  const handleConfirmAdd = () => {
    if (pendingNpub) {
      setNpubs([...npubs, pendingNpub]);
      setPendingNpub(null);
    }
  };

  const handleRemove = (index: number) => {
    setNpubs(npubs.filter((_, i) => i !== index));
  };

  const handleSave = () => {
    if (isReadOnly) return;
    collaboratorsTarget.onSave?.(npubs);
    closeCollaboratorsModal();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      e.preventDefault();
      handlePrepareAdd();
    }
  };

  const handleQRScan = (result: string) => {
    const npub = extractNpubFromScan(result);
    setShowQRScanner(false);

    if (npub) {
      if (npubs.includes(npub)) {
        setError('This npub is already in the list.');
        return;
      }
      setPendingNpub(npub);
      setError(null);
    } else {
      setError('Could not find an npub in the scanned QR code.');
    }
  };

  const handleSearchSelect = (result: SearchResult) => {
    if (npubs.includes(result.npub)) {
      setError('This npub is already in the list.');
      return;
    }
    setPendingNpub(result.npub);
    setSearchQuery('');
    setShowSearchResults(false);
    setError(null);
  };

  return (
    <>
      <div
        className="fixed inset-0 bg-black/70 flex-center z-1000 overflow-auto"
        onClick={(e) => {
          if (e.target === e.currentTarget) closeCollaboratorsModal();
        }}
      >
        <div className="bg-surface-1 rounded-lg w-full max-w-md border border-surface-3 mx-4">
          {/* Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-surface-3">
            <h2 className="text-lg font-semibold">
              {isReadOnly ? 'Editors' : 'Manage Editors'}
            </h2>
            <button
              onClick={closeCollaboratorsModal}
              className="btn-ghost p-1"
              aria-label="Close"
            >
              <span className="i-lucide-x text-lg" />
            </button>
          </div>

          {/* Body */}
          <div className="p-4 space-y-4">
            <p className="text-sm text-muted">
              {isReadOnly
                ? 'Users who can edit this document. Their changes will be merged.'
                : 'Add editors by their npub to merge their edits into this document.'}
            </p>

            {/* Current collaborators list */}
            {npubs.length > 0 && (
              <div className="space-y-2">
                <label className="text-sm font-medium">Current editors:</label>
                <ul className="space-y-1">
                  {npubs.map((npub, index) => {
                    const pubkey = npubToHex(npub);
                    return (
                      <li key={index} className="flex items-center gap-2 bg-surface-2 rounded px-3 py-2">
                        {pubkey ? (
                          <UserRow pubkey={pubkey} avatarSize={32} className="flex-1 min-w-0" />
                        ) : (
                          <>
                            <span className="i-lucide-user text-muted" />
                            <span className="flex-1 text-sm font-mono truncate">{npub}</span>
                          </>
                        )}
                        {!isReadOnly && (
                          <button
                            onClick={() => handleRemove(index)}
                            className="btn-ghost p-1 text-danger shrink-0"
                            title="Remove editor"
                          >
                            <span className="i-lucide-x" />
                          </button>
                        )}
                      </li>
                    );
                  })}
                </ul>
              </div>
            )}

            {npubs.length === 0 && (
              <div className="text-sm text-muted bg-surface-2 rounded px-3 py-2">
                No editors yet.{!isReadOnly && ' Add one below.'}
              </div>
            )}

            {/* Pending user preview (from QR scan or search) */}
            {pendingNpub && !isReadOnly && (
              <div className="space-y-2">
                <label className="text-sm font-medium">Add this editor?</label>
                <UserPreview
                  npub={pendingNpub}
                  onConfirm={handleConfirmAdd}
                  onCancel={() => setPendingNpub(null)}
                />
              </div>
            )}

            {/* Auto-detected npub preview (from typing) */}
            {detectedNpub && !pendingNpub && !isReadOnly && (
              <div className="space-y-2">
                <label className="text-sm font-medium">Add this editor?</label>
                <UserPreview
                  npub={detectedNpub}
                  onConfirm={() => {
                    setNpubs([...npubs, detectedNpub]);
                    setNewNpub('');
                    setError(null);
                  }}
                  onCancel={() => setNewNpub('')}
                />
              </div>
            )}

            {/* Add new collaborator (only if not read-only and no pending) */}
            {!isReadOnly && !pendingNpub && (
              <div className="space-y-2">
                <label className="text-sm font-medium">Add editor:</label>

                {/* Search through follows */}
                {follows.size > 0 && (
                  <div className="relative">
                    <div className="flex gap-2">
                      <div className="relative flex-1">
                        <span className="i-lucide-search absolute left-3 top-1/2 -translate-y-1/2 text-muted text-sm" />
                        <input
                          type="text"
                          value={searchQuery}
                          onChange={(e) => {
                            setSearchQuery(e.target.value);
                            setShowSearchResults(true);
                            setError(null);
                          }}
                          onFocus={() => setShowSearchResults(true)}
                          placeholder="Search followed users..."
                          className="input w-full pl-9 text-sm"
                        />
                      </div>
                    </div>

                    {/* Search results dropdown */}
                    {showSearchResults && searchResults.length > 0 && (
                      <div className="absolute top-full left-0 right-0 mt-1 bg-surface-2 rounded border border-surface-3 shadow-lg z-10 max-h-48 overflow-auto">
                        {searchResults.map((result) => (
                          <button
                            key={result.pubkey}
                            onClick={() => handleSearchSelect(result)}
                            className="w-full px-3 py-2 hover:bg-surface-3 text-left"
                          >
                            <UserRow pubkey={result.pubkey} avatarSize={28} />
                          </button>
                        ))}
                      </div>
                    )}
                  </div>
                )}

                {/* Divider or label */}
                {follows.size > 0 && (
                  <div className="flex items-center gap-2 text-xs text-muted">
                    <span className="flex-1 h-px bg-surface-3" />
                    <span>or paste npub</span>
                    <span className="flex-1 h-px bg-surface-3" />
                  </div>
                )}

                {/* Manual npub input */}
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={newNpub}
                    onChange={(e) => {
                      setNewNpub(e.target.value);
                      setError(null);
                    }}
                    onKeyDown={handleKeyDown}
                    placeholder="npub1..."
                    className="input flex-1 font-mono text-sm"
                  />
                  <button
                    onClick={() => setShowQRScanner(true)}
                    className="btn-ghost px-2"
                    title="Scan QR code"
                  >
                    <span className="i-lucide-qr-code text-lg" />
                  </button>
                  <button
                    onClick={handlePrepareAdd}
                    className="btn-success px-3"
                    disabled={!newNpub.trim()}
                  >
                    Add
                  </button>
                </div>
                {error && (
                  <p className="text-sm text-danger">{error}</p>
                )}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex justify-end gap-2 px-4 py-3 border-t border-surface-3">
            <button onClick={closeCollaboratorsModal} className="btn-ghost">
              {isReadOnly ? 'Close' : 'Cancel'}
            </button>
            {!isReadOnly && (
              <button onClick={handleSave} className="btn-success">
                Save
              </button>
            )}
          </div>
        </div>
      </div>

      {/* QR Scanner overlay */}
      {showQRScanner && (
        <QRScanner
          onScanSuccess={handleQRScan}
          onClose={() => setShowQRScanner(false)}
        />
      )}
    </>
  );
}

// packages/hashtree-web/src/components/Modals/CollaboratorsModal.svelte
<script lang="ts">
  /**
   * Modal for managing document collaborators/editors
   * Features:
   * - UserRow display for collaborators
   * - Auto-save on add/remove (like React version)
   * - QR Scanner for adding npubs
   * - Search through followed users with Fuse.js
   */
  import { modalsStore, closeCollaboratorsModal } from '../../stores/modals';
  import { nip19 } from 'nostr-tools';
  import Fuse from 'fuse.js';
  import { UserRow } from '../User';
  import { npubToPubkey, useNostrStore } from '../../nostr';
  import { createFollowsStore } from '../../stores/follows';
  import QRScanner from '../QRScanner.svelte';

  let show = $derived($modalsStore.showCollaboratorsModal);
  let target = $derived($modalsStore.collaboratorsTarget);

  // Local state for editing
  let localNpubs = $state<string[]>([]);
  let newNpubInput = $state('');
  let addError = $state<string | null>(null);
  let pendingNpub = $state<string | null>(null);
  let showQRScanner = $state(false);
  let searchQuery = $state('');
  let showSearchResults = $state(false);

  // Get current user's pubkey for follows lookup
  let nostrState = $derived(useNostrStore.getState());
  let userPubkey = $derived(nostrState.pubkey);

  // Get followed users
  let followsStore = $derived(createFollowsStore(userPubkey));
  let follows = $state<string[]>([]);

  $effect(() => {
    if (!followsStore) {
      follows = [];
      return;
    }
    const unsub = followsStore.subscribe(value => {
      follows = value?.follows || [];
    });
    return () => {
      unsub();
      followsStore.destroy();
    };
  });

  // Build fuse.js search index from followed users
  interface SearchResult {
    pubkey: string;
    npub: string;
  }

  let fuseIndex = $derived.by(() => {
    if (follows.length === 0) return null;

    const searchItems: SearchResult[] = [];
    for (const pubkey of follows) {
      try {
        const npub = nip19.npubEncode(pubkey);
        searchItems.push({ pubkey, npub });
      } catch {
        // Skip invalid pubkeys
      }
    }

    return new Fuse(searchItems, {
      keys: ['npub', 'pubkey'],
      includeScore: true,
      threshold: 0.4,
    });
  });

  // Search results
  let searchResults = $derived.by(() => {
    if (!fuseIndex || !searchQuery.trim()) return [];

    const results = fuseIndex.search(searchQuery.trim(), { limit: 6 });
    // Filter out already added npubs
    return results
      .map(r => r.item)
      .filter(item => !localNpubs.includes(item.npub));
  });

  // Sync local state when modal opens
  $effect(() => {
    if (show && target) {
      localNpubs = [...target.npubs];
      newNpubInput = '';
      addError = null;
      pendingNpub = null;
      showQRScanner = false;
      searchQuery = '';
      showSearchResults = false;
    }
  });

  // Check if we can edit (has onSave callback)
  let canEdit = $derived(!!target?.onSave);

  // Validate npub format
  function validateNpub(npub: string): { valid: boolean; error?: string } {
    if (!npub.trim()) {
      return { valid: false, error: 'Please enter an npub' };
    }

    if (!npub.startsWith('npub1') || npub.length !== 63) {
      return { valid: false, error: 'Invalid npub format. Must start with npub1 and be 63 characters.' };
    }

    try {
      const decoded = nip19.decode(npub);
      if (decoded.type !== 'npub') {
        return { valid: false, error: 'Invalid npub format' };
      }
      return { valid: true };
    } catch {
      return { valid: false, error: 'Invalid npub' };
    }
  }

  /** Extract npub from a scanned QR code text */
  function extractNpubFromScan(text: string): string | null {
    const cleaned = text.trim();

    // Direct npub match
    if (cleaned.startsWith('npub1') && cleaned.length === 63) {
      return cleaned;
    }

    // Try to find npub in the text (e.g., nostr:npub1...)
    const npubMatch = cleaned.match(/npub1[a-z0-9]{58}/i);
    if (npubMatch) {
      return npubMatch[0].toLowerCase();
    }

    // Try to decode hex pubkey
    if (/^[a-f0-9]{64}$/i.test(cleaned)) {
      try {
        return nip19.npubEncode(cleaned);
      } catch {
        return null;
      }
    }

    return null;
  }

  // Auto-detect valid npub as user types
  let detectedNpub = $derived.by(() => {
    if (pendingNpub) return null;
    const trimmed = newNpubInput.trim();
    if (!trimmed) return null;
    if (!trimmed.startsWith('npub1') || trimmed.length !== 63) return null;
    if (localNpubs.includes(trimmed)) return null;
    return trimmed;
  });

  function handlePrepareAdd() {
    const npub = newNpubInput.trim();
    const validation = validateNpub(npub);

    if (!validation.valid) {
      addError = validation.error || 'Invalid npub';
      return;
    }

    if (localNpubs.includes(npub)) {
      addError = 'This npub is already in the list.';
      return;
    }

    pendingNpub = npub;
    newNpubInput = '';
    addError = null;
    showSearchResults = false;
  }

  function handleConfirmAdd() {
    if (!pendingNpub || !target?.onSave) return;

    const newNpubs = [...localNpubs, pendingNpub];
    localNpubs = newNpubs;
    pendingNpub = null;
    // Auto-save immediately
    target.onSave(newNpubs);
  }

  function handleRemoveEditor(index: number) {
    const newNpubs = localNpubs.filter((_, i) => i !== index);
    localNpubs = newNpubs;
    // Auto-save immediately on remove
    if (target?.onSave) {
      target.onSave(newNpubs);
    }
  }

  function handleQRScan(result: string) {
    const npub = extractNpubFromScan(result);
    showQRScanner = false;

    if (npub) {
      if (localNpubs.includes(npub)) {
        addError = 'This npub is already in the list.';
        return;
      }
      pendingNpub = npub;
      addError = null;
    } else {
      addError = 'Could not find an npub in the scanned QR code.';
    }
  }

  function handleSearchSelect(result: SearchResult) {
    if (localNpubs.includes(result.npub)) {
      addError = 'This npub is already in the list.';
      return;
    }
    pendingNpub = result.npub;
    searchQuery = '';
    showSearchResults = false;
    addError = null;
  }

  function handleClose() {
    closeCollaboratorsModal();
  }

  // Handle ESC key
  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      e.preventDefault();
      if (showQRScanner) {
        showQRScanner = false;
      } else if (pendingNpub) {
        pendingNpub = null;
      } else {
        handleClose();
      }
    }
  }

  $effect(() => {
    if (show) {
      document.addEventListener('keydown', handleKeyDown);
      return () => document.removeEventListener('keydown', handleKeyDown);
    }
  });
</script>

{#if show && target}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/70" onclick={handleClose} data-modal-backdrop>
    <div class="bg-surface-1 rounded-lg shadow-lg w-full max-w-md mx-4 border border-surface-3" onclick={(e) => e.stopPropagation()}>
      <!-- Header -->
      <div class="flex items-center justify-between px-4 py-3 b-b-1 b-b-solid b-b-surface-3">
        <h2 class="text-lg font-semibold">
          {canEdit ? 'Manage Editors' : 'Editors'}
        </h2>
        <button onclick={handleClose} class="btn-ghost p-1" aria-label="Close">
          <span class="i-lucide-x text-lg"></span>
        </button>
      </div>

      <!-- Content -->
      <div class="p-4 space-y-4">
        <p class="text-sm text-text-3">
          {canEdit
            ? 'Add editors by their npub to merge their edits into this document.'
            : 'Users who can edit this document. Their changes will be merged.'}
        </p>

        <!-- Current editors list -->
        {#if localNpubs.length > 0}
          <div class="space-y-2">
            <label class="text-sm font-medium">Current editors:</label>
            <ul class="space-y-1 list-none m-0 p-0">
              {#each localNpubs as npub, index}
                {@const pubkey = npubToPubkey(npub)}
                <li class="flex items-center gap-2 bg-surface-2 rounded px-3 py-2">
                  {#if pubkey}
                    <UserRow {pubkey} avatarSize={32} class="flex-1 min-w-0" />
                  {:else}
                    <span class="i-lucide-user text-text-3"></span>
                    <span class="flex-1 text-sm font-mono truncate">{npub}</span>
                  {/if}
                  {#if canEdit}
                    <button
                      onclick={() => handleRemoveEditor(index)}
                      class="btn-ghost p-1 text-danger shrink-0"
                      title="Remove editor"
                    >
                      <span class="i-lucide-x"></span>
                    </button>
                  {/if}
                </li>
              {/each}
            </ul>
          </div>
        {:else}
          <div class="text-sm text-text-3 bg-surface-2 rounded px-3 py-2">
            No editors yet.{#if canEdit} Add one below.{/if}
          </div>
        {/if}

        <!-- Pending user preview -->
        {#if pendingNpub && canEdit}
          {@const pendingPubkey = npubToPubkey(pendingNpub)}
          <div class="space-y-2">
            <label class="text-sm font-medium">Add this editor?</label>
            <div class="bg-surface-2 rounded p-3 space-y-3">
              <div class="flex items-center gap-3">
                {#if pendingPubkey}
                  <UserRow pubkey={pendingPubkey} avatarSize={40} />
                {:else}
                  <span class="text-text-3 text-sm">Invalid npub</span>
                {/if}
              </div>
              <div class="flex gap-2">
                <button onclick={() => pendingNpub = null} class="btn-ghost flex-1 text-sm">
                  Cancel
                </button>
                <button
                  onclick={handleConfirmAdd}
                  class="btn-success flex-1 text-sm"
                  disabled={!pendingPubkey}
                >
                  Add User
                </button>
              </div>
            </div>
          </div>
        {/if}

        <!-- Auto-detected npub preview -->
        {#if detectedNpub && !pendingNpub && canEdit}
          {@const detectedPubkey = npubToPubkey(detectedNpub)}
          <div class="space-y-2">
            <label class="text-sm font-medium">Add this editor?</label>
            <div class="bg-surface-2 rounded p-3 space-y-3">
              <div class="flex items-center gap-3">
                {#if detectedPubkey}
                  <UserRow pubkey={detectedPubkey} avatarSize={40} />
                {:else}
                  <span class="text-text-3 text-sm">Invalid npub</span>
                {/if}
              </div>
              <div class="flex gap-2">
                <button onclick={() => newNpubInput = ''} class="btn-ghost flex-1 text-sm">
                  Cancel
                </button>
                <button
                  onclick={() => {
                    if (!detectedNpub || !target?.onSave) return;
                    const newNpubs = [...localNpubs, detectedNpub];
                    localNpubs = newNpubs;
                    newNpubInput = '';
                    addError = null;
                    target.onSave(newNpubs);
                  }}
                  class="btn-success flex-1 text-sm"
                  disabled={!detectedPubkey}
                >
                  Add User
                </button>
              </div>
            </div>
          </div>
        {/if}

        <!-- Add new editor (only if can edit and no pending) -->
        {#if canEdit && !pendingNpub}
          <div class="space-y-2">
            <label class="text-sm font-medium">Add editor:</label>

            <!-- Search through follows -->
            {#if follows.length > 0}
              <div class="relative">
                <div class="flex gap-2">
                  <div class="relative flex-1">
                    <span class="i-lucide-search absolute left-3 top-1/2 -translate-y-1/2 text-text-3 text-sm"></span>
                    <input
                      type="text"
                      bind:value={searchQuery}
                      oninput={() => {
                        showSearchResults = true;
                        addError = null;
                      }}
                      onfocus={() => showSearchResults = true}
                      placeholder="Search followed users..."
                      class="input w-full pl-9 text-sm"
                    />
                  </div>
                </div>

                <!-- Search results dropdown -->
                {#if showSearchResults && searchResults.length > 0}
                  <div class="absolute top-full left-0 right-0 mt-1 bg-surface-2 rounded border border-surface-3 shadow-lg z-10 max-h-48 overflow-auto">
                    {#each searchResults as result}
                      <button
                        onclick={() => handleSearchSelect(result)}
                        class="w-full px-3 py-2 hover:bg-surface-3 text-left"
                      >
                        <UserRow pubkey={result.pubkey} avatarSize={28} />
                      </button>
                    {/each}
                  </div>
                {/if}
              </div>
            {/if}

            <!-- Divider or label -->
            {#if follows.length > 0}
              <div class="flex items-center gap-2 text-xs text-text-3">
                <span class="flex-1 h-px bg-surface-3"></span>
                <span>or paste npub</span>
                <span class="flex-1 h-px bg-surface-3"></span>
              </div>
            {/if}

            <!-- Manual npub input - hide when detectedNpub shows UserPreview -->
            {#if !detectedNpub}
              <div class="flex gap-2">
                <input
                  type="text"
                  bind:value={newNpubInput}
                  placeholder="npub1..."
                  class="input flex-1 font-mono text-sm"
                  onkeydown={(e) => e.key === 'Enter' && handlePrepareAdd()}
                />
                <button
                  onclick={() => showQRScanner = true}
                  class="btn-ghost px-2"
                  title="Scan QR code"
                >
                  <span class="i-lucide-qr-code text-lg"></span>
                </button>
                <button
                  onclick={handlePrepareAdd}
                  class="btn-success px-3"
                  disabled={!newNpubInput.trim()}
                >
                  Add
                </button>
              </div>
            {/if}
            {#if addError}
              <p class="text-sm text-danger">{addError}</p>
            {/if}
          </div>
        {/if}
      </div>

      <!-- Footer -->
      <div class="flex justify-end gap-2 px-4 py-3 b-t-1 b-t-solid b-t-surface-3">
        <button onclick={handleClose} class="btn-ghost">
          Close
        </button>
      </div>
    </div>
  </div>

  <!-- QR Scanner overlay -->
  {#if showQRScanner}
    <QRScanner
      onScanSuccess={handleQRScan}
      onClose={() => showQRScanner = false}
    />
  {/if}
{/if}
