// packages/iris-files/src/components/Modals/UnsavedChangesModal.svelte
<script lang="ts">
  /**
   * Modal for confirming unsaved changes before closing editor
   */
  import {
    showUnsavedChangesModal,
    unsavedChangesTarget,
    closeUnsavedChangesModal,
  } from '../../stores/modals/other';

  let show = $derived($showUnsavedChangesModal);
  let target = $derived($unsavedChangesTarget);

  let saving = $state(false);

  async function handleSave() {
    if (!target) return;
    saving = true;
    try {
      await target.onSave();
    } finally {
      saving = false;
      closeUnsavedChangesModal();
    }
  }

  function handleDiscard() {
    if (!target) return;
    target.onDiscard();
    closeUnsavedChangesModal();
  }

  function handleCancel() {
    closeUnsavedChangesModal();
  }

  // Handle ESC key
  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      e.preventDefault();
      e.stopPropagation();
      handleCancel();
    }
  }

  $effect(() => {
    if (show) {
      document.addEventListener('keydown', handleKeyDown);
      return () => document.removeEventListener('keydown', handleKeyDown);
    }
  });
</script>

{#if show && target}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onclick={handleCancel} data-modal-backdrop>
    <div class="bg-surface-1 rounded-lg shadow-lg p-6 w-full max-w-md mx-4" onclick={(e) => e.stopPropagation()}>
      <h2 class="text-lg font-semibold mb-2">Unsaved Changes</h2>
      <p class="text-text-2 mb-4">
        {#if target.fileName}
          <strong>{target.fileName}</strong> has unsaved changes.
        {:else}
          You have unsaved changes.
        {/if}
        What would you like to do?
      </p>
      <div class="flex justify-end gap-2">
        <button onclick={handleCancel} class="btn-ghost">
          Cancel
        </button>
        <button onclick={handleDiscard} class="btn-ghost text-error">
          Don't Save
        </button>
        <button onclick={handleSave} disabled={saving} class="btn-success">
          {saving ? 'Saving...' : 'Save'}
        </button>
      </div>
    </div>
  </div>
{/if}

// packages/hashtree-web/src/components/modals/UnsavedChangesModal.tsx
/**
 * UnsavedChangesModal - confirm save/discard when closing editor with unsaved changes
 */
import { useState } from 'react';
import { useModals, closeUnsavedChangesModal } from '../../hooks/useModals';
import { ModalBase } from './ModalBase';

export function UnsavedChangesModal() {
  const { showUnsavedChangesModal, unsavedChangesTarget } = useModals();
  const [isSaving, setIsSaving] = useState(false);

  if (!showUnsavedChangesModal || !unsavedChangesTarget) return null;

  const { onSave, onDiscard, fileName } = unsavedChangesTarget;

  const handleSave = async () => {
    setIsSaving(true);
    try {
      await onSave();
      closeUnsavedChangesModal();
    } finally {
      setIsSaving(false);
    }
  };

  const handleDiscard = () => {
    onDiscard();
    closeUnsavedChangesModal();
  };

  return (
    <ModalBase title="Unsaved Changes" onClose={closeUnsavedChangesModal}>
      <p className="text-sm text-text-2 mb-4">
        {fileName ? (
          <>Do you want to save changes to <span className="font-medium text-text-1">{fileName}</span>?</>
        ) : (
          'Do you want to save your changes?'
        )}
      </p>

      <div className="flex justify-end gap-2">
        <button
          onClick={closeUnsavedChangesModal}
          className="btn-ghost"
        >
          Cancel
        </button>
        <button
          onClick={handleDiscard}
          className="btn-ghost text-danger"
        >
          Don't Save
        </button>
        <button
          onClick={handleSave}
          className="btn-success"
          disabled={isSaving}
        >
          {isSaving ? 'Saving...' : 'Save'}
        </button>
      </div>
    </ModalBase>
  );
}
