// packages/iris-files/src/components/ConnectivityIndicator.svelte
<script lang="ts">
  /**
   * Simplified connectivity indicator - network icon with count
   * Red: not connected, Yellow: relays only, Green: peers, Blue: follows peers
   * Shows "offline" text when browser is offline
   * Clicking navigates to settings
   */
  import { appStore } from '../store';
  import { nostrStore } from '../nostr';

  let peerCount = $derived($appStore.peerCount);
  let peersList = $derived($appStore.peers);
  let connectedRelays = $derived($nostrStore.connectedRelays);
  let loggedIn = $derived($nostrStore.isLoggedIn);

  // Count peers in follows pool
  let followsPeers = $derived(peersList.filter(p => p.pool === 'follows' && p.state === 'connected').length);

  // Track browser online/offline status
  let isOnline = $state(typeof navigator !== 'undefined' ? navigator.onLine : true);

  $effect(() => {
    const handleOnline = () => { isOnline = true; };
    const handleOffline = () => { isOnline = false; };

    window.addEventListener('online', handleOnline);
    window.addEventListener('offline', handleOffline);

    return () => {
      window.removeEventListener('online', handleOnline);
      window.removeEventListener('offline', handleOffline);
    };
  });

  // Color logic: red = offline, yellow = relays only, green = peers, blue = follows peers
  let color = $derived.by(() => {
    if (!isOnline) return '#f85149'; // red when offline
    if (!loggedIn || connectedRelays === 0) return '#f85149'; // red
    if (peerCount === 0) return '#d29922'; // yellow
    if (followsPeers > 0) return '#58a6ff'; // blue - connected to follows
    return '#3fb950'; // green - connected to other peers
  });

  let title = $derived.by(() => {
    if (!isOnline) return 'Offline';
    if (!loggedIn) return 'Not connected';
    if (connectedRelays === 0) return 'No relays connected';
    if (peerCount === 0) return `${connectedRelays} relay${connectedRelays !== 1 ? 's' : ''}, no peers`;
    if (followsPeers > 0) {
      return `${followsPeers} follow${followsPeers !== 1 ? 's' : ''}, ${peerCount - followsPeers} other, ${connectedRelays} relay${connectedRelays !== 1 ? 's' : ''}`;
    }
    return `${peerCount} peer${peerCount !== 1 ? 's' : ''}, ${connectedRelays} relay${connectedRelays !== 1 ? 's' : ''}`;
  });

  // Total connections = relays + peers
  let totalConnections = $derived(connectedRelays + peerCount);
</script>

<a
  href="#/settings"
  class="flex flex-col items-center px-2 py-1 text-sm no-underline"
  {title}
>
  <div class="flex items-center gap-1.5">
    <span
      data-testid="peer-indicator-dot"
      class="i-lucide-wifi"
      style="color: {color}"
    ></span>
    <span data-testid="peer-count" style="color: {color}">{totalConnections}</span>
  </div>
  {#if !isOnline}
    <span class="text-[10px] text-danger -mt-0.5">offline</span>
  {/if}
</a>

// examples/explorer/src/components/ConnectivityIndicator.tsx
/**
 * Simplified connectivity indicator - network icon with count
 * Red: not connected, Yellow: relays only, Green: peers connected
 * Clicking navigates to settings
 */
import { Link } from 'react-router-dom';
import { useAppStore } from '../store';
import { useNostrStore } from '../nostr';

export function ConnectivityIndicator() {
  const peers = useAppStore(s => s.peerCount);
  const relayList = useNostrStore(s => s.relays);
  const loggedIn = useNostrStore(s => s.isLoggedIn);
  const relayCount = relayList.length;

  // Color logic: red = nothing, yellow = relays only, green = peers
  let color: string;
  let title: string;

  if (!loggedIn) {
    color = '#f85149'; // red
    title = 'Not connected';
  } else if (peers === 0) {
    color = '#d29922'; // yellow
    title = `${relayCount} relays, no peers`;
  } else {
    color = '#3fb950'; // green
    title = `${peers} peer${peers !== 1 ? 's' : ''}, ${relayCount} relays`;
  }

  // Total connections = relays + peers
  const totalConnections = relayCount + peers;

  return (
    <Link
      to="/settings"
      className="flex items-center gap-1.5 px-2 py-1 text-sm no-underline"
      title={title}
    >
      <span
        data-testid="peer-indicator-dot"
        className="i-lucide-wifi"
        style={{ color }}
      />
      <span data-testid="peer-count" style={{ color }}>{totalConnections}</span>
    </Link>
  );
}
