// packages/hashtree-web/src/components/ProfileView.svelte
<script lang="ts">
  /**
   * ProfileView - displays user profile
   * Port of React ProfileView component
   */
  import { nip19 } from 'nostr-tools';
  import { nostrStore } from '../nostr';
  import { createProfileStore } from '../stores/profile';
  import { createFollowsStore, followPubkey, unfollowPubkey } from '../stores/follows';
  import { openShareModal } from '../stores/modals';
  import { Avatar, Name, Badge, FollowedBy } from './User';
  import CopyText from './CopyText.svelte';
  import { getFollowsMe, getFollowers, socialGraphStore } from '../utils/socialGraph';

  interface Props {
    npub: string;
  }

  let { npub }: Props = $props();

  let myPubkey = $derived($nostrStore.pubkey);
  let isLoggedIn = $derived($nostrStore.isLoggedIn);

  // Decode npub to hex pubkey
  let pubkeyHex = $derived.by(() => {
    try {
      const decoded = nip19.decode(npub);
      return decoded.data as string;
    } catch {
      return '';
    }
  });

  let isOwnProfile = $derived(myPubkey === pubkeyHex);

  // Profile store
  let profileStore = $derived(createProfileStore(npub));
  let profile = $state<{ name?: string; display_name?: string; about?: string; banner?: string; picture?: string; nip05?: string; website?: string } | null>(null);

  $effect(() => {
    const store = profileStore;
    const unsub = store.subscribe(value => {
      profile = value;
    });
    return unsub;
  });

  // Follows store for my follows (to check if I'm following this user)
  let myFollowsStore = $derived(myPubkey ? createFollowsStore(myPubkey) : null);
  let myFollows = $state<string[]>([]);

  $effect(() => {
    if (!myFollowsStore) {
      myFollows = [];
      return;
    }
    const unsub = myFollowsStore.subscribe(value => {
      myFollows = value?.follows || [];
    });
    return () => {
      unsub();
      myFollowsStore?.destroy();
    };
  });

  // Follows store for the viewed profile (to show their following count)
  let profileFollowsStore = $derived(pubkeyHex ? createFollowsStore(pubkeyHex) : null);
  let profileFollows = $state<string[]>([]);

  $effect(() => {
    if (!profileFollowsStore) {
      profileFollows = [];
      return;
    }
    const unsub = profileFollowsStore.subscribe(value => {
      profileFollows = value?.follows || [];
    });
    return () => {
      unsub();
      profileFollowsStore?.destroy();
    };
  });

  // Social graph reactive state (subscribe to version changes)
  let graphVersion = $derived($socialGraphStore.version);

  // Follow state - recompute when graph changes
  let isFollowing = $derived.by(() => {
    graphVersion; // Subscribe to changes
    return myFollows.includes(pubkeyHex);
  });

  let followsMe = $derived.by(() => {
    graphVersion; // Subscribe to changes
    return getFollowsMe(pubkeyHex);
  });

  let knownFollowers = $derived.by(() => {
    graphVersion; // Subscribe to changes
    return getFollowers(pubkeyHex);
  });

  let bannerError = $state(false);
  let followLoading = $state(false);

  function navigate(path: string) {
    window.location.hash = path;
  }

  async function handleFollow() {
    followLoading = true;
    if (isFollowing) {
      await unfollowPubkey(pubkeyHex);
    } else {
      await followPubkey(pubkeyHex);
    }
    followLoading = false;
  }
</script>

<div class="flex-1 flex flex-col min-h-0 bg-surface-0 overflow-y-auto">
  <!-- Banner -->
  <div class="h-32 md:h-40 bg-surface-2 relative shrink-0">
    {#if profile?.banner && !bannerError}
      <img
        src={profile.banner}
        alt=""
        class="w-full h-full object-cover"
        onerror={() => bannerError = true}
      />
    {/if}
  </div>

  <!-- Profile header -->
  <div class="px-4 pb-4 -mt-12 relative">
    <!-- Avatar -->
    <div class="mb-3">
      <Avatar pubkey={pubkeyHex} size={80} class="border-4 border-surface-0" />
    </div>

    <!-- Name and action buttons -->
    <div class="flex items-center justify-between gap-2">
      <div class="flex items-center gap-2 min-w-0">
        <h1 class="text-xl font-bold text-text-1 m-0 truncate">
          <Name pubkey={pubkeyHex} />
        </h1>
        {#if isOwnProfile}
          <span class="shrink-0 text-xs text-blue-500 flex items-center gap-1">
            <Badge pubKeyHex={pubkeyHex} size="sm" /> You
          </span>
        {:else if isFollowing}
          <span class="shrink-0 text-xs text-blue-500 flex items-center gap-1">
            <Badge pubKeyHex={pubkeyHex} size="sm" /> Following
          </span>
        {/if}
        {#if !isOwnProfile && followsMe}
          <span class="shrink-0 text-xs bg-surface-2 text-text-2 px-2 py-0.5 rounded">
            Follows you
          </span>
        {/if}
      </div>
      <div class="flex items-center gap-2 shrink-0">
        {#if isLoggedIn && isOwnProfile}
          <button
            onclick={() => navigate('/users')}
            class="btn-ghost"
            title="Switch user"
          >
            Users
          </button>
          <button
            onclick={() => navigate(`/${npub}/edit`)}
            class="btn-ghost"
          >
            Edit Profile
          </button>
        {/if}
        {#if isLoggedIn && !isOwnProfile}
          <button
            onclick={handleFollow}
            disabled={followLoading}
            class={isFollowing ? 'btn-ghost' : 'btn-success'}
          >
            {followLoading ? '...' : isFollowing ? 'Unfollow' : 'Follow'}
          </button>
        {/if}
        <button
          onclick={() => openShareModal(window.location.href)}
          class="btn-ghost"
          title="Share"
        >
          <span class="i-lucide-share text-base"></span>
        </button>
      </div>
    </div>

    <!-- npub with copy -->
    <CopyText
      text={npub}
      displayText={npub.slice(0, 8) + '...' + npub.slice(-4)}
      class="text-sm mt-1"
      testId="copy-npub"
    />

    {#if profile?.nip05}
      <div class="text-sm text-accent mt-1">{profile.nip05}</div>
    {/if}

    <!-- Followed by friends -->
    {#if !isOwnProfile && pubkeyHex}
      <FollowedBy pubkey={pubkeyHex} class="mt-2" />
    {/if}

    <!-- About -->
    {#if profile?.about}
      <p class="text-sm text-text-2 mt-3 whitespace-pre-wrap break-words">
        {profile.about}
      </p>
    {/if}

    <!-- Stats -->
    <div class="flex gap-4 mt-4 text-sm">
      <button
        onclick={() => navigate(`/${npub}/follows`)}
        class="bg-transparent border-none cursor-pointer p-0 text-text-2 hover:text-text-1"
      >
        <span class="font-bold text-text-1">{profileFollows.length || '...'}</span> Following
      </button>
      {#if knownFollowers.size > 0}
        <span class="text-text-2">
          <span class="font-bold text-text-1">{knownFollowers.size}</span> known followers
        </span>
      {/if}
    </div>

    <!-- Website -->
    {#if profile?.website}
      <a
        href={profile.website.startsWith('http') ? profile.website : `https://${profile.website}`}
        target="_blank"
        rel="noopener noreferrer"
        class="text-sm text-accent mt-3 inline-block hover:underline"
      >
        {profile.website}
      </a>
    {/if}
  </div>
</div>

// examples/explorer/src/components/ProfileView.tsx
import { useState } from 'react';
import { navigate } from '../utils/navigate';
import { useProfile } from '../hooks/useProfile';
import { useFollows, followPubkey, unfollowPubkey } from '../hooks/useFollows';
import { Avatar, Name } from './user';
import { nip19 } from 'nostr-tools';
import { useNostrStore } from '../nostr';

interface Props {
  npub: string;
}

export function ProfileView({ npub }: Props) {
  const myPubkeyVal = useNostrStore(s => s.pubkey);
  const isLoggedInVal = useNostrStore(s => s.isLoggedIn);

  const profile = useProfile(npub);
  const follows = useFollows(npub);
  const myFollows = useFollows(myPubkeyVal || undefined);
  const [bannerError, setBannerError] = useState(false);
  const [copied, setCopied] = useState(false);
  const [followLoading, setFollowLoading] = useState(false);

  const pubkeyHex = (() => {
    try {
      const decoded = nip19.decode(npub);
      return decoded.data as string;
    } catch {
      return '';
    }
  })();

  const isOwnProfile = myPubkeyVal === pubkeyHex;
  const isFollowing = myFollows?.follows.includes(pubkeyHex) ?? false;

  const copyUserId = async () => {
    await navigator.clipboard.writeText(npub);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleFollow = async () => {
    setFollowLoading(true);
    if (isFollowing) {
      await unfollowPubkey(pubkeyHex);
    } else {
      await followPubkey(pubkeyHex);
    }
    setFollowLoading(false);
  };

  const shortNpub = npub.slice(0, 10) + '...' + npub.slice(-4);

  return (
    <div className="flex-1 flex flex-col min-h-0 bg-surface-0 overflow-y-auto">
      {/* Banner */}
      <div className="h-32 md:h-40 bg-surface-2 relative shrink-0">
        {profile?.banner && !bannerError && (
          <img
            src={profile.banner}
            alt=""
            className="w-full h-full object-cover"
            onError={() => setBannerError(true)}
          />
        )}
      </div>

      {/* Profile header */}
      <div className="px-4 pb-4 -mt-12 relative">
        {/* Avatar */}
        <div className="mb-3">
          <Avatar pubkey={pubkeyHex} size={80} className="border-4 border-surface-0" />
        </div>

        {/* Name and action buttons */}
        <div className="flex items-center justify-between gap-2">
          <h1 className="text-xl font-bold text-text-1 m-0">
            <Name pubkey={pubkeyHex} />
          </h1>
          <div className="flex items-center gap-2">
            {isLoggedInVal && isOwnProfile && (
              <>
                <button
                  onClick={() => navigate('/accounts')}
                  className="btn-ghost"
                  title="Switch account"
                >
                  <span className="i-lucide-users" />
                </button>
                <button
                  onClick={() => navigate(`/${npub}/edit`)}
                  className="btn-ghost"
                >
                  Edit Profile
                </button>
              </>
            )}
            {isLoggedInVal && !isOwnProfile && (
              <button
                onClick={handleFollow}
                disabled={followLoading}
                className={isFollowing ? 'btn-ghost' : 'btn-success'}
              >
                {followLoading ? '...' : isFollowing ? 'Unfollow' : 'Follow'}
              </button>
            )}
          </div>
        </div>

        {/* npub with copy */}
        <button
          onClick={copyUserId}
          className="flex items-center gap-1 text-sm text-text-2 hover:text-text-1 bg-transparent border-none cursor-pointer p-0 mt-1"
          title="Copy user ID"
        >
          {copied ? (
            <span className="i-lucide-check text-success text-xs" />
          ) : (
            <span className="i-lucide-copy text-xs" />
          )}
          <span className="font-mono">{shortNpub}</span>
        </button>

        {profile?.nip05 && (
          <div className="text-sm text-accent mt-1">{profile.nip05}</div>
        )}

        {/* About */}
        {profile?.about && (
          <p className="text-sm text-text-2 mt-3 whitespace-pre-wrap break-words">
            {profile.about}
          </p>
        )}

        {/* Stats */}
        <div className="flex gap-4 mt-4 text-sm">
          <button
            onClick={() => navigate(`/${npub}/follows`)}
            className="bg-transparent border-none cursor-pointer p-0 text-text-2 hover:text-text-1"
          >
            <span className="font-bold text-text-1">{follows?.follows.length ?? '...'}</span> Following
          </button>
        </div>

        {/* Website */}
        {profile?.website && (
          <a
            href={profile.website.startsWith('http') ? profile.website : `https://${profile.website}`}
            target="_blank"
            rel="noopener noreferrer"
            className="text-sm text-accent mt-3 inline-block hover:underline"
          >
            {profile.website}
          </a>
        )}
      </div>

      {/* Follows list preview */}
      <div className="border-t border-surface-3 px-4 py-3">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-sm font-semibold text-text-1 m-0">Following</h2>
          {follows && follows.follows.length > 5 && (
            <button
              onClick={() => navigate(`/${npub}/follows`)}
              className="text-xs text-accent bg-transparent border-none cursor-pointer hover:underline"
            >
              View all
            </button>
          )}
        </div>

        {!follows ? (
          <div className="text-sm text-text-2">Loading...</div>
        ) : follows.follows.length === 0 ? (
          <div className="text-sm text-text-2">Not following anyone</div>
        ) : (
          <div className="flex flex-col gap-2">
            {follows.follows.slice(0, 5).map(pk => (
              <FollowRow key={pk} pubkey={pk} />
            ))}
          </div>
        )}
      </div>

    </div>
  );
}

function FollowRow({ pubkey }: { pubkey: string }) {
  const profile = useProfile(pubkey);
  const npubStr = nip19.npubEncode(pubkey);

  return (
    <button
      onClick={() => navigate(`/${npubStr}`)}
      className="flex items-center gap-3 p-2 rounded hover:bg-surface-2 bg-transparent border-none cursor-pointer text-left w-full"
    >
      <Avatar pubkey={pubkey} size={36} />
      <div className="flex-1 min-w-0">
        <div className="text-sm font-medium text-text-1 truncate">
          <Name pubkey={pubkey} />
        </div>
        {profile?.nip05 && (
          <div className="text-xs text-text-2 truncate">{profile.nip05}</div>
        )}
      </div>
    </button>
  );
}
