// packages/hashtree-web/src/components/modals/ExtractModal.tsx
/**
 * Modal for extracting archive files (ZIP, etc.)
 */
import { useState } from 'react';
import { useModals, closeExtractModal, setExtractLocation } from '../../hooks/useModals';
import { uploadExtractedFiles, uploadSingleFile } from '../../actions';
import { ModalBase, FileList, formatBytes } from './ModalBase';

export function ExtractModal() {
  const { showExtractModal, extractTarget, extractLocation } = useModals();
  const [isExtracting, setIsExtracting] = useState(false);
  const [isKeeping, setIsKeeping] = useState(false);

  if (!showExtractModal || !extractTarget) return null;

  const { archiveName, files, originalData } = extractTarget;
  const totalSize = files.reduce((sum, f) => sum + f.size, 0);

  // Get subdirectory name from archive (remove .zip extension)
  const subdirName = archiveName.replace(/\.zip$/i, '');

  const handleExtract = async () => {
    setIsExtracting(true);
    try {
      await uploadExtractedFiles(files, extractLocation === 'subdir' ? subdirName : undefined);
      closeExtractModal();
    } catch (err) {
      console.error('Failed to extract files:', err);
      alert('Failed to extract archive');
    } finally {
      setIsExtracting(false);
    }
  };

  const handleKeepAsZip = async () => {
    if (!originalData) {
      closeExtractModal();
      return;
    }

    setIsKeeping(true);
    try {
      await uploadSingleFile(archiveName, originalData);
      closeExtractModal();
    } catch (err) {
      console.error('Failed to upload ZIP:', err);
      alert('Failed to upload archive');
    } finally {
      setIsKeeping(false);
    }
  };

  const isBusy = isExtracting || isKeeping;

  return (
    <ModalBase title="Extract Archive?" onClose={closeExtractModal}>
      <div className="mb-4">
        <p className="text-text-2 mb-2">
          <strong>{archiveName}</strong> contains {files.length} file{files.length !== 1 ? 's' : ''} ({formatBytes(totalSize)})
        </p>
        <FileList files={files} formatSize={formatBytes} />
      </div>

      {/* Extraction location picker */}
      <div className="mb-4">
        <label className="text-sm text-text-2 mb-2 block">Extract to:</label>
        <div className="flex gap-2">
          {([
            { value: 'current', label: 'Current folder', icon: 'i-lucide-folder' },
            { value: 'subdir', label: subdirName, icon: 'i-lucide-folder-plus' },
          ] as const).map(({ value, label, icon }) => {
            const isSelected = extractLocation === value;
            return (
              <button
                key={value}
                onClick={() => setExtractLocation(value)}
                disabled={isBusy}
                className={`flex-1 flex items-center justify-center gap-2 py-2 px-3 rounded border ${
                  isSelected
                    ? 'border-accent bg-accent/10 text-accent'
                    : 'border-surface-3 text-text-1 hover:border-surface-4 hover:bg-surface-2'
                }`}
              >
                <span className={icon} />
                <span className="text-sm truncate">{label}</span>
              </button>
            );
          })}
        </div>
      </div>

      <div className="flex gap-2">
        <button onClick={handleKeepAsZip} className="btn-ghost" disabled={isBusy}>
          {isKeeping ? (
            <>
              <span className="i-lucide-loader-2 animate-spin mr-1" />
              Uploading...
            </>
          ) : (
            'Keep as ZIP'
          )}
        </button>
        <button onClick={handleExtract} className="btn-success" disabled={isBusy}>
          {isExtracting ? (
            <>
              <span className="i-lucide-loader-2 animate-spin mr-1" />
              Extracting...
            </>
          ) : (
            <>
              <span className="i-lucide-archive mr-1" />
              Extract Files
            </>
          )}
        </button>
      </div>
    </ModalBase>
  );
}

// packages/iris-files/src/components/Modals/ExtractModal.svelte
<script lang="ts">
  /**
   * Modal for extracting archive files (ZIP)
   * Shows options to extract to current directory, subdirectory, or keep as ZIP
   */
  import { modalsStore, closeExtractModal, setExtractLocation } from '../../stores/modals';
  import type { ExtractLocation } from '../../stores/modals';
  import { uploadSingleFile, uploadExtractedFiles } from '../../actions/file';
  import { formatBytes } from '../../store';

  let show = $derived($modalsStore.showExtractModal);
  let target = $derived($modalsStore.extractTarget);
  let location = $derived($modalsStore.extractLocation);

  let isProcessing = $state(false);

  // Get archive name without extension for subdirectory suggestion
  let suggestedSubdir = $derived.by(() => {
    if (!target?.archiveName) return '';
    const name = target.archiveName;
    const dotIndex = name.lastIndexOf('.');
    return dotIndex > 0 ? name.substring(0, dotIndex) : name;
  });

  // Total size of extracted files
  let totalSize = $derived.by(() => {
    if (!target?.files) return 0;
    return target.files.reduce((sum, f) => sum + f.size, 0);
  });

  async function handleExtract() {
    if (!target || isProcessing) return;
    isProcessing = true;

    try {
      const subdirName = location === 'subdir' ? suggestedSubdir : undefined;
      await uploadExtractedFiles(target.files, subdirName);
      closeExtractModal();
    } catch (e) {
      console.error('Failed to extract files:', e);
    } finally {
      isProcessing = false;
    }
  }

  async function handleKeepAsZip() {
    if (!target?.originalData || isProcessing) return;
    isProcessing = true;

    try {
      await uploadSingleFile(target.archiveName, target.originalData);
      closeExtractModal();
    } catch (e) {
      console.error('Failed to upload ZIP:', e);
    } finally {
      isProcessing = false;
    }
  }

  function handleCancel() {
    closeExtractModal();
  }

  function handleLocationChange(loc: ExtractLocation) {
    setExtractLocation(loc);
  }
</script>

{#if show && target}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/70" onclick={handleCancel}>
    <div
      class="bg-surface-1 rounded-lg shadow-lg p-6 w-full max-w-md mx-4 max-h-[80vh] flex flex-col"
      onclick={(e) => e.stopPropagation()}
    >
      <h2 class="text-lg font-semibold mb-2">Extract Archive?</h2>
      <p class="text-text-2 mb-4">
        <span class="font-medium text-text-1">{target.archiveName}</span> contains {target.files.length} file{target.files.length !== 1 ? 's' : ''} ({formatBytes(totalSize)})
      </p>

      <!-- File list preview -->
      <div class="mb-4 max-h-32 overflow-y-auto bg-surface-0 rounded border border-surface-3 p-2">
        <ul class="text-sm text-text-2 space-y-0.5">
          {#each target.files.slice(0, 10) as file (file.name)}
            <li class="flex items-center gap-2">
              <span class="i-lucide-file text-xs shrink-0"></span>
              <span class="truncate flex-1">{file.name}</span>
              <span class="text-text-3 text-xs shrink-0">{formatBytes(file.size)}</span>
            </li>
          {/each}
          {#if target.files.length > 10}
            <li class="text-text-3 text-xs">...and {target.files.length - 10} more</li>
          {/if}
        </ul>
      </div>

      <!-- Location options -->
      <div class="mb-4 space-y-2">
        <label class="flex items-center gap-2 cursor-pointer">
          <input
            type="radio"
            name="extract-location"
            checked={location === 'subdir'}
            onchange={() => handleLocationChange('subdir')}
            class="accent-accent"
          />
          <span class="text-sm">Extract to folder: <span class="font-medium text-text-1">{suggestedSubdir}/</span></span>
        </label>
        <label class="flex items-center gap-2 cursor-pointer">
          <input
            type="radio"
            name="extract-location"
            checked={location === 'current'}
            onchange={() => handleLocationChange('current')}
            class="accent-accent"
          />
          <span class="text-sm">Extract to current directory</span>
        </label>
      </div>

      <!-- Action buttons -->
      <div class="flex justify-end gap-2 mt-auto">
        <button onclick={handleCancel} class="btn-ghost" disabled={isProcessing}>
          Cancel
        </button>
        {#if target.originalData}
          <button onclick={handleKeepAsZip} class="btn-ghost" disabled={isProcessing}>
            Keep as ZIP
          </button>
        {/if}
        <button onclick={handleExtract} class="btn-success" disabled={isProcessing}>
          {isProcessing ? 'Extracting...' : 'Extract Files'}
        </button>
      </div>
    </div>
  </div>
{/if}
