// packages/hashtree-web/src/components/modals/GitHistoryModal.tsx
/**
 * GitHistoryModal - shows commit history for a git repository
 */
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { toHex, nhashEncode } from 'hashtree';
import { useModals, closeGitHistoryModal } from '../../hooks/useModals';
import { useGitLog } from '../../hooks/useGit';
import { checkoutCommit } from '../../utils/git';
import { autosaveIfOwn } from '../../nostr';

function formatDate(timestamp: number): string {
  const date = new Date(timestamp * 1000);
  return date.toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

function formatTime(timestamp: number): string {
  const date = new Date(timestamp * 1000);
  return date.toLocaleTimeString(undefined, {
    hour: '2-digit',
    minute: '2-digit',
  });
}

export function GitHistoryModal() {
  const { showGitHistoryModal, gitHistoryTarget } = useModals();
  const { commits, loading, error } = useGitLog(gitHistoryTarget?.dirCid ?? null);
  const [checkoutInProgress, setCheckoutInProgress] = useState<string | null>(null);
  const [checkoutError, setCheckoutError] = useState<string | null>(null);
  const navigate = useNavigate();

  const handleCheckout = async (commitSha: string) => {
    if (!gitHistoryTarget) return;

    setCheckoutInProgress(commitSha);
    setCheckoutError(null);

    try {
      const newCid = await checkoutCommit(gitHistoryTarget.dirCid, commitSha);
      // Save the new tree to nostr if this is the user's own tree
      autosaveIfOwn(newCid);
      // Navigate to the new tree
      const nhash = nhashEncode({
        hash: toHex(newCid.hash),
        decryptKey: newCid.key ? toHex(newCid.key) : undefined
      });
      navigate(`/${nhash}`);
      closeGitHistoryModal();
    } catch (err) {
      setCheckoutError(err instanceof Error ? err.message : 'Checkout failed');
      setCheckoutInProgress(null);
    }
  };

  if (!showGitHistoryModal || !gitHistoryTarget) return null;

  return (
    <div
      className="fixed inset-0 bg-black/50 flex items-center justify-center z-50"
      onClick={(e) => {
        if (e.target === e.currentTarget) closeGitHistoryModal();
      }}
    >
      <div className="bg-surface-1 rounded-lg shadow-xl w-full max-w-2xl max-h-[80vh] flex flex-col m-4">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-surface-3">
          <div className="flex items-center gap-2">
            <span className="i-lucide-history text-accent" />
            <h2 className="text-lg font-medium text-text-1">Commit History</h2>
          </div>
          <button
            onClick={closeGitHistoryModal}
            className="text-text-3 hover:text-text-1 transition-colors"
          >
            <span className="i-lucide-x text-xl" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-4">
          {loading && (
            <div className="flex items-center justify-center py-8">
              <span className="i-lucide-loader-2 animate-spin text-2xl text-accent" />
            </div>
          )}

          {error && (
            <div className="text-danger text-sm p-4 bg-danger/10 rounded">
              {error}
            </div>
          )}

          {checkoutError && (
            <div className="text-danger text-sm p-4 bg-danger/10 rounded mb-3">
              {checkoutError}
            </div>
          )}

          {!loading && !error && commits.length === 0 && (
            <div className="text-text-3 text-center py-8">
              No commits found
            </div>
          )}

          {!loading && !error && commits.length > 0 && (
            <div className="space-y-3">
              {commits.map((commit) => (
                <div
                  key={commit.oid}
                  className="relative pl-6 pb-3 border-l-2 border-surface-3 last:border-transparent"
                >
                  {/* Timeline dot */}
                  <div className="absolute left-[-5px] top-1 w-2 h-2 rounded-full bg-accent" />

                  {/* Commit content */}
                  <div className="bg-surface-2 rounded-lg p-3">
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        {/* Message */}
                        <div className="text-text-1 text-sm font-medium mb-2 whitespace-pre-wrap">
                          {commit.message.trim()}
                        </div>

                        {/* Meta info */}
                        <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-text-3">
                          <span className="font-mono text-accent" title={commit.oid}>
                            {commit.oid.slice(0, 7)}
                          </span>
                          <span>{commit.author}</span>
                          <span>{formatDate(commit.timestamp)} {formatTime(commit.timestamp)}</span>
                        </div>
                      </div>

                      {/* Checkout button */}
                      <button
                        onClick={() => handleCheckout(commit.oid)}
                        disabled={checkoutInProgress !== null}
                        className="btn-ghost px-2 py-1 text-xs flex items-center gap-1 shrink-0"
                        title="Restore this version"
                      >
                        {checkoutInProgress === commit.oid ? (
                          <>
                            <span className="i-lucide-loader-2 animate-spin" />
                            <span>Restoring...</span>
                          </>
                        ) : (
                          <>
                            <span className="i-lucide-history" />
                            <span>Restore</span>
                          </>
                        )}
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-surface-3">
          <button
            onClick={closeGitHistoryModal}
            className="btn-ghost px-4 py-2"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}

// packages/iris-files/src/components/Modals/GitHistoryModal.svelte
<script lang="ts">
  /**
   * Modal for displaying git commit history
   */
  import { modalsStore, closeGitHistoryModal } from '../../stores/modals';
  import { createGitLogStore, type CommitInfo } from '../../stores/git';
  import { nhashEncode } from 'hashtree';
  import { checkoutCommit, getBranches } from '../../utils/git';

  function bytesToHex(bytes: Uint8Array): string {
    return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
  }

  let show = $derived($modalsStore.showGitHistoryModal);
  let target = $derived($modalsStore.gitHistoryTarget);

  // Create git log store when modal opens
  let logStore = $derived(target ? createGitLogStore(target.dirCid, 100) : null);
  let logState = $state<{ commits: CommitInfo[]; headOid: string | null; loading: boolean; error: string | null }>({
    commits: [],
    headOid: null,
    loading: true,
    error: null,
  });

  // Branch info for detached HEAD detection
  let branchInfo = $state<{ branches: string[]; currentBranch: string | null }>({ branches: [], currentBranch: null });
  let isDetachedHead = $derived(branchInfo.currentBranch === null && logState.commits.length > 0);

  let checkoutInProgress = $state<string | null>(null);
  let checkoutError = $state<string | null>(null);

  $effect(() => {
    if (!logStore) {
      logState = { commits: [], headOid: null, loading: false, error: null };
      return;
    }
    const unsub = logStore.subscribe(value => {
      logState = value;
    });
    return unsub;
  });

  // Fetch branch info when modal opens
  $effect(() => {
    if (!target) {
      branchInfo = { branches: [], currentBranch: null };
      return;
    }
    getBranches(target.dirCid).then(info => {
      branchInfo = info;
    });
  });

  // Handle ESC key
  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      e.preventDefault();
      closeGitHistoryModal();
    }
  }

  $effect(() => {
    if (show) {
      document.addEventListener('keydown', handleKeyDown);
      return () => document.removeEventListener('keydown', handleKeyDown);
    }
  });

  // Format timestamp
  function formatDate(timestamp: number): string {
    const date = new Date(timestamp * 1000);
    const now = new Date();
    const diff = now.getTime() - date.getTime();
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));

    if (days === 0) {
      const hours = Math.floor(diff / (1000 * 60 * 60));
      if (hours === 0) {
        const mins = Math.floor(diff / (1000 * 60));
        return mins <= 1 ? 'just now' : `${mins} minutes ago`;
      }
      return hours === 1 ? '1 hour ago' : `${hours} hours ago`;
    }
    if (days === 1) return 'yesterday';
    if (days < 7) return `${days} days ago`;
    if (days < 30) return `${Math.floor(days / 7)} weeks ago`;
    if (days < 365) return `${Math.floor(days / 30)} months ago`;
    return `${Math.floor(days / 365)} years ago`;
  }

  // Get first line of commit message
  function getCommitTitle(message: string): string {
    return message.split('\n')[0].slice(0, 72);
  }

  // Get short commit hash
  function shortHash(oid: string): string {
    return oid.slice(0, 7);
  }

  // Handle checkout button click (for own repos)
  async function handleCheckout(commitSha: string) {
    if (!target || checkoutInProgress) return;

    checkoutInProgress = commitSha;
    checkoutError = null;

    try {
      if (target.onCheckout) {
        await target.onCheckout(commitSha);
        closeGitHistoryModal();
      }
    } catch (err) {
      checkoutError = err instanceof Error ? err.message : String(err);
    } finally {
      checkoutInProgress = null;
    }
  }

  // Handle checkout branch (for returning from detached HEAD)
  async function handleCheckoutBranch(branchName: string) {
    if (!target || checkoutInProgress) return;

    checkoutInProgress = branchName;
    checkoutError = null;

    try {
      if (target.onCheckout) {
        // Checkout branch by name (git will resolve to the branch's HEAD)
        await target.onCheckout(branchName);
        closeGitHistoryModal();
      }
    } catch (err) {
      checkoutError = err instanceof Error ? err.message : String(err);
    } finally {
      checkoutInProgress = null;
    }
  }

  // Handle browse button click (for others' repos)
  async function handleBrowse(commitSha: string) {
    if (!target) return;

    try {
      // Checkout to get the CID at that commit
      const newCid = await checkoutCommit(target.dirCid, commitSha);

      // Convert CID to nhash
      const hashHex = bytesToHex(newCid.hash);
      const keyHex = newCid.key ? bytesToHex(newCid.key) : undefined;
      const nhash = nhashEncode({ hash: hashHex, decryptKey: keyHex });

      // Open in new tab
      window.open(`#/${nhash}`, '_blank');
    } catch (err) {
      checkoutError = err instanceof Error ? err.message : String(err);
    }
  }
</script>

{#if show && target}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/50" onclick={closeGitHistoryModal}>
    <div class="bg-surface-1 rounded-lg shadow-lg w-full max-w-2xl mx-4 max-h-[80vh] flex flex-col" onclick={(e) => e.stopPropagation()}>
      <!-- Header -->
      <div class="flex items-center justify-between p-4 b-b-1 b-b-solid b-b-surface-3">
        <h2 class="text-lg font-semibold flex items-center gap-2">
          <span class="i-lucide-history"></span>
          Commit History
        </h2>
        <button onclick={closeGitHistoryModal} class="btn-ghost p-1">
          <span class="i-lucide-x text-lg"></span>
        </button>
      </div>

      <!-- Content -->
      <div class="flex-1 overflow-auto p-4">
        {#if logState.loading}
          <div class="flex items-center justify-center py-8 text-text-3">
            <span class="i-lucide-loader-2 animate-spin mr-2"></span>
            Loading commits...
          </div>
        {:else if logState.error}
          <div class="flex items-center justify-center py-8 text-error">
            <span class="i-lucide-alert-circle mr-2"></span>
            {logState.error}
          </div>
        {:else if logState.commits.length === 0}
          <div class="flex items-center justify-center py-8 text-text-3">
            No commits found
          </div>
        {:else}
          {#if checkoutError}
            <div class="mb-4 p-3 bg-error/10 text-error rounded-lg text-sm flex items-center gap-2">
              <span class="i-lucide-alert-circle"></span>
              {checkoutError}
            </div>
          {/if}
          {#if isDetachedHead && target?.canEdit && branchInfo.branches.length > 0}
            <div class="mb-4 p-3 bg-warning/10 text-warning rounded-lg text-sm">
              <div class="flex items-center gap-2 mb-2">
                <span class="i-lucide-alert-triangle"></span>
                <span class="font-medium">Detached HEAD</span>
              </div>
              <p class="text-text-2 text-xs mb-2">
                You're viewing an older commit. Switch to a branch to see all commits:
              </p>
              <div class="flex flex-wrap gap-2">
                {#each branchInfo.branches as branch (branch)}
                  <button
                    onclick={() => handleCheckoutBranch(branch)}
                    disabled={checkoutInProgress !== null}
                    class="btn-ghost px-2 py-1 text-xs flex items-center gap-1 bg-surface-2"
                  >
                    {#if checkoutInProgress === branch}
                      <span class="i-lucide-loader-2 animate-spin"></span>
                    {:else}
                      <span class="i-lucide-git-branch"></span>
                    {/if}
                    {branch}
                  </button>
                {/each}
              </div>
            </div>
          {/if}
          <div class="flex flex-col">
            {#each logState.commits as commit, i (commit.oid)}
              {@const isHead = commit.oid === logState.headOid}
              <div class="flex gap-3 pb-4 {i < logState.commits.length - 1 ? 'b-b-1 b-b-solid b-b-surface-3 mb-4' : ''} {isHead ? 'bg-accent/5 -mx-4 px-4 py-3 rounded-lg' : ''}">
                <!-- Timeline dot -->
                <div class="flex flex-col items-center shrink-0">
                  <div class="w-3 h-3 rounded-full {isHead ? 'bg-success ring-2 ring-success/30' : 'bg-accent'}"></div>
                  {#if i < logState.commits.length - 1}
                    <div class="w-0.5 flex-1 bg-surface-3 mt-1"></div>
                  {/if}
                </div>

                <!-- Commit info -->
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-2 mb-1">
                    <span class="font-medium text-text-1 truncate" title={commit.message}>
                      {getCommitTitle(commit.message)}
                    </span>
                    {#if isHead}
                      <span class="shrink-0 text-xs font-medium px-1.5 py-0.5 rounded bg-success/20 text-success flex items-center gap-1">
                        <span class="i-lucide-circle-dot text-[10px]"></span>
                        HEAD
                      </span>
                    {/if}
                  </div>
                  <div class="flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-text-3">
                    <span class="font-mono bg-surface-2 px-1.5 py-0.5 rounded text-xs">
                      {shortHash(commit.oid)}
                    </span>
                    <span class="flex items-center gap-1">
                      <span class="i-lucide-user text-xs"></span>
                      {commit.author}
                    </span>
                    <span class="flex items-center gap-1">
                      <span class="i-lucide-clock text-xs"></span>
                      {formatDate(commit.timestamp)}
                    </span>
                  </div>
                </div>

                <!-- Action button -->
                <div class="shrink-0">
                  {#if target.canEdit && target.onCheckout}
                    {#if isHead}
                      <span class="text-xs text-text-3 px-2 py-1">Current</span>
                    {:else}
                      <button
                        onclick={() => handleCheckout(commit.oid)}
                        disabled={checkoutInProgress !== null}
                        class="btn-ghost px-2 py-1 text-xs flex items-center gap-1"
                        title="Checkout this commit (replaces working directory)"
                      >
                        {#if checkoutInProgress === commit.oid}
                          <span class="i-lucide-loader-2 animate-spin"></span>
                        {:else}
                          <span class="i-lucide-git-branch-plus"></span>
                        {/if}
                        Checkout
                      </button>
                    {/if}
                  {:else}
                    <button
                      onclick={() => handleBrowse(commit.oid)}
                      class="btn-ghost px-2 py-1 text-xs flex items-center gap-1"
                      title="Browse files at this commit"
                    >
                      <span class="i-lucide-external-link"></span>
                      Browse
                    </button>
                  {/if}
                </div>
              </div>
            {/each}
          </div>
        {/if}
      </div>

      <!-- Footer -->
      <div class="flex justify-between items-center p-4 b-t-1 b-t-solid b-t-surface-3">
        <span class="text-sm text-text-3">
          {logState.commits.length} commit{logState.commits.length !== 1 ? 's' : ''}
        </span>
        <button onclick={closeGitHistoryModal} class="btn-ghost">Close</button>
      </div>
    </div>
  </div>
{/if}
