// packages/hashtree-web/src/components/UsersPage.tsx
import { useState } from 'react';
import { Link } from 'react-router-dom';
import { navigate } from '../utils/navigate';
import { Avatar, Name } from './user';
import { useNostrStore, loginWithNsec, loginWithExtension, generateNewKey } from '../nostr';
import {
  useAccountsStore,
  createAccountFromNsec,
  createExtensionAccount,
  hasExtensionAccount,
  hasNostrExtension,
  saveActiveAccountToStorage,
  type Account,
} from '../accounts';

export function UsersPage() {
  const myPubkey = useNostrStore(s => s.pubkey);
  const myNpub = useNostrStore(s => s.npub);
  const accounts = useAccountsStore(s => s.accounts);
  const addAccount = useAccountsStore(s => s.addAccount);
  const removeAccount = useAccountsStore(s => s.removeAccount);
  const setActiveAccount = useAccountsStore(s => s.setActiveAccount);

  const [showAddNsec, setShowAddNsec] = useState(false);
  const [nsecInput, setNsecInput] = useState('');
  const [error, setError] = useState('');
  const [switching, setSwitching] = useState<string | null>(null);

  const handleAddNsec = () => {
    setError('');
    const trimmed = nsecInput.trim();
    if (!trimmed) {
      setError('Please enter an nsec');
      return;
    }

    const account = createAccountFromNsec(trimmed);
    if (!account) {
      setError('Invalid nsec');
      return;
    }

    // Check if already exists
    if (accounts.some(a => a.pubkey === account.pubkey)) {
      setError('Account already added');
      return;
    }

    addAccount(account);
    setNsecInput('');
    setShowAddNsec(false);
  };

  const handleAddExtension = async () => {
    setError('');

    if (!hasNostrExtension()) {
      setError('No nostr extension found');
      return;
    }

    if (hasExtensionAccount()) {
      setError('Extension account already added');
      return;
    }

    try {
      // Get pubkey from extension
      const pubkey = await window.nostr!.getPublicKey();
      const account = createExtensionAccount(pubkey);

      // Check if already exists (as nsec account)
      if (accounts.some(a => a.pubkey === account.pubkey)) {
        setError('Account already added');
        return;
      }

      addAccount(account);
    } catch {
      setError('Failed to get pubkey from extension');
    }
  };

  const handleGenerateNew = () => {
    setError('');
    // generateNewKey creates a new keypair, sets it active, and adds to accounts store
    generateNewKey();
  };

  const handleSwitchAccount = async (account: Account) => {
    if (account.pubkey === myPubkey) return;

    setSwitching(account.pubkey);
    setError('');

    try {
      let success = false;

      if (account.type === 'extension') {
        success = await loginWithExtension();
      } else if (account.nsec) {
        success = loginWithNsec(account.nsec, false); // Don't save again, already in accounts
      }

      if (success) {
        setActiveAccount(account.pubkey);
        saveActiveAccountToStorage(account.pubkey);
      } else {
        setError('Failed to switch account');
      }
    } catch {
      setError('Failed to switch account');
    } finally {
      setSwitching(null);
    }
  };

  const handleRemoveAccount = (account: Account) => {
    if (accounts.length <= 1) {
      setError('Cannot remove the only account');
      return;
    }

    const removed = removeAccount(account.pubkey);
    if (!removed) {
      setError('Cannot remove the only account');
    } else if (account.pubkey === myPubkey && accounts.length > 1) {
      // If removing current account, switch to another
      const nextAccount = accounts.find(a => a.pubkey !== account.pubkey);
      if (nextAccount) {
        handleSwitchAccount(nextAccount);
      }
    }
  };

  const handleBack = () => {
    if (myNpub) {
      navigate(`/${myNpub}`);
    } else {
      navigate('/');
    }
  };

  const canShowExtensionOption = hasNostrExtension() && !hasExtensionAccount();

  return (
    <div className="flex-1 flex flex-col bg-surface-0 overflow-y-auto">
      {/* Header */}
      <div className="flex items-center gap-3 p-4 border-b border-surface-3">
        <button
          onClick={handleBack}
          className="btn-ghost p-2"
          title="Back"
        >
          <span className="i-lucide-arrow-left text-lg" />
        </button>
        <h1 className="text-xl font-bold text-text-1 m-0">Users</h1>
      </div>

      {/* Account List */}
      <div className="p-4">
        <div className="flex flex-col gap-2">
          {accounts.map(account => (
            <AccountRow
              key={account.pubkey}
              account={account}
              isActive={account.pubkey === myPubkey}
              isSwitching={switching === account.pubkey}
              canRemove={accounts.length > 1}
              onSwitch={() => handleSwitchAccount(account)}
              onRemove={() => handleRemoveAccount(account)}
            />
          ))}
        </div>

        {accounts.length === 0 && (
          <div className="text-center text-text-2 py-8">
            No accounts added yet
          </div>
        )}

        {/* Add Account */}
        {error && (
          <div className="text-danger text-sm mt-3">{error}</div>
        )}

        <div className="flex flex-col gap-2 mt-4">
          <button
            onClick={handleGenerateNew}
            className="btn-success"
          >
            Generate new
          </button>

          <div className="flex gap-2">
            {canShowExtensionOption && (
              <button
                onClick={handleAddExtension}
                className="btn-ghost flex-1"
              >
                Add from Extension
              </button>
            )}

            {!showAddNsec ? (
              <button
                onClick={() => setShowAddNsec(true)}
                className="btn-ghost flex-1"
              >
                Add with nsec
              </button>
            ) : (
            <div className="flex flex-col gap-2 flex-1">
              <input
                type="password"
                value={nsecInput}
                onChange={(e) => setNsecInput(e.target.value)}
                placeholder="nsec1..."
                className="input w-full"
                autoFocus
              />
              <div className="flex gap-2">
                <button
                  onClick={() => {
                    setShowAddNsec(false);
                    setNsecInput('');
                    setError('');
                  }}
                  className="btn-ghost flex-1"
                >
                  Cancel
                </button>
                <button
                  onClick={handleAddNsec}
                  className="btn-success flex-1"
                >
                  Add
                </button>
              </div>
            </div>
          )}
          </div>
        </div>
      </div>
    </div>
  );
}

interface AccountRowProps {
  account: Account;
  isActive: boolean;
  isSwitching: boolean;
  canRemove: boolean;
  onSwitch: () => void;
  onRemove: () => void;
}

function AccountRow({ account, isActive, isSwitching, canRemove, onSwitch, onRemove }: AccountRowProps) {
  const [showConfirmRemove, setShowConfirmRemove] = useState(false);

  return (
    <div className={`flex items-center gap-3 p-3 rounded-lg ${isActive ? 'bg-surface-2' : 'bg-surface-1 hover:bg-surface-2'}`}>
      <Link to={`/${account.npub}`} className="shrink-0">
        <Avatar pubkey={account.pubkey} size={40} />
      </Link>
      <button
        onClick={onSwitch}
        disabled={isActive || isSwitching}
        className="flex items-center gap-3 flex-1 min-w-0 bg-transparent border-none cursor-pointer p-0 text-left disabled:cursor-default"
      >
        <div className="flex-1 min-w-0">
          <div className="font-medium text-text-1 truncate">
            <Name pubkey={account.pubkey} />
          </div>
          {account.type === 'extension' && (
            <div className="text-xs text-text-2">Extension</div>
          )}
        </div>
      </button>

      <div className="flex items-center gap-2">
        {isSwitching && (
          <span className="i-lucide-loader-2 animate-spin text-text-2" />
        )}

        {isActive && (
          <span className="i-lucide-check-circle text-success" />
        )}


        {canRemove && !showConfirmRemove && (
          <button
            onClick={() => setShowConfirmRemove(true)}
            className="btn-ghost p-2 text-text-2 hover:text-danger"
            title="Remove account"
          >
            <span className="i-lucide-trash-2" />
          </button>
        )}

        {showConfirmRemove && (
          <div className="flex items-center gap-1">
            <button
              onClick={() => setShowConfirmRemove(false)}
              className="btn-ghost p-1 text-xs"
            >
              Cancel
            </button>
            <button
              onClick={() => {
                onRemove();
                setShowConfirmRemove(false);
              }}
              className="btn-ghost p-1 text-xs text-danger"
            >
              Remove
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// packages/iris-files/src/components/UsersPage.svelte
<script lang="ts">
  /**
   * UsersPage - manage saved accounts
   * Shows list of accounts, allows adding nsec accounts, switching between accounts, and removing accounts
   */
  import { navigate } from '../utils/navigate';
  import { accountsStore, createAccountFromNsec, saveActiveAccountToStorage, hasNostrExtension, type Account } from '../accounts';
  import { loginWithNsec, loginWithExtension, generateNewKey, restoreSession } from '../nostr';
  import { Avatar, Name } from './User';
  import { BackButton } from './ui';

  // State
  let showAddNsec = $state(false);
  let nsecInput = $state('');
  let nsecError = $state<string | null>(null);
  let confirmingRemove = $state<string | null>(null); // pubkey of account being removed
  let extensionError = $state<string | null>(null);

  // Store values
  let accountsState = $derived($accountsStore);
  let accounts = $derived(accountsState.accounts);
  let activeAccountPubkey = $derived(accountsState.activeAccountPubkey);
  let hasExtension = $derived(hasNostrExtension());

  // Sort accounts by creation time (oldest first)
  let sortedAccounts = $derived(
    [...accounts].sort((a, b) => a.addedAt - b.addedAt)
  );

  function handleAddNsec() {
    nsecError = null;
    const nsec = nsecInput.trim();

    if (!nsec || !nsec.startsWith('nsec1')) {
      nsecError = 'Invalid nsec';
      return;
    }

    // Check if already exists
    const account = createAccountFromNsec(nsec);
    if (!account) {
      nsecError = 'Invalid nsec';
      return;
    }

    if (accounts.some(a => a.pubkey === account.pubkey)) {
      nsecError = 'Account already added';
      return;
    }

    // Add the account
    accountsStore.addAccount(account);
    nsecInput = '';
    showAddNsec = false;
  }

  function cancelAddNsec() {
    showAddNsec = false;
    nsecInput = '';
    nsecError = null;
  }

  async function switchToAccount(account: Account) {
    if (account.pubkey === activeAccountPubkey) return;

    // Save as active
    saveActiveAccountToStorage(account.pubkey);
    accountsStore.setActiveAccount(account.pubkey);

    // Log in with this account
    if (account.type === 'nsec' && account.nsec) {
      await loginWithNsec(account.nsec);
    } else {
      // For extension accounts, re-initialize from storage
      await restoreSession();
    }
  }

  function startRemoveAccount(pubkey: string) {
    confirmingRemove = pubkey;
  }

  function cancelRemoveAccount() {
    confirmingRemove = null;
  }

  function confirmRemoveAccount(pubkey: string) {
    accountsStore.removeAccount(pubkey);
    confirmingRemove = null;
  }

  async function handleGenerateNew() {
    await generateNewKey();
  }

  async function handleExtensionLogin() {
    extensionError = null;
    const success = await loginWithExtension();
    if (success) {
      navigate('/');
    } else {
      extensionError = 'Extension login failed. Is a Nostr extension installed?';
    }
  }

</script>

<div class="flex-1 flex flex-col min-h-0 bg-surface-0 p-6 max-w-2xl mx-auto w-full">
  <!-- Header -->
  <div class="flex items-center gap-4 mb-6">
    <BackButton href="/" />
    <h1 class="text-xl font-semibold">Users</h1>
  </div>

  <!-- Account list -->
  <div class="space-y-3 mb-6">
    {#each sortedAccounts as account (account.pubkey)}
      {@const isActive = account.pubkey === activeAccountPubkey}
      {@const isConfirming = confirmingRemove === account.pubkey}
      <div
        class="rounded-lg p-4 flex items-center gap-3 cursor-pointer transition-colors {isActive ? 'bg-surface-2' : 'bg-surface-1 hover:bg-surface-2'}"
        onclick={() => !isConfirming && switchToAccount(account)}
        role="button"
        tabindex="0"
        onkeypress={(e) => e.key === 'Enter' && !isConfirming && switchToAccount(account)}
        data-testid="account-item"
      >
        <!-- Avatar -->
        <a
          href={`#/${account.npub}/profile`}
          class="shrink-0"
          onclick={(e) => e.stopPropagation()}
        >
          <Avatar pubkey={account.pubkey} size={40} />
        </a>

        <!-- Info -->
        <div class="flex-1 min-w-0">
          <div class="font-medium truncate">
            <Name pubkey={account.pubkey} />
          </div>
        </div>

        <!-- Active indicator or actions -->
        <div class="shrink-0 flex items-center gap-2">
          {#if isActive}
            <span class="i-lucide-check-circle text-success text-lg"></span>
          {/if}

          {#if accounts.length > 1}
            {#if isConfirming}
              <button
                onclick={(e) => { e.stopPropagation(); confirmRemoveAccount(account.pubkey); }}
                class="btn-danger text-sm"
              >
                Remove
              </button>
              <button
                onclick={(e) => { e.stopPropagation(); cancelRemoveAccount(); }}
                class="btn-ghost text-sm"
              >
                Cancel
              </button>
            {:else}
              <button
                onclick={(e) => { e.stopPropagation(); startRemoveAccount(account.pubkey); }}
                class="btn-ghost text-danger"
                title="Remove account"
              >
                <span class="i-lucide-trash-2"></span>
              </button>
            {/if}
          {/if}
        </div>
      </div>
    {/each}
  </div>

  <!-- Add account section -->
  <div class="space-y-2">
    <button onclick={handleGenerateNew} class="btn-success w-full justify-center" data-testid="generate-new-account">
      <span class="i-lucide-plus"></span>
      Generate New Account
    </button>

    {#if hasExtension}
      <button onclick={handleExtensionLogin} class="btn-ghost w-full justify-center border border-surface-3" data-testid="extension-login">
        <span class="i-lucide-puzzle"></span>
        Login with Extension
      </button>
      {#if extensionError}
        <p class="text-danger text-sm text-center">{extensionError}</p>
      {/if}
    {/if}

    {#if showAddNsec}
      <div class="bg-surface-1 rounded-lg p-4 space-y-3">
        <h3 class="font-medium">Add account with secret key</h3>
        <input
          type="password"
          bind:value={nsecInput}
          placeholder="nsec1..."
          class="input w-full"
          onkeypress={(e) => e.key === 'Enter' && handleAddNsec()}
        />
        {#if nsecError}
          <p class="text-danger text-sm">{nsecError}</p>
        {/if}
        <div class="flex gap-2">
          <button onclick={cancelAddNsec} class="btn-ghost">Cancel</button>
          <button onclick={handleAddNsec} class="btn-success">Add</button>
        </div>
      </div>
    {:else}
      <button onclick={() => showAddNsec = true} class="btn-ghost w-full justify-center text-text-3" data-testid="add-with-nsec">
        <span class="i-lucide-key"></span>
        Add with Secret Key
      </button>
    {/if}
  </div>
</div>
