// packages/hashtree-web/src/components/stream/StreamView.svelte
<script lang="ts">
  /**
   * StreamView - inline stream view renders in preview area
   * Port of React StreamView component
   */
  import { onDestroy } from 'svelte';
  import { formatBytes } from '../../store';
  import { nostrStore } from '../../nostr';
  import { routeStore, currentDirCidStore, directoryEntriesStore } from '../../hooks';
  import { openShareModal } from '../../hooks/useModals';
  import {
    streamStore,
    startPreview,
    stopPreview,
    startRecording,
    stopRecording,
    formatTime,
    setStreamFilename,
    setPersistStream,
  } from './useStream';

  let videoRef: HTMLVideoElement | undefined = $state();

  let route = $derived($routeStore);
  let selectedTree = $derived($nostrStore.selectedTree);
  let stream = $derived($streamStore);
  let currentDirCid = $derived($currentDirCidStore);
  let dirEntries = $derived($directoryEntriesStore);
  let entries = $derived(dirEntries.entries);

  // Build base URL for the current directory
  let basePath = $derived(
    route.npub && route.treeName
      ? `/${route.npub}/${route.treeName}${route.path.length ? '/' + route.path.join('/') : ''}`
      : '/'
  );

  // Get link key (prefer route, fallback to selectedTree)
  let linkKey = $derived(
    route.linkKey ?? (selectedTree?.visibility === 'unlisted' && selectedTree?.linkKey ? selectedTree.linkKey : null)
  );

  // Build close URL (remove stream param but keep linkKey)
  let closeUrl = $derived(linkKey ? `#${basePath}?k=${linkKey}` : `#${basePath}`);

  // Check if filename exists
  let filenameExists = $derived(entries.some(e => e.name === `${stream.streamFilename}.webm`));

  // Cleanup on destroy
  onDestroy(() => {
    if (videoRef) {
      stopPreview(videoRef);
    }
    stopRecording();
  });

  function handleClose() {
    if (!stream.isRecording) {
      if (videoRef) stopPreview(videoRef);
      window.location.hash = closeUrl;
    }
  }

  function handleStartRecording() {
    if (videoRef) {
      startRecording(videoRef);
      // Navigate to file URL when recording starts
      const fullFilename = `${stream.streamFilename}.webm`;
      const filePath = `${basePath}/${encodeURIComponent(fullFilename)}`;
      const params = [
        linkKey ? `k=${linkKey}` : '',
        'stream=1',
      ].filter(Boolean).join('&');
      window.location.hash = `#${filePath}?${params}`;
    }
  }

  function handleShare() {
    const viewerUrl = window.location.href
      .replace(/[&?]stream=1/, '')
      .replace(/\?$/, '');
    openShareModal(viewerUrl);
  }

  function handleFilenameChange(e: Event) {
    const input = e.target as HTMLInputElement;
    setStreamFilename(input.value.replace(/[^a-zA-Z0-9_-]/g, ''));
  }

  function handleCancelPreview() {
    if (videoRef) stopPreview(videoRef);
    handleClose();
  }
</script>

<div class="flex-1 flex flex-col min-h-0 bg-surface-0">
  <!-- Header -->
  <div class="shrink-0 px-3 py-2 border-b border-surface-3 flex items-center justify-between bg-surface-1">
    <div class="flex items-center gap-2 min-w-0">
      <span class="i-lucide-video text-text-2 shrink-0"></span>
      <span class="font-medium text-text-1 truncate">Livestream</span>
      {#if stream.isRecording}
        <span class="inline-flex items-center gap-1.5 text-danger text-sm shrink-0">
          <span class="w-2 h-2 bg-danger rounded-full animate-pulse"></span>
          REC {formatTime(stream.recordingTime)}
        </span>
      {/if}
    </div>
    <div class="flex items-center gap-1 shrink-0">
      <button onclick={handleShare} class="btn-ghost" title="Share">
        Share
      </button>
      {#if !stream.isRecording}
        <a href={closeUrl} class="btn-ghost no-underline">Back</a>
      {/if}
    </div>
  </div>

  <!-- Content -->
  <div class="flex-1 flex flex-col p-4 gap-4 overflow-auto">
    <video
      bind:this={videoRef}
      autoplay
      muted
      playsinline
      class="w-full aspect-video bg-surface-2 rounded"
    ></video>

    {#if stream.isRecording}
      <div class="flex items-center gap-4 text-sm text-muted">
        <span>{formatBytes(stream.streamStats.totalSize)}</span>
      </div>
    {/if}

    <!-- Stream Controls -->
    {#if !stream.isPreviewing && !stream.isRecording}
      <button
        onclick={() => videoRef && startPreview(videoRef)}
        class="p-3 btn-primary"
      >
        Start Camera
      </button>
    {:else if stream.isRecording}
      <button onclick={stopRecording} class="p-3 btn-success">
        <span class="i-lucide-square mr-2"></span>
        Stop Recording
      </button>
    {:else}
      <!-- Preview mode - show filename input and controls -->
      <div class="flex flex-col gap-3">
        <div class="flex gap-2 items-center">
          <div class="flex items-center flex-1">
            <input
              type="text"
              value={stream.streamFilename}
              oninput={handleFilenameChange}
              placeholder="filename"
              class="flex-1 p-3 bg-surface-0 border border-surface-3 rounded-l text-text-1"
            />
            <span class="p-3 bg-surface-2 border border-surface-3 border-l-0 rounded-r text-muted">
              .webm
            </span>
          </div>
        </div>

        {#if filenameExists}
          <div class="text-danger text-sm">
            Overwrites existing {stream.streamFilename}.webm
          </div>
        {/if}

        <!-- Storage mode toggle -->
        <div class="flex gap-2 text-sm">
          <button
            onclick={() => setPersistStream(true)}
            class="flex-1 p-2 rounded-sm cursor-pointer {stream.persistStream
              ? 'bg-success text-white border-none'
              : 'bg-surface-2 text-muted border border-surface-3'}"
          >
            Full Recording
          </button>
          <button
            onclick={() => setPersistStream(false)}
            class="flex-1 p-2 rounded-sm cursor-pointer {!stream.persistStream
              ? 'bg-accent text-white border-none'
              : 'bg-surface-2 text-muted border border-surface-3'}"
          >
            Live Only (30s)
          </button>
        </div>
        <div class="text-muted text-xs">
          {stream.persistStream
            ? 'Saves entire stream to file'
            : 'Keeps only last 30 seconds (for live viewing)'}
        </div>

        <div class="flex gap-2">
          <button
            onclick={handleStartRecording}
            class="flex-1 p-3 btn-danger"
          >
            <span class="i-lucide-circle mr-2"></span>
            Start Recording
          </button>
          <button
            onclick={handleCancelPreview}
            class="p-3 btn-ghost"
          >
            Cancel
          </button>
        </div>
      </div>
    {/if}
  </div>
</div>

// packages/hashtree-web/src/components/stream/StreamView.tsx
/**
 * Inline stream view - renders in preview area instead of modal
 */
import { useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { formatBytes } from '../../store';
import { useNostrStore } from '../../nostr';
import { useRoute, useCurrentDirCid, useDirectoryEntries } from '../../hooks';
import {
  startPreview,
  stopPreview,
  startRecording,
  stopRecording,
  formatTime,
  useStreamState,
  setStreamFilename,
  setPersistStream,
} from './useStream';
import { openShareModal } from '../../hooks/useModals';

export function StreamView() {
  const videoRef = useRef<HTMLVideoElement>(null);
  const navigate = useNavigate();
  const route = useRoute();
  const selectedTree = useNostrStore(s => s.selectedTree);
  const { isRecording, recordingTime, streamStats } = useStreamState();

  // Build base URL for the current directory
  const basePath = route.npub && route.treeName
    ? `/${route.npub}/${route.treeName}${route.path.length ? '/' + route.path.join('/') : ''}`
    : '/';

  // Get link key (prefer route, fallback to selectedTree)
  const linkKey = route.linkKey ?? (selectedTree?.visibility === 'unlisted' && 'linkKey' in selectedTree ? selectedTree.linkKey : null);

  // Build close URL (remove stream param but keep linkKey)
  const closeUrl = linkKey ? `${basePath}?k=${linkKey}` : basePath;

  useEffect(() => {
    return () => {
      stopPreview(videoRef.current);
      stopRecording();
    };
  }, []);

  const handleClose = () => {
    if (!isRecording) {
      stopPreview(videoRef.current);
      navigate(closeUrl);
    }
  };

  // When recording starts, navigate to the file URL (shareable link)
  const handleStartRecording = (filename: string) => {
    const fullFilename = `${filename}.webm`;
    const filePath = `${basePath}/${encodeURIComponent(fullFilename)}`;
    // Build query params: linkKey + stream=1
    const params = [
      linkKey ? `k=${linkKey}` : '',
      'stream=1',
    ].filter(Boolean).join('&');
    navigate(`${filePath}?${params}`, { replace: true });
  };

  // Get shareable viewer URL (current URL without ?stream=1)
  const getViewerUrl = () => {
    return window.location.href
      .replace(/[&?]stream=1/, '')
      .replace(/\?$/, '');
  };

  const handleShare = () => {
    const viewerUrl = getViewerUrl();
    openShareModal(viewerUrl);
  };

  return (
    <div className="flex-1 flex flex-col min-h-0 bg-surface-0">
      {/* Header */}
      <div className="h-10 shrink-0 px-3 border-b border-surface-3 flex items-center justify-between bg-surface-1">
        <span className="font-medium flex items-center gap-2">
          <span className="i-lucide-video text-accent" />
          Livestream
          {isRecording && (
            <span className="inline-flex items-center gap-1.5 text-danger text-sm">
              <span className="w-2 h-2 bg-danger rounded-full animate-pulse" />
              REC {formatTime(recordingTime)}
            </span>
          )}
        </span>
        <div className="flex items-center gap-1">
          {isRecording && (
            <button onClick={handleShare} className="btn-ghost" title="Share viewer link">
              <span className="i-lucide-share" />
            </button>
          )}
          {!isRecording && (
            <button onClick={handleClose} className="btn-ghost">
              <span className="i-lucide-x" />
            </button>
          )}
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 flex flex-col p-4 gap-4 overflow-auto">
        <video
          ref={videoRef}
          autoPlay
          muted
          playsInline
          className="w-full aspect-video bg-surface-2 rounded"
        />

        {isRecording && (
          <div className="flex items-center gap-4 text-sm text-muted">
            <span>{formatBytes(streamStats.totalSize)}</span>
          </div>
        )}

        <StreamControls videoRef={videoRef} onCancel={handleClose} onStartRecording={handleStartRecording} />
      </div>
    </div>
  );
}

function StreamControls({ videoRef, onCancel, onStartRecording }: {
  videoRef: { current: HTMLVideoElement | null };
  onCancel: () => void;
  onStartRecording: (filename: string) => void;
}) {
  const { isRecording, isPreviewing, streamFilename, persistStream } = useStreamState();
  const currentDirCid = useCurrentDirCid();
  const { entries } = useDirectoryEntries(currentDirCid);

  const filenameExists = entries.some(e => e.name === `${streamFilename}.webm`);

  if (!isPreviewing && !isRecording) {
    return (
      <button
        onClick={() => startPreview(videoRef.current)}
        className="p-3 btn-primary"
      >
        Start Camera
      </button>
    );
  }

  if (isRecording) {
    return (
      <button onClick={stopRecording} className="p-3 btn-success">
        <span className="i-lucide-square mr-2" />
        Stop Recording
      </button>
    );
  }

  // Preview mode - show filename input and controls
  return (
    <div className="flex flex-col gap-3">
      <div className="flex gap-2 items-center">
        <div className="flex items-center flex-1">
          <input
            type="text"
            value={streamFilename}
            onChange={(e) => {
              setStreamFilename(e.target.value.replace(/[^a-zA-Z0-9_-]/g, ''));
            }}
            placeholder="filename"
            className="flex-1 p-3 bg-surface-0 border border-surface-3 rounded-l text-text-1"
          />
          <span className="p-3 bg-surface-2 border border-surface-3 border-l-0 rounded-r text-muted">
            .webm
          </span>
        </div>
      </div>

      {filenameExists && (
        <div className="text-danger text-sm">
          Overwrites existing {streamFilename}.webm
        </div>
      )}

      {/* Storage mode toggle */}
      <div className="flex gap-2 text-sm">
        <button
          onClick={() => { setPersistStream(true); }}
          className={`flex-1 p-2 rounded-sm cursor-pointer ${
            persistStream
              ? 'bg-success text-white border-none'
              : 'bg-surface-2 text-muted border border-surface-3'
          }`}
        >
          Full Recording
        </button>
        <button
          onClick={() => { setPersistStream(false); }}
          className={`flex-1 p-2 rounded-sm cursor-pointer ${
            !persistStream
              ? 'bg-accent text-white border-none'
              : 'bg-surface-2 text-muted border border-surface-3'
          }`}
        >
          Live Only (30s)
        </button>
      </div>
      <div className="text-muted text-xs">
        {persistStream
          ? 'Saves entire stream to file'
          : 'Keeps only last 30 seconds (for live viewing)'}
      </div>

      <div className="flex gap-2">
        <button
          onClick={() => {
            startRecording(videoRef.current);
            onStartRecording(streamFilename);
          }}
          className="flex-1 p-3 btn-danger"
        >
          <span className="i-lucide-circle mr-2" />
          Start Recording
        </button>
        <button
          onClick={() => {
            stopPreview(videoRef.current);
            onCancel();
          }}
          className="p-3 btn-ghost"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}
